CREATE OR REPLACE VIEW v_reconciliation_customer_recordsv2 AS

-- 1. PROSPECT CUSTOMERS (sscaifp) - typed NULLs for columns not present in this table
SELECT
    CAST(KATIALLO.CUSTOMER_CODE AS NUMBER(9,0)) AS CUSTOMER_CODE,
    CAST(NULL AS VARCHAR2(8))    AS ZGADR4_Address_4,
    CAST(NULL AS VARCHAR2(8))    AS ZGADR5_Address_5,
    CAST(NULL AS VARCHAR2(8))    AS ZGADR6_Address_6,
    CAST(NULL AS VARCHAR2(8))    AS ZGADR7_Address_7,
    CAST(NULL AS VARCHAR2(8))    AS ZGADR8_Address_8,
    CAST(NULL AS VARCHAR2(8))    AS ZGADR9_Address_9,
    CAST(NULL AS NUMBER)         AS ZGNOCR_Num_Copies_Req,
    CAST(NULL AS VARCHAR2(112))  AS ZGDTCT_Date_Contact,
    CAST(NULL AS VARCHAR2(4))    AS ZGAUPU_Auto_Purge_Ind,
    CAST(NULL AS VARCHAR2(4))    AS ZGADRQ_Advice_Req_Code,
    CAST(NULL AS VARCHAR2(4))    AS ZGSCEI_Exempt_SvcChg_Ind,
    CAST(NULL AS NUMBER)         AS ZGFXBM_FX_Buy_Margin_Pct,
    CAST(NULL AS NUMBER)         AS ZGFXSM_FX_Sell_Margin_Pct,
    CAST(NULL AS VARCHAR2(16))   AS ZGCBBK_Corresp_Bank_ID,
    CAST(NULL AS VARCHAR2(16))   AS ZGCBBH_Corresp_Branch_ID,
    CAST(NULL AS VARCHAR2(4))    AS ZGVSHD_Visa_Holder_Ind,
    CAST(NULL AS VARCHAR2(4))    AS ZGMCHD_MC_Holder_Ind,
    CAST(NULL AS VARCHAR2(4))    AS ZGCGCH_ChqGuar_Holder_Ind,
    CAST(NULL AS VARCHAR2(12))   AS ZGCUCL_CB_Cust_Class,
    CAST(NULL AS NUMBER)         AS ZGINDY_Industry_Code,
    CAST(NULL AS VARCHAR2(112))  AS ZGDTAD_Date_Req_Added,
    CAST(NULL AS VARCHAR2(4))    AS ZGDROP_Drop_Ind,
    CAST(NULL AS VARCHAR2(112))  AS ZGGMDL_GIMIS_Load_Date,
    CAST(NULL AS VARCHAR2(4))    AS ZGRCAM_Repair_Chg_Method,
    CAST(NULL AS NUMBER)         AS ZGAPTA_AutoPost_Thresh_Amt,
    CAST(NULL AS VARCHAR2(8))    AS ZGPTRF_Pref_Tariff,
    CAST(NULL AS NUMBER)         AS ZGLGTP_Legal_Type,
    CAST(NULL AS NUMBER)         AS ZGCRDO_Acct_Officer,
    CAST(NULL AS NUMBER)         AS ZGLNSP_LastName_StartPos,
    CAST(NULL AS NUMBER)         AS ZGLNLN_LastName_Length,
    CAST(NULL AS NUMBER)         AS ZGFNSP_FirstName_StartPos,
    CAST(NULL AS NUMBER)         AS ZGFNLN_FirstName_Length,
    CAST(NULL AS NUMBER)         AS ZGTLSP_Title_StartPos,
    CAST(NULL AS NUMBER)         AS ZGTLLN_Title_Length,
    CAST(NULL AS NUMBER)         AS ZGITSP_Initial_StartPos,
    CAST(NULL AS NUMBER)         AS ZGITLN_Initial_Length,
    CAST(NULL AS VARCHAR2(4))    AS ZGCAST_Acct_Status,
    CAST(NULL AS VARCHAR2(4))    AS ZGRCBI_Client_Ind,
    p.ZUDLUP          AS ZGDLUP_Last_Update_Date,
    p.ZUTLUP          AS ZGTLUP_Last_Update_Time,
    CAST(NULL AS NUMBER)         AS ZGAPTT_InwardCbl_Thresh,
    CAST(NULL AS VARCHAR2(4))    AS ZGPTOD_Print_OD_Limit_Ind,
    CAST(NULL AS NUMBER)         AS ZGSTNO_Stmt_Seq_Num,
    CAST(NULL AS NUMBER)         AS ZGPMKS_Prev_Mkt_Sector,
    CAST(NULL AS VARCHAR2(112))  AS ZGMSD1_Curr_MktSect_Date,
    CAST(NULL AS VARCHAR2(112))  AS ZGMSD2_Prev_MktSect_Date,
    CAST(NULL AS VARCHAR2(40))   AS ZGTXNO_Tax_ID_Num,
    CAST(NULL AS VARCHAR2(4))    AS ZGAUGR_Auto_Grading,
    CAST(NULL AS NUMBER)         AS ZGRDDG_Random_Digit,
    CAST(NULL AS NUMBER)         AS ZGBSCR_Behaviour_Score,
    CAST(NULL AS NUMBER)         AS ZGPRAL_PreApproved_Limit,
    CAST(NULL AS VARCHAR2(800))  AS ZGVLOC_VLOC,
    p.ZUMDFL          AS ZGMDFL_Mode_Flag,
    p.ZURRN#          AS "ZGRRN#_Rel_Rec_Num",
    p.ZUCTCD          AS ZGCTCD_Country_Code,
    p.ZUDCG           AS ZGDCG_Dom_Cust_Grp,
    p.ZUDCB           AS ZGDCB_Customer_Branch,
    p.ZUDCS           AS ZGDCS_Customer_Serial,
    CAST(NULL AS VARCHAR2(12))   AS ZGGHCL_GHO_Class,
    p.ZUCSFN          AS ZGCSFN_Full_Name,
    p.ZUC2FN          AS ZGC2FN_Fullname_2_Lang,
    p.ZUCSCN          AS ZGCSCN_Cust_Name,
    p.ZUC2CN          AS ZGC2CN_Name_2_Lang,
    p.ZUCSSN          AS ZGCSSN_Short_Name,
    p.ZUC2SN          AS ZGC2SN_ShortName_2_Lang,
    CAST(NULL AS NUMBER)         AS ZGMKS1_Mkt_Sector_1,
    CAST(NULL AS NUMBER)         AS ZGMKP1_Mkt_Sect_Pct_1,
    CAST(NULL AS NUMBER)         AS ZGMKS2_Mkt_Sector_2,
    CAST(NULL AS NUMBER)         AS ZGMKP2_Mkt_Sect_Pct_2,
    CAST(NULL AS NUMBER)         AS ZGMKS3_Mkt_Sector_3,
    CAST(NULL AS NUMBER)         AS ZGMKP3_Mkt_Sect_Pct_3,
    CAST(NULL AS VARCHAR2(8))    AS ZGICC_IntlID_Country,
    CAST(NULL AS VARCHAR2(16))   AS ZGICG_IntlID_GroupMbr,
    CAST(NULL AS NUMBER)         AS ZGICB_IntlID_Branch,
    CAST(NULL AS NUMBER)         AS ZGICS_IntlID_Serial,
    p.ZUNATY          AS ZGNATY_Nationality,
    p.ZUIDTY          AS ZGIDTY_ID_Doc_Type,
    p.ZUIDNO          AS ZGIDNO_ID_Doc_Number,
    p.ZUCTRS          AS ZGCTRS_Country_Reg_Res,
    CAST(NULL AS VARCHAR2(4))    AS ZGLANG_Language,
    CAST(NULL AS VARCHAR2(4))    AS ZGGMCI_GIMIS_Cust_Ind,
    CAST(NULL AS VARCHAR2(4))    AS ZGEBCI_EBP_Cust_Ind,
    CAST(NULL AS VARCHAR2(4))    AS ZGICAI_Intl_Corp_AC_Ind,
    CAST(NULL AS VARCHAR2(4))    AS ZGCSRQ_Comp_Stmt_Req,
    CAST(NULL AS VARCHAR2(112))  AS ZGDTNS_Next_Stmt_Date,
    CAST(NULL AS VARCHAR2(112))  AS ZGDTN2_Spec_Next_Stmt_Dt,
    CAST(NULL AS VARCHAR2(4))    AS ZGSMCY_Stmt_Cycle,
    CAST(NULL AS VARCHAR2(4))    AS ZGSMC2_Spec_Stmt_Cycle,
    CAST(NULL AS VARCHAR2(8))    AS ZGADR1_Address_1,
    CAST(NULL AS VARCHAR2(8))    AS ZGADR2_Address_2,
    CAST(NULL AS VARCHAR2(8))    AS ZGADR3_Address_3,
    p.ZUDTBR         AS ZGDTBR_Date_of_Birth,
    0                AS ZKKID_No_Kids,
    CAST(NULL AS VARCHAR2(8))   AS ZKEDUC_Educ_Level
FROM DATACUT35.hub_mt_sscaifp@C2M p
JOIN (SELECT mci.PRFT_CUST_ID AS CUSTOMER_CODE , MCI.CUSTOMER_CODE AS CUSTOMER_CODE2
    FROM MG_CUSTOMER_INTER mci 
    WHERE mci.ROW_STATUS = 1  )  KATIALLO  ON trim(KATIALLO.CUSTOMER_CODE2)=  CONCAT('SSCAIFP-',p.SERIAL_NUMBER)  
WHERE p.customer_code2 = '0000000'

UNION ALL

-- 2. ACTIVE CUSTOMERS (sscustp)

SELECT /*+ DRIVING_SITE(c) */
    CAST(KATIALLO.CUSTOMER_CODE AS NUMBER (9,0)) AS CUSTOMER_CODE,
    c.ZGADR4  AS ZGADR4_Address_4,
    c.ZGADR5  AS ZGADR5_Address_5,
    c.ZGADR6  AS ZGADR6_Address_6,
    c.ZGADR7  AS ZGADR7_Address_7,
    c.ZGADR8  AS ZGADR8_Address_8,
    c.ZGADR9  AS ZGADR9_Address_9,
    c.ZGNOCR  AS ZGNOCR_Num_Copies_Req,
    c.ZGDTCT  AS ZGDTCT_Date_Contact,
    c.ZGAUPU  AS ZGAUPU_Auto_Purge_Ind,
    c.ZGADRQ  AS ZGADRQ_Advice_Req_Code,
    c.ZGSCEI  AS ZGSCEI_Exempt_SvcChg_Ind,
    c.ZGFXBM  AS ZGFXBM_FX_Buy_Margin_Pct,
    c.ZGFXSM  AS ZGFXSM_FX_Sell_Margin_Pct,
    c.ZGCBBK  AS ZGCBBK_Corresp_Bank_ID,
    c.ZGCBBH  AS ZGCBBH_Corresp_Branch_ID,
    c.ZGVSHD  AS ZGVSHD_Visa_Holder_Ind,
    c.ZGMCHD  AS ZGMCHD_MC_Holder_Ind,
    c.ZGCGCH  AS ZGCGCH_ChqGuar_Holder_Ind,
    c.ZGCUCL  AS ZGCUCL_CB_Cust_Class,
    c.ZGINDY  AS ZGINDY_Industry_Code,
    c.ZGDTAD  AS ZGDTAD_Date_Req_Added,
    c.ZGDROP  AS ZGDROP_Drop_Ind,
    c.ZGGMDL  AS ZGGMDL_GIMIS_Load_Date,
    c.ZGRCAM  AS ZGRCAM_Repair_Chg_Method,
    c.ZGAPTA  AS ZGAPTA_AutoPost_Thresh_Amt,
    c.ZGPTRF  AS ZGPTRF_Pref_Tariff,
    c.ZGLGTP  AS ZGLGTP_Legal_Type,
    c.ZGCRDO  AS ZGCRDO_Acct_Officer,
    c.ZGLNSP  AS ZGLNSP_LastName_StartPos,
    c.ZGLNLN  AS ZGLNLN_LastName_Length,
    c.ZGFNSP  AS ZGFNSP_FirstName_StartPos,
    c.ZGFNLN  AS ZGFNLN_FirstName_Length,
    c.ZGTLSP  AS ZGTLSP_Title_StartPos,
    c.ZGTLLN  AS ZGTLLN_Title_Length,
    c.ZGITSP  AS ZGITSP_Initial_StartPos,
    c.ZGITLN  AS ZGITLN_Initial_Length,
    c.ZGCAST  AS ZGCAST_Acct_Status,
    c.ZGRCBI  AS ZGRCBI_Client_Ind,
    c.ZGDLUP  AS ZGDLUP_Last_Update_Date,
    c.ZGTLUP  AS ZGTLUP_Last_Update_Time,
    c.ZGAPTT  AS ZGAPTT_InwardCbl_Thresh,
    c.ZGPTOD  AS ZGPTOD_Print_OD_Limit_Ind,
    c.ZGSTNO  AS ZGSTNO_Stmt_Seq_Num,
    c.ZGPMKS  AS ZGPMKS_Prev_Mkt_Sector,
    c.ZGMSD1  AS ZGMSD1_Curr_MktSect_Date,
    c.ZGMSD2  AS ZGMSD2_Prev_MktSect_Date,
    c.ZGTXNO  AS ZGTXNO_Tax_ID_Num,
    c.ZGAUGR  AS ZGAUGR_Auto_Grading,
    c.ZGRDDG  AS ZGRDDG_Random_Digit,
    c.ZGBSCR  AS ZGBSCR_Behaviour_Score,
    c.ZGPRAL  AS ZGPRAL_PreApproved_Limit,
    c.ZGVLOC  AS ZGVLOC_VLOC,
    c.ZGMDFL  AS ZGMDFL_Mode_Flag,
    c.ZGRRN#  AS "ZGRRN#_Rel_Rec_Num",
    c.ZGCTCD  AS ZGCTCD_Country_Code,
    c.ZGDCG   AS ZGDCG_Dom_Cust_Grp,
    c.ZGDCB   AS ZGDCB_Customer_Branch,
    c.ZGDCS   AS ZGDCS_Customer_Serial,
    c.ZGGHCL  AS ZGGHCL_GHO_Class,
    c.ZGCSFN  AS ZGCSFN_Full_Name,
    c.ZGC2FN  AS ZGC2FN_Fullname_2_Lang,
    c.ZGCSCN  AS ZGCSCN_Cust_Name,
    c.ZGC2CN  AS ZGC2CN_Name_2_Lang,
    c.ZGCSSN  AS ZGCSSN_Short_Name,
    c.ZGC2SN  AS ZGC2SN_ShortName_2_Lang,
    c.ZGMKS1  AS ZGMKS1_Mkt_Sector_1,
    c.ZGMKP1  AS ZGMKP1_Mkt_Sect_Pct_1,
    c.ZGMKS2  AS ZGMKS2_Mkt_Sector_2,
    c.ZGMKP2  AS ZGMKP2_Mkt_Sect_Pct_2,
    c.ZGMKS3  AS ZGMKS3_Mkt_Sector_3,
    c.ZGMKP3  AS ZGMKP3_Mkt_Sect_Pct_3,
    c.ZGICC   AS ZGICC_IntlID_Country,
    c.ZGICG   AS ZGICG_IntlID_GroupMbr,
    c.ZGICB   AS ZGICB_IntlID_Branch,
    c.ZGICS   AS ZGICS_IntlID_Serial,
    c.ZGNATY  AS ZGNATY_Nationality,
    c.ZGIDTY  AS ZGIDTY_ID_Doc_Type,
    c.ZGIDNO  AS ZGIDNO_ID_Doc_Number,
    c.ZGCTRS  AS ZGCTRS_Country_Reg_Res,
    c.ZGLANG  AS ZGLANG_Language,
    c.ZGGMCI  AS ZGGMCI_GIMIS_Cust_Ind,
    c.ZGEBCI  AS ZGEBCI_EBP_Cust_Ind,
    c.ZGICAI  AS ZGICAI_Intl_Corp_AC_Ind,
    c.ZGCSRQ  AS ZGCSRQ_Comp_Stmt_Req,
    c.ZGDTNS  AS ZGDTNS_Next_Stmt_Date,
    c.ZGDTN2  AS ZGDTN2_Spec_Next_Stmt_Dt,
    c.ZGSMCY  AS ZGSMCY_Stmt_Cycle,
    c.ZGSMC2  AS ZGSMC2_Spec_Stmt_Cycle,
    c.ZGADR1  AS ZGADR1_Address_1,
    c.ZGADR2  AS ZGADR2_Address_2,
    c.ZGADR3  AS ZGADR3_Address_3,
    i.ZKDTBR  AS ZGDTBR_Date_of_Birth,
    i.ZKKID   AS ZKKID_No_Kids,
    i.ZKEDUC  AS ZKEDUC_Educ_Level
FROM DATACUT35.hub_mt_sscustp@C2M c
JOIN (
    SELECT mci.PRFT_CUST_ID AS CUSTOMER_CODE, 
           TRIM(mci.CUSTOMER_CODE) AS CUSTOMER_CODE2
      FROM MG_CUSTOMER_INTER mci 
     WHERE mci.ROW_STATUS = 1  
) KATIALLO ON KATIALLO.CUSTOMER_CODE2 = c.customer_code
LEFT JOIN DATACUT35.hub_mt_ssincip@C2M i
       ON i.customer_code = c.customer_code
WHERE NOT EXISTS (
    SELECT 1
      FROM DATACUT35.hub_mt_ssprjip@C2M p
     WHERE p.customer_code = c.customer_code
)