SELECT CAST('CUSTOMER_CODE' AS NVARCHAR2(100)) AS MAPPING_FIELD,
       CAST(A.CUSTOMER_CODE AS NVARCHAR2(100)) AS HUB_VALUE,
       CAST(A.PRFT_CUST_ID AS NVARCHAR2(100)) AS PROFITS_VALUE
  FROM CREDIA_UAT1.MG_CUSTOMER_INTER A
 WHERE ROW_STATUS = 1

UNION ALL

SELECT CAST(PARAMETER_TYPE AS NVARCHAR2(100)) AS MAPPING_FIELD,
       CAST(OLD_VALUE AS NVARCHAR2(100)) AS HUB_VALUE,
       CAST(NVL(TO_CHAR(NEW_VALUE), NEW_TEXT_VALUE) AS NVARCHAR2(100)) AS PROFITS_VALUE
  FROM CREDIA_UAT1.MG_PARAM_PARAMETER mpp

UNION ALL

SELECT CAST('UNIT' AS NVARCHAR2(100)) AS MAPPING_FIELD,
       CAST(HUB_UNIT AS NVARCHAR2(100)) AS HUB_VALUE,
       CAST(PRFT_TYPE AS NVARCHAR2(100)) AS PROFITS_VALUE
  FROM (
        SELECT '2'  HUB_UNIT, '2'  PRFT_TYPE FROM DUAL UNION ALL
        SELECT '6'  HUB_UNIT, '6'  PRFT_TYPE FROM DUAL UNION ALL
        SELECT '7'  HUB_UNIT, '7'  PRFT_TYPE FROM DUAL UNION ALL
        SELECT '8'  HUB_UNIT, '8'  PRFT_TYPE FROM DUAL UNION ALL
        SELECT '9'  HUB_UNIT, '9'  PRFT_TYPE FROM DUAL UNION ALL
        SELECT '11' HUB_UNIT, '11' PRFT_TYPE FROM DUAL UNION ALL
        SELECT '12' HUB_UNIT, '12' PRFT_TYPE FROM DUAL UNION ALL
        SELECT '13' HUB_UNIT, '13' PRFT_TYPE FROM DUAL UNION ALL
        SELECT '16' HUB_UNIT, '16' PRFT_TYPE FROM DUAL UNION ALL
        SELECT '23' HUB_UNIT, '23' PRFT_TYPE FROM DUAL UNION ALL
        SELECT '25' HUB_UNIT, '25' PRFT_TYPE FROM DUAL UNION ALL
        SELECT '26' HUB_UNIT, '26' PRFT_TYPE FROM DUAL UNION ALL
        SELECT '27' HUB_UNIT, '27' PRFT_TYPE FROM DUAL UNION ALL
        SELECT '33' HUB_UNIT, '33' PRFT_TYPE FROM DUAL UNION ALL
        SELECT '37' HUB_UNIT, '37' PRFT_TYPE FROM DUAL UNION ALL
        SELECT '39' HUB_UNIT, '39' PRFT_TYPE FROM DUAL UNION ALL
        SELECT '40' HUB_UNIT, '40' PRFT_TYPE FROM DUAL UNION ALL
        SELECT '42' HUB_UNIT, '42' PRFT_TYPE FROM DUAL UNION ALL
        SELECT '43' HUB_UNIT, '43' PRFT_TYPE FROM DUAL UNION ALL
        SELECT '44' HUB_UNIT, '44' PRFT_TYPE FROM DUAL UNION ALL
        SELECT '47' HUB_UNIT, '47' PRFT_TYPE FROM DUAL UNION ALL
        SELECT '49' HUB_UNIT, '49' PRFT_TYPE FROM DUAL UNION ALL
        SELECT '50' HUB_UNIT, '50' PRFT_TYPE FROM DUAL UNION ALL
        SELECT '54' HUB_UNIT, '54' PRFT_TYPE FROM DUAL UNION ALL
        SELECT '56' HUB_UNIT, '56' PRFT_TYPE FROM DUAL UNION ALL
        SELECT '57' HUB_UNIT, '57' PRFT_TYPE FROM DUAL UNION ALL
        SELECT '58' HUB_UNIT, '58' PRFT_TYPE FROM DUAL UNION ALL
        SELECT '59' HUB_UNIT, '59' PRFT_TYPE FROM DUAL UNION ALL
        SELECT '61' HUB_UNIT, '61' PRFT_TYPE FROM DUAL UNION ALL
        SELECT '64' HUB_UNIT, '64' PRFT_TYPE FROM DUAL UNION ALL
        SELECT '65' HUB_UNIT, '65' PRFT_TYPE FROM DUAL UNION ALL
        SELECT '68' HUB_UNIT, '68' PRFT_TYPE FROM DUAL UNION ALL
        SELECT '71' HUB_UNIT, '71' PRFT_TYPE FROM DUAL UNION ALL
        SELECT '73' HUB_UNIT, '73' PRFT_TYPE FROM DUAL UNION ALL
        SELECT '74' HUB_UNIT, '74' PRFT_TYPE FROM DUAL UNION ALL
        SELECT '75' HUB_UNIT, '75' PRFT_TYPE FROM DUAL UNION ALL
        SELECT '78' HUB_UNIT, '78' PRFT_TYPE FROM DUAL UNION ALL
        SELECT '80' HUB_UNIT, '80' PRFT_TYPE FROM DUAL UNION ALL
        SELECT '81' HUB_UNIT, '81' PRFT_TYPE FROM DUAL UNION ALL
        SELECT '82' HUB_UNIT, '82' PRFT_TYPE FROM DUAL UNION ALL
        SELECT '83' HUB_UNIT, '83' PRFT_TYPE FROM DUAL UNION ALL
        SELECT '84' HUB_UNIT, '84' PRFT_TYPE FROM DUAL UNION ALL
        SELECT '85' HUB_UNIT, '85' PRFT_TYPE FROM DUAL UNION ALL
        SELECT '86' HUB_UNIT, '86' PRFT_TYPE FROM DUAL UNION ALL
        SELECT '87' HUB_UNIT, '87' PRFT_TYPE FROM DUAL UNION ALL
        SELECT '88' HUB_UNIT, '88' PRFT_TYPE FROM DUAL UNION ALL
        SELECT '89' HUB_UNIT, '89' PRFT_TYPE FROM DUAL UNION ALL
        SELECT '90' HUB_UNIT, '90' PRFT_TYPE FROM DUAL
       ) d

UNION ALL

SELECT CAST('CUST_TYPE' AS NVARCHAR2(100)) AS MAPPING_FIELD,
       CAST(HUB_TYPE AS NVARCHAR2(100)) AS HUB_VALUE,
       CAST(PRFT_TYPE AS NVARCHAR2(100)) AS PROFITS_VALUE
  FROM (SELECT 'I' HUB_TYPE, 1 PRFT_TYPE FROM DUAL
        UNION ALL
        SELECT 'N' HUB_TYPE, 2 PRFT_TYPE FROM DUAL) d

/* -- TEMPORARILY DISABLED: HGR_TCACMSP table does not exist yet in CREDIA_UAT1 (confirmed via all_tables check)
UNION ALL

SELECT DISTINCT CAST('LOAN_PRODUCT' AS NVARCHAR2(100)) AS MAPPING_FIELD,
       CAST(CDAPTY||'-'||CDCYCD AS NVARCHAR2(100)) AS HUB_VALUE,
       CAST(
        CASE
         WHEN LS.CDAPTY = 'CNM' THEN '44505'
         WHEN LS.CDAPTY = 'CNF' THEN '44501'
         WHEN LS.CDAPTY = 'FAG' THEN '44502'
         WHEN LS.CDAPTY = 'FLN' THEN '42101'
         WHEN LS.CDAPTY = 'HM1' THEN '43201'
         WHEN LS.CDAPTY = 'HM3' THEN '43202'
         WHEN LS.CDAPTY = 'HML' THEN '43203'
         WHEN LS.CDAPTY = 'HOL' THEN '43204'
         WHEN LS.CDAPTY = 'PIL' THEN '42102'
         WHEN LS.CDAPTY = 'PSL' THEN '42103'
         ELSE 'N/A'
        END AS NVARCHAR2(100)) AS PROFITS_VALUE
  FROM CREDIA_UAT1.HGR_TCACMSP LS
*/

UNION ALL

SELECT CAST('INST_FREQ' AS NVARCHAR2(100)) AS MAPPING_FIELD,
       CAST(HUB_TYPE AS NVARCHAR2(100)) AS HUB_VALUE,
       CAST(PRFT_TYPE AS NVARCHAR2(100)) AS PROFITS_VALUE
  FROM (SELECT 'M' HUB_TYPE, 1 PRFT_TYPE FROM DUAL
        UNION ALL
        SELECT 'Q' HUB_TYPE, 3 PRFT_TYPE FROM DUAL
        UNION ALL
        SELECT 'Y' HUB_TYPE, 12 PRFT_TYPE FROM DUAL) d

UNION ALL

SELECT CAST('EXTRAIT_FREQ' AS NVARCHAR2(100)) AS MAPPING_FIELD,
       CAST(HUB_TYPE AS NVARCHAR2(100)) AS HUB_VALUE,
       CAST(PRFT_TYPE AS NVARCHAR2(100)) AS PROFITS_VALUE
  FROM (SELECT 'M' HUB_TYPE, 1 PRFT_TYPE FROM DUAL
        UNION ALL
        SELECT 'Q' HUB_TYPE, 2 PRFT_TYPE FROM DUAL
        UNION ALL
        SELECT 'Y' HUB_TYPE, 4 PRFT_TYPE FROM DUAL) d

UNION ALL

SELECT CAST('LOAN_STATUS' AS NVARCHAR2(100)) AS MAPPING_FIELD,
       CAST(HUB_TYPE AS NVARCHAR2(100)) AS HUB_VALUE,
       CAST(PRFT_TYPE AS NVARCHAR2(100)) AS PROFITS_VALUE
  FROM (SELECT 'N' HUB_TYPE, 'Normal' PRFT_TYPE FROM DUAL
        UNION ALL
        SELECT 'Y' HUB_TYPE, 'Overdue' PRFT_TYPE FROM DUAL) d

UNION ALL

SELECT DISTINCT CAST('DEPOSIT_PRODUCT' AS NVARCHAR2(100)) AS MAPPING_FIELD,
       CAST(
        CASE P.PRODUCT_ID
         WHEN 36003 THEN 'CA1'
         WHEN 36003 THEN 'CA2'
         WHEN 31000 THEN 'SVO'
         WHEN 36000 THEN 'CA3'
         WHEN 36000 THEN 'CA4'
         WHEN 31600 THEN 'CA5'
         WHEN 31001 THEN 'CUD'
         WHEN 31601 THEN 'CUO'
         WHEN 31002 THEN 'SV7'
         WHEN 31003 THEN 'SSJ'
         WHEN 31007 THEN 'CUV'
         WHEN 31601 THEN 'CUR'
         WHEN 31004 THEN 'SV5'
         WHEN 31005 THEN 'SV1'
         WHEN 31005 THEN 'SV2'
         WHEN 31007 THEN 'CUT'
         WHEN 35102 THEN 'CNB'
         WHEN 31000 THEN 'SVR'
         WHEN 35102 THEN 'CNA'
         WHEN 31001 THEN 'CUE'
         WHEN 31000 THEN 'SSM'
         WHEN 31000 THEN 'SSN'
         WHEN 31003 THEN 'SSO'
         WHEN 36001 THEN 'CA8'
         WHEN 36002 THEN 'C10'
         WHEN 31002 THEN 'SVQ'
         WHEN 31000 THEN 'SSR'
         WHEN 37000 THEN 'TRC'
         WHEN 37001 THEN 'TMD'
         WHEN 37002 THEN 'TDS'
         WHEN 37003 THEN 'TDN'
         WHEN 37002 THEN 'TNO'
         WHEN 37004 THEN 'TIF'
         WHEN 37004 THEN 'TDI'
         WHEN 37002 THEN 'TON'
         WHEN 37002 THEN 'TD6'
         WHEN 37000 THEN 'TRO'
        END AS NVARCHAR2(100)) AS HUB_VALUE,
       CAST(P.PRODUCT_ID AS NVARCHAR2(100)) AS PROFITS_VALUE
  FROM CREDIA_UAT1.PROFITS_ACCOUNT P
  JOIN CREDIA_UAT1.DEPOSIT_ACCOUNT D ON P.DEP_ACC_NUMBER = D.ACCOUNT_NUMBER
 WHERE EXISTS (SELECT 1 FROM CREDIA_UAT1.MG_CUST_DPAC_INTER mg WHERE p.ACCOUNT_NUMBER = mg.ACCOUNT_NO)

UNION ALL

SELECT CAST('STATEMENT_FREQ' AS NVARCHAR2(100)) AS MAPPING_FIELD,
       CAST(HUB_TYPE AS NVARCHAR2(100)) AS HUB_VALUE,
       CAST(PRFT_TYPE AS NVARCHAR2(100)) AS PROFITS_VALUE
  FROM (SELECT 'M' HUB_TYPE, 10 PRFT_TYPE FROM DUAL
        UNION ALL
        SELECT 'Q' HUB_TYPE, 12 PRFT_TYPE FROM DUAL
        UNION ALL
        SELECT 'H' HUB_TYPE, 13 PRFT_TYPE FROM DUAL
        UNION ALL
        SELECT 'Y' HUB_TYPE, 14 PRFT_TYPE FROM DUAL) d

UNION ALL

SELECT CAST('DEPOSIT_STATUS' AS NVARCHAR2(100)) AS MAPPING_FIELD,
       CAST(HUB_TYPE AS NVARCHAR2(100)) AS HUB_VALUE,
       CAST(PRFT_TYPE AS NVARCHAR2(100)) AS PROFITS_VALUE
  FROM (SELECT '1&1' HUB_TYPE, '1' PRFT_TYPE FROM DUAL
        UNION ALL SELECT '2&1' HUB_TYPE, '1' PRFT_TYPE FROM DUAL
        UNION ALL SELECT '3&1' HUB_TYPE, '2' PRFT_TYPE FROM DUAL
        UNION ALL SELECT '3&2' HUB_TYPE, '2' PRFT_TYPE FROM DUAL
        UNION ALL SELECT '3&3' HUB_TYPE, '2' PRFT_TYPE FROM DUAL
        UNION ALL SELECT '4&1' HUB_TYPE, '5' PRFT_TYPE FROM DUAL
        UNION ALL SELECT '4&2' HUB_TYPE, '5' PRFT_TYPE FROM DUAL
        UNION ALL SELECT '4&3' HUB_TYPE, '5' PRFT_TYPE FROM DUAL
        UNION ALL SELECT '1&2' HUB_TYPE, '6' PRFT_TYPE FROM DUAL
        UNION ALL SELECT '2&2' HUB_TYPE, '6' PRFT_TYPE FROM DUAL
        UNION ALL SELECT '1&3' HUB_TYPE, '8' PRFT_TYPE FROM DUAL
        UNION ALL SELECT '2&3' HUB_TYPE, '8' PRFT_TYPE FROM DUAL
        UNION ALL SELECT '5&1' HUB_TYPE, '1' PRFT_TYPE FROM DUAL
        UNION ALL SELECT '5&2' HUB_TYPE, '6' PRFT_TYPE FROM DUAL
        UNION ALL SELECT '5&3' HUB_TYPE, '8' PRFT_TYPE FROM DUAL) d

UNION ALL

SELECT DISTINCT CAST('DEP_DEBIT_INTEREST' AS NVARCHAR2(100)) AS MAPPING_FIELD,
       CAST(D1HORT AS NVARCHAR2(100)) AS HUB_VALUE,
       CAST(DB_ID_INTEREST AS NVARCHAR2(100)) AS PROFITS_VALUE
  FROM CREDIA_UAT1.MG_HGR_OVD_INTERESTS

UNION ALL

SELECT DISTINCT CAST('DEP_CREDIT_INTEREST' AS NVARCHAR2(100)) AS MAPPING_FIELD,
       CAST(DGCIRT AS NVARCHAR2(100)) AS HUB_VALUE,
       CAST(CR_ID_INTEREST AS NVARCHAR2(100)) AS PROFITS_VALUE
  FROM CREDIA_UAT1.MG_HGR_OVD_INTERESTS

UNION ALL

SELECT CAST('DAYS_BASE' AS NVARCHAR2(100)) AS MAPPING_FIELD,
       CAST(HUB_TYPE AS NVARCHAR2(100)) AS HUB_VALUE,
       CAST(PRFT_TYPE AS NVARCHAR2(100)) AS PROFITS_VALUE
  FROM (SELECT 'A' HUB_TYPE, '360' PRFT_TYPE FROM DUAL
        UNION ALL SELECT 'B' HUB_TYPE, '360' PRFT_TYPE FROM DUAL
        UNION ALL SELECT 'C' HUB_TYPE, '365' PRFT_TYPE FROM DUAL
        UNION ALL SELECT 'D' HUB_TYPE, '365' PRFT_TYPE FROM DUAL
        UNION ALL SELECT 'E' HUB_TYPE, '365' PRFT_TYPE FROM DUAL
        UNION ALL SELECT 'F' HUB_TYPE, '365' PRFT_TYPE FROM DUAL) d

UNION ALL

SELECT CAST('DEPOSITS_INTEREST_APPLICATION_CYCLE' AS NVARCHAR2(100)) AS MAPPING_FIELD,
       CAST(HUB_TYPE AS NVARCHAR2(100)) AS HUB_VALUE,
       CAST(PRFT_TYPE AS NVARCHAR2(100)) AS PROFITS_VALUE
  FROM (SELECT 'M' HUB_TYPE, 1 PRFT_TYPE FROM DUAL
        UNION ALL SELECT 'Q' HUB_TYPE, 3 PRFT_TYPE FROM DUAL
        UNION ALL SELECT 'H' HUB_TYPE, 6 PRFT_TYPE FROM DUAL
        UNION ALL SELECT 'Y' HUB_TYPE, 12 PRFT_TYPE FROM DUAL) d

UNION ALL

SELECT CAST('SCHEDULED DATE' AS NVARCHAR2(100)) AS MAPPING_FIELD,
       CAST(NULL AS NVARCHAR2(100)) AS HUB_VALUE,
       CAST(SCHEDULED_DATE AS NVARCHAR2(100)) AS PROFITS_VALUE
  FROM CREDIA_UAT1.BANK_PARAMETERS

UNION ALL

SELECT CAST('TD_MATURITY_INST' AS NVARCHAR2(100)) AS MAPPING_FIELD,
       CAST(HUB_TYPE AS NVARCHAR2(100)) AS HUB_VALUE,
       CAST(PROFITS_VALUE AS NVARCHAR2(100)) AS PROFITS_VALUE
  FROM (SELECT '1-1' HUB_TYPE, 'Interest Capitalization' PROFITS_VALUE FROM DUAL
        UNION ALL SELECT '0-0' HUB_TYPE, 'Cash' PROFITS_VALUE FROM DUAL
        UNION ALL SELECT '0-3' HUB_TYPE, 'Cash' PROFITS_VALUE FROM DUAL
        UNION ALL SELECT '0-3' HUB_TYPE, 'Transfer to service account' PROFITS_VALUE FROM DUAL
        UNION ALL SELECT '1-2' HUB_TYPE, 'Transfer to service account' PROFITS_VALUE FROM DUAL) d
