
SELECT
       'Customers' AS CHECK_TYPE,
       C.CHECK_ID, C.CHECK_NAME, C.CATEGORY,
       C.RESULT_NUM, C.RESULT_TOTAL, C.RESULT_TXT,
       CASE WHEN C.CATEGORY = 'NOT_FOUND' THEN 'INFO'
            WHEN C.RESULT_NUM = 0            THEN 'PASS'
            ELSE 'REVIEW' END AS STATUS
  FROM (


SELECT 'CM-001' AS CHECK_ID, 'Branch_Code mismatch vs SSCUSTP.ZGDCB' AS CHECK_NAME,
       'CONFIRMED' AS CATEGORY, COUNT(*) AS RESULT_NUM,
       TOT1.RESULT_TOTAL AS RESULT_TOTAL,
       CAST(NULL AS VARCHAR2(200)) AS RESULT_TXT
  FROM NCIS_Customers n
  JOIN MG_CUSTOMER_INTER mci ON mci.PRFT_CUST_ID = n.Customer_Code
  JOIN HUB_MT_SSCUSTP s ON TRIM(s.CUSTOMER_CODE) = TRIM(mci.CUSTOMER_CODE)

  CROSS JOIN (SELECT COUNT(*) AS RESULT_TOTAL
          FROM NCIS_Customers n1
          JOIN MG_CUSTOMER_INTER mci1 ON mci1.PRFT_CUST_ID = n1.Customer_Code
          JOIN HUB_MT_SSCUSTP s1 ON TRIM(s1.CUSTOMER_CODE) = TRIM(mci1.CUSTOMER_CODE)) TOT1 WHERE TRIM(TO_CHAR(n.Branch_Code)) <> TRIM(TO_CHAR(s.ZGDCB))
    OR (n.Branch_Code IS NULL AND s.ZGDCB IS NOT NULL)
    OR (n.Branch_Code IS NOT NULL AND s.ZGDCB IS NULL)
 GROUP BY TOT1.RESULT_TOTAL

UNION ALL
SELECT 'CM-002' AS CHECK_ID,
       'Date_of_Birth mismatch vs SSINCIP.ZKDTBR' AS CHECK_NAME,
       'CONFIRMED' AS CATEGORY,
       COUNT(*) AS RESULT_NUM,
       TOT2.RESULT_TOTAL AS RESULT_TOTAL,
       CAST(NULL AS VARCHAR2(200)) AS RESULT_TXT
  FROM NCIS_Customers n
  JOIN MG_CUSTOMER_INTER mci ON mci.PRFT_CUST_ID = n.Customer_Code
  JOIN HUB_MT_SSINCIP i ON TRIM(i.CUSTOMER_CODE) = TRIM(mci.CUSTOMER_CODE)

  CROSS JOIN (SELECT COUNT(*) AS RESULT_TOTAL
          FROM NCIS_Customers n2
          JOIN MG_CUSTOMER_INTER mci2 ON mci2.PRFT_CUST_ID = n2.Customer_Code
          JOIN HUB_MT_SSINCIP i2 ON TRIM(i2.CUSTOMER_CODE) = TRIM(mci2.CUSTOMER_CODE)) TOT2 WHERE NVL(TO_CHAR(n.Date_of_Birth,'YYYYMMDD'),'X') <> 
       CASE 
         WHEN TRIM(i.ZKDTBR) = '99999999' THEN '19010101'
         ELSE NVL(TRIM(i.ZKDTBR),'X')
       END
 GROUP BY TOT2.RESULT_TOTAL

UNION ALL
SELECT 'CM-003' AS CHECK_ID, 'Sex mismatch vs SSINCIP.ZKSEX' AS CHECK_NAME,
       'CONFIRMED' AS CATEGORY, COUNT(*) AS RESULT_NUM,
       TOT3.RESULT_TOTAL AS RESULT_TOTAL,
       CAST(NULL AS VARCHAR2(200)) AS RESULT_TXT
  FROM NCIS_Customers n
  JOIN MG_CUSTOMER_INTER mci ON mci.PRFT_CUST_ID = n.Customer_Code
  JOIN HUB_MT_SSINCIP i ON TRIM(i.CUSTOMER_CODE) = TRIM(mci.CUSTOMER_CODE)

  CROSS JOIN (SELECT COUNT(*) AS RESULT_TOTAL
          FROM NCIS_Customers n3
          JOIN MG_CUSTOMER_INTER mci3 ON mci3.PRFT_CUST_ID = n3.Customer_Code
          JOIN HUB_MT_SSINCIP i3 ON TRIM(i3.CUSTOMER_CODE) = TRIM(mci3.CUSTOMER_CODE)) TOT3 WHERE CASE 
         WHEN n.Customer_Type = 1 AND (i.ZKSEX IS NULL OR TRIM(i.ZKSEX) = '') AND TRIM(n.Sex) = 'M' 
           THEN 'MATCH_FOUND'
         WHEN TRIM(i.ZKSEX) = 'X' AND TRIM(n.Sex) = 'M' 
           THEN 'MATCH_FOUND'
         ELSE NVL(TRIM(n.Sex), 'X')
       END
       <>
       CASE 
         WHEN n.Customer_Type = 1 AND (i.ZKSEX IS NULL OR TRIM(i.ZKSEX) = '') AND TRIM(n.Sex) = 'M' 
           THEN 'MATCH_FOUND'
         WHEN TRIM(i.ZKSEX) = 'X' AND TRIM(n.Sex) = 'M' 
           THEN 'MATCH_FOUND'
         ELSE NVL(TRIM(i.ZKSEX), 'X')
       END
 GROUP BY TOT3.RESULT_TOTAL

UNION ALL
SELECT 'CM-004', 'Nationality mismatch vs SSCUSTP.ZGNATY',
       'CONFIRMED', COUNT(*),
       TOT4.RESULT_TOTAL AS RESULT_TOTAL,
       CAST(NULL AS VARCHAR2(200))
  FROM NCIS_Customers n
  JOIN MG_CUSTOMER_INTER mci ON mci.PRFT_CUST_ID = n.Customer_Code
  JOIN HUB_MT_SSCUSTP s ON TRIM(s.CUSTOMER_CODE) = TRIM(mci.CUSTOMER_CODE)

  CROSS JOIN (SELECT COUNT(*) AS RESULT_TOTAL
          FROM NCIS_Customers n4
          JOIN MG_CUSTOMER_INTER mci4 ON mci4.PRFT_CUST_ID = n4.Customer_Code
          JOIN HUB_MT_SSCUSTP s4 ON TRIM(s4.CUSTOMER_CODE) = TRIM(mci4.CUSTOMER_CODE)) TOT4 WHERE NVL(TRIM(n.Nationality),'X') <> NVL(TRIM(s.ZGNATY),'X')
 GROUP BY TOT4.RESULT_TOTAL

UNION ALL
SELECT 'CM-005', 'Communication_Language mismatch vs SSCUSTP.ZGLANG',
       'CONFIRMED', COUNT(*),
       TOT5.RESULT_TOTAL AS RESULT_TOTAL,
       CAST(NULL AS VARCHAR2(200))
  FROM NCIS_Customers n
  JOIN MG_CUSTOMER_INTER mci ON mci.PRFT_CUST_ID = n.Customer_Code
  JOIN HUB_MT_SSCUSTP s ON TRIM(s.CUSTOMER_CODE) = TRIM(mci.CUSTOMER_CODE)

  CROSS JOIN (SELECT COUNT(*) AS RESULT_TOTAL
          FROM NCIS_Customers n5
          JOIN MG_CUSTOMER_INTER mci5 ON mci5.PRFT_CUST_ID = n5.Customer_Code
          JOIN HUB_MT_SSCUSTP s5 ON TRIM(s5.CUSTOMER_CODE) = TRIM(mci5.CUSTOMER_CODE)) TOT5 WHERE NVL(TRIM(n.Communication_Language),'X') <> NVL(TRIM(s.ZGLANG),'X')
 GROUP BY TOT5.RESULT_TOTAL

UNION ALL
SELECT 'CM-006', 'Number_of_Children mismatch vs SSINCIP.ZKKID',
       'CONFIRMED', COUNT(*),
       TOT6.RESULT_TOTAL AS RESULT_TOTAL,
       CAST(NULL AS VARCHAR2(200))
  FROM NCIS_Customers n
  JOIN MG_CUSTOMER_INTER mci ON mci.PRFT_CUST_ID = n.Customer_Code
  JOIN HUB_MT_SSINCIP i ON TRIM(i.CUSTOMER_CODE) = TRIM(mci.CUSTOMER_CODE)

  CROSS JOIN (SELECT COUNT(*) AS RESULT_TOTAL
          FROM NCIS_Customers n6
          JOIN MG_CUSTOMER_INTER mci6 ON mci6.PRFT_CUST_ID = n6.Customer_Code
          JOIN HUB_MT_SSINCIP i6 ON TRIM(i6.CUSTOMER_CODE) = TRIM(mci6.CUSTOMER_CODE)) TOT6 WHERE NVL(TO_NUMBER(n.Number_of_Children),-1) <> NVL(TO_NUMBER(i.ZKKID),-1)
 GROUP BY TOT6.RESULT_TOTAL

UNION ALL
SELECT 'CM-007', 'Education_Level mismatch vs SSINCIP.ZKEDUC',
       'CONFIRMED', COUNT(*),
       TOT7.RESULT_TOTAL AS RESULT_TOTAL,
       CAST(NULL AS VARCHAR2(200))
  FROM NCIS_Customers n
  JOIN MG_CUSTOMER_INTER mci ON mci.PRFT_CUST_ID = n.Customer_Code
  JOIN HUB_MT_SSINCIP i ON TRIM(i.CUSTOMER_CODE) = TRIM(mci.CUSTOMER_CODE)

  CROSS JOIN (SELECT COUNT(*) AS RESULT_TOTAL
          FROM NCIS_Customers n7
          JOIN MG_CUSTOMER_INTER mci7 ON mci7.PRFT_CUST_ID = n7.Customer_Code
          JOIN HUB_MT_SSINCIP i7 ON TRIM(i7.CUSTOMER_CODE) = TRIM(mci7.CUSTOMER_CODE)) TOT7 WHERE NVL(TRIM(n.Education_Level),'X') <> NVL(TRIM(i.ZKEDUC),'X')
 GROUP BY TOT7.RESULT_TOTAL

UNION ALL
SELECT 'CM-008', 'Identification_ID_Type mismatch vs SSCUSTP.ZGIDTY (PROBABLE — confirm mapping)',
       'PROBABLE', COUNT(*),
       TOT8.RESULT_TOTAL AS RESULT_TOTAL,
       CAST(NULL AS VARCHAR2(200))
  FROM NCIS_Customers n
  JOIN MG_CUSTOMER_INTER mci ON mci.PRFT_CUST_ID = n.Customer_Code
  JOIN HUB_MT_SSCUSTP s ON TRIM(s.CUSTOMER_CODE) = TRIM(mci.CUSTOMER_CODE)

  CROSS JOIN (SELECT COUNT(*) AS RESULT_TOTAL
          FROM NCIS_Customers n8
          JOIN MG_CUSTOMER_INTER mci8 ON mci8.PRFT_CUST_ID = n8.Customer_Code
          JOIN HUB_MT_SSCUSTP s8 ON TRIM(s8.CUSTOMER_CODE) = TRIM(mci8.CUSTOMER_CODE)) TOT8 WHERE NVL(TRIM(TO_CHAR(n.Identification_ID_Type)),'X') <> NVL(TRIM(s.ZGIDTY),'X')
 GROUP BY TOT8.RESULT_TOTAL

UNION ALL
SELECT 'CM-009', 'Identification_ID mismatch vs SSCUSTP.ZGIDNO (PROBABLE — confirm mapping)',
       'PROBABLE', COUNT(*),
       TOT9.RESULT_TOTAL AS RESULT_TOTAL,
       CAST(NULL AS VARCHAR2(200))
  FROM NCIS_Customers n
  JOIN MG_CUSTOMER_INTER mci ON mci.PRFT_CUST_ID = n.Customer_Code
  JOIN HUB_MT_SSCUSTP s ON TRIM(s.CUSTOMER_CODE) = TRIM(mci.CUSTOMER_CODE)

  CROSS JOIN (SELECT COUNT(*) AS RESULT_TOTAL
          FROM NCIS_Customers n9
          JOIN MG_CUSTOMER_INTER mci9 ON mci9.PRFT_CUST_ID = n9.Customer_Code
          JOIN HUB_MT_SSCUSTP s9 ON TRIM(s9.CUSTOMER_CODE) = TRIM(mci9.CUSTOMER_CODE)) TOT9 WHERE NVL(TRIM(n.Identification_ID),'X') <> NVL(TRIM(s.ZGIDNO),'X')
 GROUP BY TOT9.RESULT_TOTAL

UNION ALL
SELECT 'CM-010', 'Tax_ID mismatch vs SSCUSTP.ZGTXNO (PROBABLE — confirm mapping)',
       'PROBABLE', COUNT(*),
       TOT10.RESULT_TOTAL AS RESULT_TOTAL,
       CAST(NULL AS VARCHAR2(200))
  FROM NCIS_Customers n
  JOIN MG_CUSTOMER_INTER mci ON mci.PRFT_CUST_ID = n.Customer_Code
  JOIN HUB_MT_SSCUSTP s ON TRIM(s.CUSTOMER_CODE) = TRIM(mci.CUSTOMER_CODE)

  CROSS JOIN (SELECT COUNT(*) AS RESULT_TOTAL
          FROM NCIS_Customers n10
          JOIN MG_CUSTOMER_INTER mci10 ON mci10.PRFT_CUST_ID = n10.Customer_Code
          JOIN HUB_MT_SSCUSTP s10 ON TRIM(s10.CUSTOMER_CODE) = TRIM(mci10.CUSTOMER_CODE)) TOT10 WHERE NVL(TRIM(n.Tax_ID),'X') <> NVL(TRIM(s.ZGTXNO),'X')
 GROUP BY TOT10.RESULT_TOTAL

UNION ALL
SELECT 'CM-011', 'Family_Status mismatch vs SSINCIP.ZKMST (PROBABLE — confirm mapping)',
       'PROBABLE', COUNT(*),
       TOT11.RESULT_TOTAL AS RESULT_TOTAL,
       CAST(NULL AS VARCHAR2(200))
  FROM NCIS_Customers n
  JOIN MG_CUSTOMER_INTER mci ON mci.PRFT_CUST_ID = n.Customer_Code
  JOIN HUB_MT_SSINCIP i ON TRIM(i.CUSTOMER_CODE) = TRIM(mci.CUSTOMER_CODE)

  CROSS JOIN (SELECT COUNT(*) AS RESULT_TOTAL
          FROM NCIS_Customers n11
          JOIN MG_CUSTOMER_INTER mci11 ON mci11.PRFT_CUST_ID = n11.Customer_Code
          JOIN HUB_MT_SSINCIP i11 ON TRIM(i11.CUSTOMER_CODE) = TRIM(mci11.CUSTOMER_CODE)) TOT11 WHERE NVL(TRIM(n.Family_Status),'X') <> NVL(TRIM(i.ZKMST),'X')
 GROUP BY TOT11.RESULT_TOTAL

UNION ALL
SELECT 'CM-012', 'Activity_Code mismatch vs SSCUSTP.ZGINDY (PROBABLE — confirm mapping, see A5)',
       'PROBABLE', COUNT(*),
       TOT12.RESULT_TOTAL AS RESULT_TOTAL,
       CAST(NULL AS VARCHAR2(200))
  FROM NCIS_Customers n
  JOIN MG_CUSTOMER_INTER mci ON mci.PRFT_CUST_ID = n.Customer_Code
  JOIN HUB_MT_SSCUSTP s ON TRIM(s.CUSTOMER_CODE) = TRIM(mci.CUSTOMER_CODE)

  CROSS JOIN (SELECT COUNT(*) AS RESULT_TOTAL
          FROM NCIS_Customers n12
          JOIN MG_CUSTOMER_INTER mci12 ON mci12.PRFT_CUST_ID = n12.Customer_Code
          JOIN HUB_MT_SSCUSTP s12 ON TRIM(s12.CUSTOMER_CODE) = TRIM(mci12.CUSTOMER_CODE)) TOT12 WHERE NVL(TRIM(TO_CHAR(n.Activity_Code)),'X') <> NVL(TRIM(TO_CHAR(s.ZGINDY)),'X')
 GROUP BY TOT12.RESULT_TOTAL

UNION ALL
SELECT 'CM-013', 'Profession mismatch vs SSINCIP.ZKOCPT (PROBABLE — confirm mapping)',
       'PROBABLE', COUNT(*),
       TOT13.RESULT_TOTAL AS RESULT_TOTAL,
       CAST(NULL AS VARCHAR2(200))
  FROM NCIS_Customers n
  JOIN MG_CUSTOMER_INTER mci ON mci.PRFT_CUST_ID = n.Customer_Code
  JOIN HUB_MT_SSINCIP i ON TRIM(i.CUSTOMER_CODE) = TRIM(mci.CUSTOMER_CODE)

  CROSS JOIN (SELECT COUNT(*) AS RESULT_TOTAL
          FROM NCIS_Customers n13
          JOIN MG_CUSTOMER_INTER mci13 ON mci13.PRFT_CUST_ID = n13.Customer_Code
          JOIN HUB_MT_SSINCIP i13 ON TRIM(i13.CUSTOMER_CODE) = TRIM(mci13.CUSTOMER_CODE)) TOT13 WHERE NVL(TRIM(n.Profession),'X') <> NVL(TRIM(i.ZKOCPT),'X')
 GROUP BY TOT13.RESULT_TOTAL

UNION ALL
SELECT 'CM-014', 'Corporation_Registry_Number mismatch vs SSNICIP.XUINCN (PROBABLE — non-individual only)',
       'PROBABLE', COUNT(*),
       TOT14.RESULT_TOTAL AS RESULT_TOTAL,
       CAST(NULL AS VARCHAR2(200))
  FROM NCIS_Customers n
  JOIN MG_CUSTOMER_INTER mci ON mci.PRFT_CUST_ID = n.Customer_Code
  JOIN HUB_MT_SSNICIP ni ON TRIM(ni.CUSTOMER_CODE) = TRIM(mci.CUSTOMER_CODE)

  CROSS JOIN (SELECT COUNT(*) AS RESULT_TOTAL
          FROM NCIS_Customers n14
          JOIN MG_CUSTOMER_INTER mci14 ON mci14.PRFT_CUST_ID = n14.Customer_Code
          JOIN HUB_MT_SSNICIP ni14 ON TRIM(ni14.CUSTOMER_CODE) = TRIM(mci14.CUSTOMER_CODE)
         WHERE n14.Corporation_Registry_Number IS NOT NULL) TOT14 WHERE n.Corporation_Registry_Number IS NOT NULL
   AND NVL(TRIM(n.Corporation_Registry_Number),'X') <> NVL(TRIM(ni.XUINCN),'X')
 GROUP BY TOT14.RESULT_TOTAL

UNION ALL
SELECT 'CM-015', 'Legal_Form mismatch vs SSCUSTP.ZGLGTP (PROBABLE — confirm mapping)',
       'PROBABLE', COUNT(*),
       TOT15.RESULT_TOTAL AS RESULT_TOTAL,
       CAST(NULL AS VARCHAR2(200))
  FROM NCIS_Customers n
  JOIN MG_CUSTOMER_INTER mci ON mci.PRFT_CUST_ID = n.Customer_Code
  JOIN HUB_MT_SSCUSTP s ON TRIM(s.CUSTOMER_CODE) = TRIM(mci.CUSTOMER_CODE)

  CROSS JOIN (SELECT COUNT(*) AS RESULT_TOTAL
          FROM NCIS_Customers n15
          JOIN MG_CUSTOMER_INTER mci15 ON mci15.PRFT_CUST_ID = n15.Customer_Code
          JOIN HUB_MT_SSCUSTP s15 ON TRIM(s15.CUSTOMER_CODE) = TRIM(mci15.CUSTOMER_CODE)) TOT15 WHERE NVL(TRIM(TO_CHAR(n.Legal_Form)),'X') <> NVL(TRIM(s.ZGLGTP),'X')
 GROUP BY TOT15.RESULT_TOTAL

UNION ALL
SELECT 'CM-016', 'Customer_Type distribution vs SSGHCLP.VQCSTY (LOW CONFIDENCE — for review only)',
       'PROBABLE', COUNT(*),
       TOT16.RESULT_TOTAL AS RESULT_TOTAL,
       CAST(NULL AS VARCHAR2(200))
  FROM NCIS_Customers n
  JOIN MG_CUSTOMER_INTER mci ON mci.PRFT_CUST_ID = n.Customer_Code
  JOIN HUB_MT_SSCUSTP s ON TRIM(s.CUSTOMER_CODE) = TRIM(mci.CUSTOMER_CODE)
  JOIN HUB_MT_SSGHCLP g ON TRIM(s.ZGGHCL) = TRIM(g.VQGHCL)

  CROSS JOIN (SELECT COUNT(*) AS RESULT_TOTAL
          FROM NCIS_Customers n16
          JOIN MG_CUSTOMER_INTER mci16 ON mci16.PRFT_CUST_ID = n16.Customer_Code
          JOIN HUB_MT_SSCUSTP s16 ON TRIM(s16.CUSTOMER_CODE) = TRIM(mci16.CUSTOMER_CODE)
          JOIN HUB_MT_SSGHCLP g16 ON TRIM(s16.ZGGHCL) = TRIM(g16.VQGHCL)) TOT16 WHERE NVL(TRIM(TO_CHAR(n.Customer_Type)),'X') <> NVL(TRIM(g.VQCSTY),'X')
 GROUP BY TOT16.RESULT_TOTAL

UNION ALL
SELECT 'CM-017', 'Customer_Check_Digit — TODO: no confirmed HUB field (see A3)',
       'NOT_FOUND', COUNT(*), TOT17.RESULT_TOTAL, CAST(NULL AS VARCHAR2(200))
  FROM NCIS_Customers
  CROSS JOIN (SELECT COUNT(*) AS RESULT_TOTAL FROM NCIS_Customers) TOT17 WHERE Customer_Check_Digit IS NOT NULL
 GROUP BY TOT17.RESULT_TOTAL

UNION ALL
SELECT 'CM-018', 'First_Name — TODO: derived field only (ZGFNSP/ZGFNLN substring), not directly comparable',
       'NOT_FOUND', COUNT(*), TOT18.RESULT_TOTAL, CAST(NULL AS VARCHAR2(200))
  FROM NCIS_Customers
  CROSS JOIN (SELECT COUNT(*) AS RESULT_TOTAL FROM NCIS_Customers) TOT18 WHERE First_Name IS NOT NULL
 GROUP BY TOT18.RESULT_TOTAL

UNION ALL
SELECT 'CM-019', 'Surname — TODO: derived field only (ZGLNSP/ZGLNLN substring), not directly comparable',
       'NOT_FOUND', COUNT(*), TOT19.RESULT_TOTAL, CAST(NULL AS VARCHAR2(200))
  FROM NCIS_Customers
  CROSS JOIN (SELECT COUNT(*) AS RESULT_TOTAL FROM NCIS_Customers) TOT19 WHERE Surname IS NOT NULL
 GROUP BY TOT19.RESULT_TOTAL

UNION ALL
SELECT 'CM-020', 'Father_name — TODO: no confirmed HUB field',
       'NOT_FOUND', COUNT(*), TOT20.RESULT_TOTAL, CAST(NULL AS VARCHAR2(200))
  FROM NCIS_Customers
  CROSS JOIN (SELECT COUNT(*) AS RESULT_TOTAL FROM NCIS_Customers) TOT20 WHERE Father_name IS NOT NULL
 GROUP BY TOT20.RESULT_TOTAL

UNION ALL
SELECT 'CM-021', 'Country_of_Birth — TODO: no confirmed HUB field',
       'NOT_FOUND', COUNT(*), TOT21.RESULT_TOTAL, CAST(NULL AS VARCHAR2(200))
  FROM NCIS_Customers
  CROSS JOIN (SELECT COUNT(*) AS RESULT_TOTAL FROM NCIS_Customers) TOT21 WHERE Country_of_Birth IS NOT NULL
 GROUP BY TOT21.RESULT_TOTAL

UNION ALL
SELECT 'CM-022', 'Identification_ID_Issue_Date — TODO: no confirmed HUB field',
       'NOT_FOUND', COUNT(*), TOT22.RESULT_TOTAL, CAST(NULL AS VARCHAR2(200))
  FROM NCIS_Customers
  CROSS JOIN (SELECT COUNT(*) AS RESULT_TOTAL FROM NCIS_Customers) TOT22 WHERE Identification_ID_Issue_Date IS NOT NULL
 GROUP BY TOT22.RESULT_TOTAL

UNION ALL
SELECT 'CM-023', 'Identification_ID_Issue_Authority — TODO: no confirmed HUB field',
       'NOT_FOUND', COUNT(*), TOT23.RESULT_TOTAL, CAST(NULL AS VARCHAR2(200))
  FROM NCIS_Customers
  CROSS JOIN (SELECT COUNT(*) AS RESULT_TOTAL FROM NCIS_Customers) TOT23 WHERE Identification_ID_Issue_Authority IS NOT NULL
 GROUP BY TOT23.RESULT_TOTAL

UNION ALL
SELECT 'CM-024', 'Identification_ID_Issue_Country — TODO: no confirmed HUB field (see A5)',
       'NOT_FOUND', COUNT(*), TOT24.RESULT_TOTAL, CAST(NULL AS VARCHAR2(200))
  FROM NCIS_Customers
  CROSS JOIN (SELECT COUNT(*) AS RESULT_TOTAL FROM NCIS_Customers) TOT24 WHERE Identification_ID_Issue_Country IS NOT NULL
 GROUP BY TOT24.RESULT_TOTAL

UNION ALL
SELECT 'CM-025', 'Tax_ID_Office — TODO: no confirmed HUB field',
       'NOT_FOUND', COUNT(*), TOT25.RESULT_TOTAL, CAST(NULL AS VARCHAR2(200))
  FROM NCIS_Customers
  CROSS JOIN (SELECT COUNT(*) AS RESULT_TOTAL FROM NCIS_Customers) TOT25 WHERE Tax_ID_Office IS NOT NULL
 GROUP BY TOT25.RESULT_TOTAL

UNION ALL
SELECT 'CM-026', 'Mobile_Telephone — TODO: no confirmed HUB field in this DD subset',
       'NOT_FOUND', COUNT(*), TOT26.RESULT_TOTAL, CAST(NULL AS VARCHAR2(200))
  FROM NCIS_Customers
  CROSS JOIN (SELECT COUNT(*) AS RESULT_TOTAL FROM NCIS_Customers) TOT26 WHERE Mobile_Telephone IS NOT NULL
 GROUP BY TOT26.RESULT_TOTAL

UNION ALL
SELECT 'CM-027', 'email — TODO: no confirmed HUB field in this DD subset',
       'NOT_FOUND', COUNT(*), TOT27.RESULT_TOTAL, CAST(NULL AS VARCHAR2(200))
  FROM NCIS_Customers
  CROSS JOIN (SELECT COUNT(*) AS RESULT_TOTAL FROM NCIS_Customers) TOT27 WHERE email IS NOT NULL
 GROUP BY TOT27.RESULT_TOTAL

UNION ALL
SELECT 'CM-028', 'Citizenship — TODO: no confirmed distinct HUB field (possible overlap with Nationality)',
       'NOT_FOUND', COUNT(*), TOT28.RESULT_TOTAL, CAST(NULL AS VARCHAR2(200))
  FROM NCIS_Customers
  CROSS JOIN (SELECT COUNT(*) AS RESULT_TOTAL FROM NCIS_Customers) TOT28 WHERE Citizenship IS NOT NULL
 GROUP BY TOT28.RESULT_TOTAL

UNION ALL
SELECT 'CM-029', 'Financial_Sector — TODO: candidate SSCUSTP.ZGMKS1/2/3, slot not confirmed',
       'NOT_FOUND', COUNT(*), TOT29.RESULT_TOTAL, CAST(NULL AS VARCHAR2(200))
  FROM NCIS_Customers
  CROSS JOIN (SELECT COUNT(*) AS RESULT_TOTAL FROM NCIS_Customers) TOT29 WHERE Financial_Sector IS NOT NULL
 GROUP BY TOT29.RESULT_TOTAL

UNION ALL
SELECT 'CM-030', 'Professional_Status — TODO: no confirmed HUB field',
       'NOT_FOUND', COUNT(*), TOT30.RESULT_TOTAL, CAST(NULL AS VARCHAR2(200))
  FROM NCIS_Customers
  CROSS JOIN (SELECT COUNT(*) AS RESULT_TOTAL FROM NCIS_Customers) TOT30 WHERE Professional_Status IS NOT NULL
 GROUP BY TOT30.RESULT_TOTAL

UNION ALL
SELECT 'CM-031', 'Insurance_Clearance_Expiration_Date — TODO: likely no HUB source (PROFITS-only enrichment)',
       'NOT_FOUND', COUNT(*), TOT31.RESULT_TOTAL, CAST(NULL AS VARCHAR2(200))
  FROM NCIS_Customers
  CROSS JOIN (SELECT COUNT(*) AS RESULT_TOTAL FROM NCIS_Customers) TOT31 WHERE Insurance_Clearance_Expiration_Date IS NOT NULL
 GROUP BY TOT31.RESULT_TOTAL

UNION ALL
SELECT 'CM-032', 'Corp_Registry_Number_Issue_Country — TODO: candidate SSNICIP.XUCTHQ, not confirmed',
       'NOT_FOUND', COUNT(*), TOT32.RESULT_TOTAL, CAST(NULL AS VARCHAR2(200))
  FROM NCIS_Customers
  CROSS JOIN (SELECT COUNT(*) AS RESULT_TOTAL FROM NCIS_Customers) TOT32 WHERE Corporation_Registry_Number_Issue_Country IS NOT NULL
 GROUP BY TOT32.RESULT_TOTAL

UNION ALL
SELECT 'CM-033', 'Risk_Classification — TODO: likely SSCDDMP.CMRSKC, outside SSCUSTP/SSINCIP join scope',
       'NOT_FOUND', COUNT(*), TOT33.RESULT_TOTAL, CAST(NULL AS VARCHAR2(200))
  FROM NCIS_Customers
  CROSS JOIN (SELECT COUNT(*) AS RESULT_TOTAL FROM NCIS_Customers) TOT33 WHERE Risk_Classification IS NOT NULL
 GROUP BY TOT33.RESULT_TOTAL

UNION ALL
SELECT 'CM-034', 'Special_Agreements — TODO: no confirmed HUB field',
       'NOT_FOUND', COUNT(*), TOT34.RESULT_TOTAL, CAST(NULL AS VARCHAR2(200))
  FROM NCIS_Customers
  CROSS JOIN (SELECT COUNT(*) AS RESULT_TOTAL FROM NCIS_Customers) TOT34 WHERE Special_Agreements IS NOT NULL
 GROUP BY TOT34.RESULT_TOTAL

UNION ALL
SELECT 'CM-035', 'Tax_ID_Issue_Country — TODO: no confirmed HUB field',
       'NOT_FOUND', COUNT(*), TOT35.RESULT_TOTAL, CAST(NULL AS VARCHAR2(200))
  FROM NCIS_Customers
  CROSS JOIN (SELECT COUNT(*) AS RESULT_TOTAL FROM NCIS_Customers) TOT35 WHERE Tax_ID_Issue_Country IS NOT NULL
 GROUP BY TOT35.RESULT_TOTAL

UNION ALL
SELECT 'CM-036', 'Customer_Creation_Date — TODO: candidate SSCUSTP.ZGDTAD, not confirmed',
       'NOT_FOUND', COUNT(*), TOT36.RESULT_TOTAL, CAST(NULL AS VARCHAR2(200))
  FROM NCIS_Customers
  CROSS JOIN (SELECT COUNT(*) AS RESULT_TOTAL FROM NCIS_Customers) TOT36 WHERE Customer_Creation_Date IS NOT NULL
 GROUP BY TOT36.RESULT_TOTAL

UNION ALL
SELECT 'CM-037', 'AMLRICAT — TODO: no confirmed HUB field (possibly related to SSCDDMP.CMRSKC)',
       'NOT_FOUND', COUNT(*), TOT37.RESULT_TOTAL, CAST(NULL AS VARCHAR2(200))
  FROM NCIS_Customers
  CROSS JOIN (SELECT COUNT(*) AS RESULT_TOTAL FROM NCIS_Customers) TOT37 WHERE AMLRICAT IS NOT NULL
 GROUP BY TOT37.RESULT_TOTAL

UNION ALL
SELECT 'CM-038', 'CUSTOMER_ENTRY_COMMENTS — TODO: likely no HUB source (PROFITS-only free text)',
       'NOT_FOUND', COUNT(*), TOT38.RESULT_TOTAL, CAST(NULL AS VARCHAR2(200))
  FROM NCIS_Customers
  CROSS JOIN (SELECT COUNT(*) AS RESULT_TOTAL FROM NCIS_Customers) TOT38 WHERE CUSTOMER_ENTRY_COMMENTS IS NOT NULL
 GROUP BY TOT38.RESULT_TOTAL
) C
ORDER BY C.CATEGORY, C.CHECK_ID;
