SELECT 'CM-105', 'Telephone: no matching SSADDRP.ZBTENO/ZBTEN2 found among customer''s HUB addresses (PROBABLE — see A3)',
       'PROBABLE',
       COUNT(CASE WHEN p.Telephone IS NOT NULL AND h.CUSTOMER_CODE IS NULL THEN 1 END) AS RESULT_NUM,
       COUNT(CASE WHEN p.Telephone IS NOT NULL THEN 1 END) AS RESULT_TOTAL,
       CAST(NULL AS VARCHAR2(200))
  FROM NCIS_Customer_addresses p
  JOIN MG_CUSTOMER_INTER mci ON mci.PRFT_CUST_ID = p.Customer_Code
  LEFT JOIN (SELECT DISTINCT TRIM(sc.CUSTOMER_CODE) AS CUSTOMER_CODE, TRIM(s.ZBTENO) AS PHONE
               FROM HUB_MT_SSCUSTP sc
               JOIN HUB_MT_SSADDRP s ON s.ZBDCB = sc.ZGDCB AND s.ZBDCS = sc.ZGDCS
              WHERE s.ZBTENO IS NOT NULL
             UNION
             SELECT DISTINCT TRIM(sc.CUSTOMER_CODE) AS CUSTOMER_CODE, TRIM(s.ZBTEN2) AS PHONE
               FROM HUB_MT_SSCUSTP sc
               JOIN HUB_MT_SSADDRP s ON s.ZBDCB = sc.ZGDCB AND s.ZBDCS = sc.ZGDCS
              WHERE s.ZBTEN2 IS NOT NULL) h
    ON h.CUSTOMER_CODE = TRIM(mci.CUSTOMER_CODE) AND h.PHONE = TRIM(p.Telephone);