SELECT
       'Deposits' AS CHECK_TYPE,
       C.CHECK_ID, C.CHECK_NAME, C.CATEGORY,
       C.RESULT_NUM, C.RESULT_TOTAL, C.RESULT_TXT,
       CASE WHEN C.CATEGORY = 'NOT_FOUND' THEN 'INFO'
            WHEN C.RESULT_NUM = 0            THEN 'PASS'
            ELSE 'REVIEW' END AS STATUS
  FROM (


SELECT 'CM-201' AS CHECK_ID,
       'Deposit accounts with 0 or 2+ matching HUB DDACMSP/TDACMSP rows (expect exactly 1)' AS CHECK_NAME,
       'CONFIRMED' AS CATEGORY,
       COUNT(CASE WHEN  (NVL(dagg.DDA_CNT,0) + NVL(tagg.TD_CNT,0)) <> 1 THEN 1 END) AS RESULT_NUM,
       COUNT(*) AS RESULT_TOTAL,
       CAST(NULL AS VARCHAR2(200)) AS RESULT_TXT
  FROM NCIS_Deposits n
  JOIN MG_CUST_DPAC_INTER mg ON mg.ACCOUNT_NO = n.Account_Number
  LEFT JOIN (SELECT TRIM(ACCOUNT_NO) AS ACCOUNT_NO, COUNT(*) AS DDA_CNT
               FROM HUB_MT_DDACMSP
              GROUP BY TRIM(ACCOUNT_NO)) dagg
    ON dagg.ACCOUNT_NO = TRIM(mg.ACCOUNT_NO)
  LEFT JOIN (SELECT TRIM(ACCOUNT_NO) AS ACCOUNT_NO, COUNT(*) AS TD_CNT
               FROM HUB_MT_TDACMSP
              GROUP BY TRIM(ACCOUNT_NO)) tagg
    ON tagg.ACCOUNT_NO = TRIM(mg.ACCOUNT_NO)

UNION ALL
SELECT 'CM-202', 'Open_Date mismatch vs DDACMSP.DFDTAO / TDACMSP.TDDTAO',
       'CONFIRMED', COUNT(CASE WHEN  NVL(TO_CHAR(n.Open_Date,'YYYYMMDD'),'X') <> NVL(TRIM(COALESCE(d.DFDTAO, t.TDDTAO)),'X') THEN 1 END),
       COUNT(*) AS RESULT_TOTAL,
       CAST(NULL AS VARCHAR2(200))
  FROM NCIS_Deposits n
  JOIN MG_CUST_DPAC_INTER mg ON mg.ACCOUNT_NO = n.Account_Number
  LEFT JOIN HUB_MT_DDACMSP d ON TRIM(d.ACCOUNT_NO) = TRIM(mg.ACCOUNT_NO)
  LEFT JOIN HUB_MT_TDACMSP t ON TRIM(t.ACCOUNT_NO) = TRIM(mg.ACCOUNT_NO)

UNION ALL
SELECT 'CM-203', 'Account_Status mismatch vs DDACMSP.DFSTUS / TDACMSP.TDSTUS',
       'CONFIRMED', COUNT(CASE WHEN  NVL(TRIM(n.Account_Status),'X') <> NVL(TRIM(COALESCE(d.DFSTUS, t.TDSTUS)),'X') THEN 1 END),
       COUNT(*) AS RESULT_TOTAL,
       CAST(NULL AS VARCHAR2(200))
  FROM NCIS_Deposits n
  JOIN MG_CUST_DPAC_INTER mg ON mg.ACCOUNT_NO = n.Account_Number
  LEFT JOIN HUB_MT_DDACMSP d ON TRIM(d.ACCOUNT_NO) = TRIM(mg.ACCOUNT_NO)
  LEFT JOIN HUB_MT_TDACMSP t ON TRIM(t.ACCOUNT_NO) = TRIM(mg.ACCOUNT_NO)

UNION ALL
SELECT 'CM-204', 'TD_Expiration_DATE mismatch vs TDACMSP.TDDUDT',
       'CONFIRMED', COUNT(CASE WHEN  n.TD_Expiration_DATE IS NOT NULL
   AND NVL(TO_CHAR(n.TD_Expiration_DATE,'YYYYMMDD'),'X') <> NVL(TRIM(t.TDDUDT),'X') THEN 1 END),
       COUNT(CASE WHEN n.TD_Expiration_DATE IS NOT NULL THEN 1 END) AS RESULT_TOTAL,
       CAST(NULL AS VARCHAR2(200))
  FROM NCIS_Deposits n
  JOIN MG_CUST_DPAC_INTER mg ON mg.ACCOUNT_NO = n.Account_Number
  JOIN HUB_MT_TDACMSP t ON TRIM(t.ACCOUNT_NO) = TRIM(mg.ACCOUNT_NO)

UNION ALL
SELECT 'CM-205', 'TD_Start_Date mismatch vs TDACMSP.TDSTDT',
       'CONFIRMED', COUNT(CASE WHEN  n.TD_Start_Date IS NOT NULL
   AND NVL(TO_CHAR(n.TD_Start_Date,'YYYYMMDD'),'X') <> NVL(TRIM(t.TDSTDT),'X') THEN 1 END),
       COUNT(CASE WHEN n.TD_Start_Date IS NOT NULL THEN 1 END) AS RESULT_TOTAL,
       CAST(NULL AS VARCHAR2(200))
  FROM NCIS_Deposits n
  JOIN MG_CUST_DPAC_INTER mg ON mg.ACCOUNT_NO = n.Account_Number
  JOIN HUB_MT_TDACMSP t ON TRIM(t.ACCOUNT_NO) = TRIM(mg.ACCOUNT_NO)

UNION ALL
SELECT 'CM-206', 'Account_Type mismatch vs DDACMSP.DFAPTY / TDACMSP.TDAPTY (PROBABLE)',
       'PROBABLE', COUNT(CASE WHEN  NVL(TRIM(TO_CHAR(n.Account_Type)),'X') <> NVL(TRIM(COALESCE(d.DFAPTY, t.TDAPTY)),'X') THEN 1 END),
       COUNT(*) AS RESULT_TOTAL,
       CAST(NULL AS VARCHAR2(200))
  FROM NCIS_Deposits n
  JOIN MG_CUST_DPAC_INTER mg ON mg.ACCOUNT_NO = n.Account_Number
  LEFT JOIN HUB_MT_DDACMSP d ON TRIM(d.ACCOUNT_NO) = TRIM(mg.ACCOUNT_NO)
  LEFT JOIN HUB_MT_TDACMSP t ON TRIM(t.ACCOUNT_NO) = TRIM(mg.ACCOUNT_NO)

UNION ALL
SELECT 'CM-207', 'Account_Currency: PROFITS description vs HUB currency code — needs crosswalk (PROBABLE)',
       'PROBABLE', COUNT(CASE WHEN  NVL(TRIM(n.Account_Currency),'X') <> NVL(TRIM(COALESCE(d.DFCYCD, t.TDCYCD)),'X') THEN 1 END),
       COUNT(*) AS RESULT_TOTAL,
       CAST(NULL AS VARCHAR2(200))
  FROM NCIS_Deposits n
  JOIN MG_CUST_DPAC_INTER mg ON mg.ACCOUNT_NO = n.Account_Number
  LEFT JOIN HUB_MT_DDACMSP d ON TRIM(d.ACCOUNT_NO) = TRIM(mg.ACCOUNT_NO)
  LEFT JOIN HUB_MT_TDACMSP t ON TRIM(t.ACCOUNT_NO) = TRIM(mg.ACCOUNT_NO)

UNION ALL
SELECT 'CM-208', 'Extrait_Issue_Frequency mismatch vs DDSTMTP.DHSMCY (PROBABLE — DDA-side only)',
       'PROBABLE', COUNT(CASE WHEN  NVL(TRIM(n.Extrait_Issue_Frequency),'X') <> NVL(TRIM(dh.DHSMCY),'X') THEN 1 END),
       COUNT(*) AS RESULT_TOTAL,
       CAST(NULL AS VARCHAR2(200))
  FROM NCIS_Deposits n
  JOIN MG_CUST_DPAC_INTER mg ON mg.ACCOUNT_NO = n.Account_Number
  JOIN HUB_MT_DDSTMTP dh ON TRIM(dh.ACCOUNT_NO) = TRIM(mg.ACCOUNT_NO)

UNION ALL
SELECT 'CM-209', 'BOOK_BALANCE mismatch vs DDACMSP.DFRLBL / TDACMSP.TDRLBL "Ledger Balance" (PROBABLE)',
       'PROBABLE', COUNT(CASE WHEN  NVL(TO_NUMBER(n.BOOK_BALANCE),-1) <> NVL(TO_NUMBER(COALESCE(d.DFRLBL, t.TDRLBL)),-1) THEN 1 END),
       COUNT(*) AS RESULT_TOTAL,
       CAST(NULL AS VARCHAR2(200))
  FROM NCIS_Deposits n
  JOIN MG_CUST_DPAC_INTER mg ON mg.ACCOUNT_NO = n.Account_Number
  LEFT JOIN HUB_MT_DDACMSP d ON TRIM(d.ACCOUNT_NO) = TRIM(mg.ACCOUNT_NO)
  LEFT JOIN HUB_MT_TDACMSP t ON TRIM(t.ACCOUNT_NO) = TRIM(mg.ACCOUNT_NO)

UNION ALL
SELECT 'CM-210', 'BLOCKED_BALANCE mismatch vs DDACMSP.DFTTHD / TDACMSP.TDTTHD "Total Holds" (PROBABLE)',
       'PROBABLE', COUNT(CASE WHEN  NVL(TO_NUMBER(n.BLOCKED_BALANCE),-1) <> NVL(TO_NUMBER(COALESCE(d.DFTTHD, t.TDTTHD)),-1) THEN 1 END),
       COUNT(*) AS RESULT_TOTAL,
       CAST(NULL AS VARCHAR2(200))
  FROM NCIS_Deposits n
  JOIN MG_CUST_DPAC_INTER mg ON mg.ACCOUNT_NO = n.Account_Number
  LEFT JOIN HUB_MT_DDACMSP d ON TRIM(d.ACCOUNT_NO) = TRIM(mg.ACCOUNT_NO)
  LEFT JOIN HUB_MT_TDACMSP t ON TRIM(t.ACCOUNT_NO) = TRIM(mg.ACCOUNT_NO)

UNION ALL
SELECT 'CM-211', 'TD_MATURITY_INSTRUCTIONS mismatch vs TDACMSP.TDMTIN — code crosswalk unconfirmed (PROBABLE)',
       'PROBABLE', COUNT(CASE WHEN  n.TD_MATURITY_INSTRUCTIONS IS NOT NULL
   AND NVL(TRIM(n.TD_MATURITY_INSTRUCTIONS),'X') <> NVL(TRIM(t.TDMTIN),'X') THEN 1 END),
       COUNT(CASE WHEN n.TD_MATURITY_INSTRUCTIONS IS NOT NULL THEN 1 END) AS RESULT_TOTAL,
       CAST(NULL AS VARCHAR2(200))
  FROM NCIS_Deposits n
  JOIN MG_CUST_DPAC_INTER mg ON mg.ACCOUNT_NO = n.Account_Number
  JOIN HUB_MT_TDACMSP t ON TRIM(t.ACCOUNT_NO) = TRIM(mg.ACCOUNT_NO)

UNION ALL
SELECT 'CM-212', 'TD_Interest_Rate mismatch vs TDACMSP.TDCNTR "Contract Rate" (PROBABLE)',
       'PROBABLE', COUNT(CASE WHEN  n.TD_Interest_Rate IS NOT NULL
   AND NVL(TO_NUMBER(n.TD_Interest_Rate),-1) <> NVL(TO_NUMBER(t.TDCNTR),-1) THEN 1 END),
       COUNT(CASE WHEN n.TD_Interest_Rate IS NOT NULL THEN 1 END) AS RESULT_TOTAL,
       CAST(NULL AS VARCHAR2(200))
  FROM NCIS_Deposits n
  JOIN MG_CUST_DPAC_INTER mg ON mg.ACCOUNT_NO = n.Account_Number
  JOIN HUB_MT_TDACMSP t ON TRIM(t.ACCOUNT_NO) = TRIM(mg.ACCOUNT_NO)

UNION ALL
SELECT 'CM-213', 'CREDIT_INTEREST_ACCRUALS mismatch vs DDCRINP.DGCRIA / TDACMSP.TDINAR (PROBABLE, dual)',
       'PROBABLE', COUNT(CASE WHEN  NVL(TO_NUMBER(n.CREDIT_INTEREST_ACCRUALS),-1) <> NVL(TO_NUMBER(COALESCE(g.DGCRIA, t.TDINAR)),-1) THEN 1 END),
       COUNT(*) AS RESULT_TOTAL,
       CAST(NULL AS VARCHAR2(200))
  FROM NCIS_Deposits n
  JOIN MG_CUST_DPAC_INTER mg ON mg.ACCOUNT_NO = n.Account_Number
  LEFT JOIN HUB_MT_DDCRINP g ON TRIM(g.ACCOUNT_NO) = TRIM(mg.ACCOUNT_NO)
  LEFT JOIN HUB_MT_TDACMSP t ON TRIM(t.ACCOUNT_NO) = TRIM(mg.ACCOUNT_NO)

UNION ALL
SELECT 'CM-214', 'Credit_Interest_Spread mismatch vs DDCRINP.DGCIRS / TDACMSP.TDCRSP (PROBABLE, dual)',
       'PROBABLE', COUNT(CASE WHEN  NVL(TO_NUMBER(n.Credit_Interest_Spread),-1) <> NVL(TO_NUMBER(COALESCE(g.DGCIRS, t.TDCRSP)),-1) THEN 1 END),
       COUNT(*) AS RESULT_TOTAL,
       CAST(NULL AS VARCHAR2(200))
  FROM NCIS_Deposits n
  JOIN MG_CUST_DPAC_INTER mg ON mg.ACCOUNT_NO = n.Account_Number
  LEFT JOIN HUB_MT_DDCRINP g ON TRIM(g.ACCOUNT_NO) = TRIM(mg.ACCOUNT_NO)
  LEFT JOIN HUB_MT_TDACMSP t ON TRIM(t.ACCOUNT_NO) = TRIM(mg.ACCOUNT_NO)

UNION ALL
SELECT 'CM-215', 'Credit_Interest_Code mismatch vs DDCRINP.DGCIRT / TDACMSP.TDCRTY (PROBABLE, dual)',
       'PROBABLE', COUNT(CASE WHEN  NVL(TRIM(TO_CHAR(n.Credit_Interest_Code)),'X') <> NVL(TRIM(COALESCE(TO_CHAR(g.DGCIRT), t.TDCRTY)),'X') THEN 1 END),
       COUNT(*) AS RESULT_TOTAL,
       CAST(NULL AS VARCHAR2(200))
  FROM NCIS_Deposits n
  JOIN MG_CUST_DPAC_INTER mg ON mg.ACCOUNT_NO = n.Account_Number
  LEFT JOIN HUB_MT_DDCRINP g ON TRIM(g.ACCOUNT_NO) = TRIM(mg.ACCOUNT_NO)
  LEFT JOIN HUB_MT_TDACMSP t ON TRIM(t.ACCOUNT_NO) = TRIM(mg.ACCOUNT_NO)

UNION ALL
SELECT 'CM-216', 'Check_Digit — TODO: possibly embedded in DFACS/TDACS trailing digit (see A2/customer precedent)',
       'NOT_FOUND', COUNT(CASE WHEN  Check_Digit IS NOT NULL THEN 1 END), COUNT(*), CAST(NULL AS VARCHAR2(200)) FROM NCIS_Deposits

UNION ALL
SELECT 'CM-217', 'Unit_Code — TODO: possible overlap with DFACB/TDACB (Account Branch), not confirmed',
       'NOT_FOUND', COUNT(CASE WHEN  Unit_Code IS NOT NULL THEN 1 END), COUNT(*), CAST(NULL AS VARCHAR2(200)) FROM NCIS_Deposits

UNION ALL
SELECT 'CM-218', 'Number_Of_Beneficiaries — TODO: no confirmed HUB field (PROFITS BENEFICIARY count, derived)',
       'NOT_FOUND', COUNT(CASE WHEN  Number_Of_Beneficiaries IS NOT NULL THEN 1 END), COUNT(*), CAST(NULL AS VARCHAR2(200)) FROM NCIS_Deposits

UNION ALL
SELECT 'CM-219', 'Agreement_Code — TODO: PROFITS-internal self-join construct (AGR_UNIT/YEAR/SN), no HUB field found',
       'NOT_FOUND', COUNT(CASE WHEN  Agreement_Code IS NOT NULL THEN 1 END), COUNT(*), CAST(NULL AS VARCHAR2(200)) FROM NCIS_Deposits

UNION ALL
SELECT 'CM-220', 'Overdraft_Limit_Start_Date — TODO: no confirmed HUB field (AFSIMSP.FNODLI is an indicator only, see A5)',
       'NOT_FOUND', COUNT(CASE WHEN  Overdraft_Limit_Start_Date IS NOT NULL THEN 1 END), COUNT(*), CAST(NULL AS VARCHAR2(200)) FROM NCIS_Deposits

UNION ALL
SELECT 'CM-221', 'Overdraft_Limit_Amount — TODO: no confirmed HUB field (AFSIMSP.FNODLI is an indicator only, see A5)',
       'NOT_FOUND', COUNT(CASE WHEN  Overdraft_Limit_Amount IS NOT NULL THEN 1 END), COUNT(*), CAST(NULL AS VARCHAR2(200)) FROM NCIS_Deposits

UNION ALL
SELECT 'CM-222', 'Service_Account_1 — TODO: PROFITS-derived linked-account chain, no HUB field found',
       'NOT_FOUND', COUNT(CASE WHEN  Service_Account_1 IS NOT NULL THEN 1 END), COUNT(*), CAST(NULL AS VARCHAR2(200)) FROM NCIS_Deposits

UNION ALL
SELECT 'CM-223', 'Service_Account_2 — TODO: PROFITS-derived linked-account chain, no HUB field found',
       'NOT_FOUND', COUNT(CASE WHEN  Service_Account_2 IS NOT NULL THEN 1 END), COUNT(*), CAST(NULL AS VARCHAR2(200)) FROM NCIS_Deposits

UNION ALL
SELECT 'CM-224', 'UNCLEAR_BALANCE — TODO: no confirmed HUB field in DDACMSP/TDACMSP',
       'NOT_FOUND', COUNT(CASE WHEN  UNCLEAR_BALANCE IS NOT NULL THEN 1 END), COUNT(*), CAST(NULL AS VARCHAR2(200)) FROM NCIS_Deposits

UNION ALL
SELECT 'CM-225', 'TD_Renewal_Flag — TODO: candidate TDACMSP.TDRNCT is a COUNT not a FLAG, type mismatch unresolved',
       'NOT_FOUND', COUNT(CASE WHEN  TD_Renewal_Flag IS NOT NULL THEN 1 END), COUNT(*), CAST(NULL AS VARCHAR2(200)) FROM NCIS_Deposits

UNION ALL
SELECT 'CM-226', 'AVAILABLE_BALANCE — TODO: not a stored field in DDACMSP/TDACMSP (likely Ledger − Holds, formula TBD)',
       'NOT_FOUND', COUNT(CASE WHEN  AVAILABLE_BALANCE IS NOT NULL THEN 1 END), COUNT(*), CAST(NULL AS VARCHAR2(200)) FROM NCIS_Deposits

UNION ALL
SELECT 'CM-227', 'Customer_Category — TODO: two unconfirmed candidates, DFGHCL/TDGHCL vs DFCBCL/TDCBCL',
       'NOT_FOUND', COUNT(CASE WHEN  Customer_Category IS NOT NULL THEN 1 END), COUNT(*), CAST(NULL AS VARCHAR2(200)) FROM NCIS_Deposits

UNION ALL
SELECT 'CM-228', 'Activity_Sector — TODO: candidate DFMKS1/2/3 or TDMKS1/2/3 "Market Sector", slot not confirmed',
       'NOT_FOUND', COUNT(CASE WHEN  Activity_Sector IS NOT NULL THEN 1 END), COUNT(*), CAST(NULL AS VARCHAR2(200)) FROM NCIS_Deposits

UNION ALL
SELECT 'CM-229', 'DEBIT_INTEREST_ACCRUALS — TODO: no DDA-side debit-interest table found in DD scan',
       'NOT_FOUND', COUNT(CASE WHEN  DEBIT_INTEREST_ACCRUALS IS NOT NULL THEN 1 END), COUNT(*), CAST(NULL AS VARCHAR2(200)) FROM NCIS_Deposits

UNION ALL
SELECT 'CM-230', 'Reason — TODO: no confirmed HUB field',
       'NOT_FOUND', COUNT(CASE WHEN  Reason IS NOT NULL THEN 1 END), COUNT(*), CAST(NULL AS VARCHAR2(200)) FROM NCIS_Deposits

UNION ALL
SELECT 'CM-231', 'OVD_Debit_interest_Spread — TODO: no confirmed HUB field (no DDA debit-interest table found)',
       'NOT_FOUND', COUNT(CASE WHEN  OVD_Debit_interest_Spread IS NOT NULL THEN 1 END), COUNT(*), CAST(NULL AS VARCHAR2(200)) FROM NCIS_Deposits

UNION ALL
SELECT 'CM-232', 'OVD_Interest_Transfer_Account — INFO only: hardcoded literal ''N/A'' in source query, not a real field',
       'NOT_FOUND', COUNT(CASE WHEN  OVD_Interest_Transfer_Account IS NOT NULL THEN 1 END), COUNT(*), CAST(NULL AS VARCHAR2(200)) FROM NCIS_Deposits

UNION ALL
SELECT 'CM-233', 'OVD_Days_Base — TODO: currency-level attribute (CRNCY.DAYSBASE), no account-level HUB field found',
       'NOT_FOUND', COUNT(CASE WHEN  OVD_Days_Base IS NOT NULL THEN 1 END), COUNT(*), CAST(NULL AS VARCHAR2(200)) FROM NCIS_Deposits

UNION ALL
SELECT 'CM-234', 'OVD_Interest_application_cycle — TODO: no DDA debit-interest table found',
       'NOT_FOUND', COUNT(CASE WHEN  OVD_Interest_application_cycle IS NOT NULL THEN 1 END), COUNT(*), CAST(NULL AS VARCHAR2(200)) FROM NCIS_Deposits

UNION ALL
SELECT 'CM-235', 'Next_Debit_interest_application_Date — TODO: no DDA debit-interest table found',
       'NOT_FOUND', COUNT(CASE WHEN  Next_Debit_interest_application_Date IS NOT NULL THEN 1 END), COUNT(*), CAST(NULL AS VARCHAR2(200)) FROM NCIS_Deposits

UNION ALL
SELECT 'CM-236', 'Days_Base — TODO: likely resides in INT_SCALE-equivalent interest table, not in this DD scan',
       'NOT_FOUND', COUNT(CASE WHEN  Days_Base IS NOT NULL THEN 1 END), COUNT(*), CAST(NULL AS VARCHAR2(200)) FROM NCIS_Deposits

UNION ALL
SELECT 'CM-237', 'Debit_Interest_Code — TODO: no DDA debit-interest table found, TD side has no distinct field',
       'NOT_FOUND', COUNT(CASE WHEN  Debit_Interest_Code IS NOT NULL THEN 1 END), COUNT(*), CAST(NULL AS VARCHAR2(200)) FROM NCIS_Deposits

UNION ALL
SELECT 'CM-238', 'Unauthorized_Interest_Accrued — TODO: tentative TDACMSP.TDOIAR ("Overdue interest") but semantics differ, not confirmed',
       'NOT_FOUND', COUNT(CASE WHEN  Unauthorized_Interest_Accrued IS NOT NULL THEN 1 END), COUNT(*), CAST(NULL AS VARCHAR2(200)) FROM NCIS_Deposits

UNION ALL
SELECT 'CM-239', 'DEPOSIT_TYPE — TODO: possible overlap/duplicate with Account_Type (DFAPTY/TDAPTY), needs NC clarification',
       'NOT_FOUND', COUNT(CASE WHEN  DEPOSIT_TYPE IS NOT NULL THEN 1 END), COUNT(*), CAST(NULL AS VARCHAR2(200)) FROM NCIS_Deposits
) C
ORDER BY C.CATEGORY, C.CHECK_ID;