SELECT
    CAST('ME04_ATM' AS NVARCHAR2(50))          AS DQ_TYPE,
    CAST(y.dq_category AS NVARCHAR2(100))      AS DQ_CATEGORY,
    CAST(y.check_name  AS NVARCHAR2(500))      AS CHECK_NAME,
    CAST(NULL AS NVARCHAR2(100))               AS TABLE_NAME,
    CAST(NULL AS NUMBER)                       AS FAILED_RECORDS,
    CAST(y.result_num AS NUMBER)               AS TOTAL_RECORDS,
    CAST(NULL AS NUMBER)                       AS FAILURE_PCT,
    CAST(y.check_id AS NVARCHAR2(20))          AS CHECK_ID,
    CAST(y.result_num AS NUMBER(20,2))         AS RESULT_NUM,
    CAST(y.result_txt AS NVARCHAR2(2000))      AS RESULT_TXT,
    CAST(y.expected AS NUMBER(20,2))           AS EXPECTED,
    CAST(
        CASE
            WHEN y.expected IS NOT NULL
              THEN CASE WHEN ABS(y.result_num - y.expected) * 100.0 / NULLIF(y.expected, 0) <= 0.1
                        THEN 'PASS' ELSE 'REVIEW' END
            WHEN y.result_txt IS NULL
              THEN CASE WHEN y.result_num = 0 THEN 'PASS' ELSE 'FAIL' END
            ELSE 'INFO'
        END AS NVARCHAR2(20)
    ) AS DQ_STATUS
FROM (
    SELECT 'CAT-ATM-01 VOLUME RECONCILIATION' AS dq_category, x.check_id, x.check_name, x.result_num, x.result_txt, x.expected
      FROM (
-- ATM-RC-001 | Row Count: Card Holder Extension File (AT@CAHEP)
SELECT 'ATM-RC-001' AS check_id, 'Row Count: Card Holder Extension File (AT@CAHEP)' AS check_name,
       COUNT(*) AS RESULT_NUM, CAST(NULL AS VARCHAR2(200)) AS RESULT_TXT, CAST(NULL AS NUMBER) AS EXPECTED
  FROM DATACUT3."ATM_MT_AT@CAHEP"
UNION ALL
-- ATM-RC-002 | Row Count: Chip Controls per BIN File (AT@CBNP)
SELECT 'ATM-RC-002', 'Row Count: Chip Controls per BIN File (AT@CBNP)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3."ATM_MT_AT@CBNP"
UNION ALL
-- ATM-RC-003 | Row Count: Chip Controls per Card File (AT@CCDP)
SELECT 'ATM-RC-003', 'Row Count: Chip Controls per Card File (AT@CCDP)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3."ATM_MT_AT@CCDP"
UNION ALL
-- ATM-RC-004 | Row Count: Chip Controls per Product File (AT@CPDP)
SELECT 'ATM-RC-004', 'Row Count: Chip Controls per Product File (AT@CPDP)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3."ATM_MT_AT@CPDP"
UNION ALL
-- ATM-RC-005 | Row Count: SEPA Charges Discount File (AT@SPCP)
SELECT 'ATM-RC-005', 'Row Count: SEPA Charges Discount File (AT@SPCP)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3."ATM_MT_AT@SPCP"
UNION ALL
-- ATM-RC-006 | Row Count: SEPA Transaction Charges File (AT@TRCP)
SELECT 'ATM-RC-006', 'Row Count: SEPA Transaction Charges File (AT@TRCP)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3."ATM_MT_AT@TRCP"
UNION ALL
-- ATM-RC-007 | Row Count: SEPA Transaction Types File (AT@TRTP)
SELECT 'ATM-RC-007', 'Row Count: SEPA Transaction Types File (AT@TRTP)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3."ATM_MT_AT@TRTP"
UNION ALL
-- ATM-RC-008 | Row Count: ATM Account Type Mapping (ATAACTP)
SELECT 'ATM-RC-008', 'Row Count: ATM Account Type Mapping (ATAACTP)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ATM_MT_ATAACTP
UNION ALL
-- ATM-RC-009 | Row Count: ATM/HUB Product Type Control (ATAPTYP)
SELECT 'ATM-RC-009', 'Row Count: ATM/HUB Product Type Control (ATAPTYP)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ATM_MT_ATAPTYP
UNION ALL
-- ATM-RC-010 | Row Count: Authorisation Log Journal (ATAULJP)
SELECT 'ATM-RC-010', 'Row Count: Authorisation Log Journal (ATAULJP)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ATM_MT_ATAULJP
UNION ALL
-- ATM-RC-011 | Row Count: Authorized Function Control (ATAUTCP)
SELECT 'ATM-RC-011', 'Row Count: Authorized Function Control (ATAUTCP)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ATM_MT_ATAUTCP
UNION ALL
-- ATM-RC-012 | Row Count: ATM Cardholder File (ATCAHFP)
SELECT 'ATM-RC-012', 'Row Count: ATM Cardholder File (ATCAHFP)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ATM_MT_ATCAHFP
UNION ALL
-- ATM-RC-013 | Row Count: ATM Card Fee File (ATCFEEP)
SELECT 'ATM-RC-013', 'Row Count: ATM Card Fee File (ATCFEEP)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ATM_MT_ATCFEEP
UNION ALL
-- ATM-RC-014 | Row Count: ATM Transaction Charge Control (ATCHRGP)
SELECT 'ATM-RC-014', 'Row Count: ATM Transaction Charge Control (ATCHRGP)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ATM_MT_ATCHRGP
UNION ALL
-- ATM-RC-015 | Row Count: ATMP Cycle Fund Control (ATCYCLP)
SELECT 'ATM-RC-015', 'Row Count: ATMP Cycle Fund Control (ATCYCLP)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ATM_MT_ATCYCLP
UNION ALL
-- ATM-RC-016 | Row Count: Function ID vs Program ID (ATFUNCP)
SELECT 'ATM-RC-016', 'Row Count: Function ID vs Program ID (ATFUNCP)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ATM_MT_ATFUNCP
UNION ALL
-- ATM-RC-017 | Row Count: Preferential Transaction Charge Control (ATPCHGP)
SELECT 'ATM-RC-017', 'Row Count: Preferential Transaction Charge Control (ATPCHGP)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ATM_MT_ATPCHGP
UNION ALL
-- ATM-RC-018 | Row Count: ATMP Product Type Control (ATPDCPP)
SELECT 'ATM-RC-018', 'Row Count: ATMP Product Type Control (ATPDCPP)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ATM_MT_ATPDCPP
UNION ALL
-- ATM-RC-019 | Row Count: ATMP Standing Data Control (ATSDCPP)
SELECT 'ATM-RC-019', 'Row Count: ATMP Standing Data Control (ATSDCPP)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ATM_MT_ATSDCPP
UNION ALL
-- ATM-RC-020 | Row Count: ATMP Standing Data File (ATSTDPP)
SELECT 'ATM-RC-020', 'Row Count: ATMP Standing Data File (ATSTDPP)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ATM_MT_ATSTDPP
UNION ALL
-- ATM-RC-021 | Row Count: Account Suffix File (ATSUFXP)
SELECT 'ATM-RC-021', 'Row Count: Account Suffix File (ATSUFXP)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ATM_MT_ATSUFXP
UNION ALL
-- ATM-RC-022 | Row Count: ATMP Transaction Log File (ATTNFFP)
SELECT 'ATM-RC-022', 'Row Count: ATMP Transaction Log File (ATTNFFP)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ATM_MT_ATTNFFP
UNION ALL
-- ATM-RC-023 | Row Count: ATMP Transaction Journal File (ATTNFJP)
SELECT 'ATM-RC-023', 'Row Count: ATMP Transaction Journal File (ATTNFJP)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ATM_MT_ATTNFJP
UNION ALL
-- ATM-RC-024 | Row Count: User Control File (ATUSRCP)
SELECT 'ATM-RC-024', 'Row Count: User Control File (ATUSRCP)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ATM_MT_ATUSRCP
UNION ALL
-- ATM-RC-025 | Row Count: ATMP User Information File (ATUSRIP)
SELECT 'ATM-RC-025', 'Row Count: ATMP User Information File (ATUSRIP)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ATM_MT_ATUSRIP
UNION ALL
-- ATM-RC-026 | Row Count: Visa Card Number Generation File (ATVNOCP)
SELECT 'ATM-RC-026', 'Row Count: Visa Card Number Generation File (ATVNOCP)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ATM_MT_ATVNOCP
UNION ALL
-- ATM-RC-027 | Row Count: Supplementary Card Details (MVATSUP)
SELECT 'ATM-RC-027', 'Row Count: Supplementary Card Details (MVATSUP)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ATM_MT_MVATSUP
UNION ALL
-- ATM-RC-028 | Row Count: Daily OD Limit File (MVCLMPP)
SELECT 'ATM-RC-028', 'Row Count: Daily OD Limit File (MVCLMPP)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ATM_MT_MVCLMPP
      ) x
    UNION ALL
    SELECT 'CAT-ATM-02 MANDATORY FIELDS - NULL/BLANK' AS dq_category, x.check_id, x.check_name, x.result_num, x.result_txt, x.expected
      FROM (
-- ATM-MF-001 | Missing Primary Account Number — Cardholder Master (ACPAN)
SELECT 'ATM-MF-001' AS check_id, 'Missing PAN: ATCAHFP (ACPAN)' AS check_name,
       COUNT(*) AS RESULT_NUM, CAST(NULL AS VARCHAR2(200)) AS RESULT_TXT, CAST(NULL AS NUMBER) AS EXPECTED
  FROM DATACUT3.ATM_MT_ATCAHFP
 WHERE ACPAN IS NULL
UNION ALL
-- ATM-MF-002 | Missing Country/Group Member — Cardholder Master (ACCTCD/ACGMAB)
SELECT 'ATM-MF-002', 'Missing Country/Group Member: ATCAHFP (ACCTCD/ACGMAB)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ATM_MT_ATCAHFP
 WHERE ACCTCD IS NULL OR TRIM(ACCTCD) = '' OR ACGMAB IS NULL OR TRIM(ACGMAB) = ''
UNION ALL
-- ATM-MF-003 | Missing Card Status — Cardholder Master (ACCDST)
SELECT 'ATM-MF-003', 'Missing Card Status: ATCAHFP (ACCDST)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ATM_MT_ATCAHFP
 WHERE ACCDST IS NULL OR TRIM(ACCDST) = ''
UNION ALL
-- ATM-MF-004 | Missing PAN — Cardholder Extension (A@PAN)
SELECT 'ATM-MF-004', 'Missing PAN: AT@CAHEP (A@PAN)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3."ATM_MT_AT@CAHEP"
 WHERE "A@PAN" IS NULL
UNION ALL
-- ATM-MF-005 | Missing ATMP Product Type — Product Control (BUPDTY)
SELECT 'ATM-MF-005', 'Missing ATMP Product Type Link: ATAPTYP (BUPDTY)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ATM_MT_ATAPTYP
 WHERE BUPDTY IS NULL OR TRIM(BUPDTY) = ''
UNION ALL
-- ATM-MF-006 | Missing ATM Product Type — Product Type Control (DFPDTY)
SELECT 'ATM-MF-006', 'Missing ATM Product Type: ATPDCPP (DFPDTY)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ATM_MT_ATPDCPP
 WHERE DFPDTY IS NULL OR TRIM(DFPDTY) = ''
UNION ALL
-- ATM-MF-007 | Missing Account/Product Type — Account Type Mapping (DGAPTY)
SELECT 'ATM-MF-007', 'Missing Account/Product Type: ATAACTP (DGAPTY)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ATM_MT_ATAACTP
 WHERE DGAPTY IS NULL OR TRIM(DGAPTY) = ''
UNION ALL
-- ATM-MF-008 | Missing Card Number — Transaction Log (EACDNO)
SELECT 'ATM-MF-008', 'Missing Card Number: ATTNFFP (EACDNO)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ATM_MT_ATTNFFP
 WHERE EACDNO IS NULL
UNION ALL
-- ATM-MF-009 | Missing Card Number — Transaction Journal (EACDNO)
SELECT 'ATM-MF-009', 'Missing Card Number: ATTNFJP (EACDNO)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ATM_MT_ATTNFJP
 WHERE EACDNO IS NULL
UNION ALL
-- ATM-MF-010 | Missing Card Number — Authorisation Log Journal (FACDNO)
SELECT 'ATM-MF-010', 'Missing Card Number: ATAULJP (FACDNO)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ATM_MT_ATAULJP
 WHERE FACDNO IS NULL
UNION ALL
-- ATM-MF-011 | Missing Card Number — Daily OD Limit File (TQCDNO)
SELECT 'ATM-MF-011', 'Missing Card Number: MVCLMPP (TQCDNO)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ATM_MT_MVCLMPP
 WHERE TQCDNO IS NULL
UNION ALL
-- ATM-MF-012 | Missing Country/Group Member — Account Suffix File (ASCTCD/ASGMAB)
SELECT 'ATM-MF-012', 'Missing Country/Group Member: ATSUFXP (ASCTCD/ASGMAB)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ATM_MT_ATSUFXP
 WHERE ASCTCD IS NULL OR TRIM(ASCTCD) = '' OR ASGMAB IS NULL OR TRIM(ASGMAB) = ''
      ) x
    UNION ALL
    SELECT 'CAT-ATM-03 DATE FIELD VALIDITY' AS dq_category, x.check_id, x.check_name, x.result_num, x.result_txt, x.expected
      FROM (
-- ATM-DT-001 | Invalid Date Last Transaction — Cardholder Master (ACDLTN)
SELECT 'ATM-DT-001' AS check_id, 'Invalid Date Last Transaction: ATCAHFP (ACDLTN)' AS check_name,
       COUNT(*) AS RESULT_NUM, CAST(NULL AS VARCHAR2(200)) AS RESULT_TXT, CAST(NULL AS NUMBER) AS EXPECTED
  FROM DATACUT3.ATM_MT_ATCAHFP
 WHERE ACDLTN IS NOT NULL
   AND TO_NUMBER(TO_CHAR(ACDLTN,'YYYYMMDD')) NOT BETWEEN 20000101 AND TO_NUMBER(TO_CHAR(DATE '2026-06-15','YYYYMMDD'))
UNION ALL
-- ATM-DT-002 | Invalid First Issue Date — Cardholder Master (ACFISS)
SELECT 'ATM-DT-002', 'Invalid First Issue Date: ATCAHFP (ACFISS)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ATM_MT_ATCAHFP
 WHERE ACFISS IS NOT NULL
   AND TO_NUMBER(TO_CHAR(ACFISS,'YYYYMMDD')) NOT BETWEEN 19900101 AND TO_NUMBER(TO_CHAR(DATE '2026-06-15','YYYYMMDD'))
UNION ALL
-- ATM-DT-003 | Current Issue Date Before First Issue Date — Cardholder Master (ACLISS < ACFISS)
SELECT 'ATM-DT-003', 'Current Issue Date Before First Issue Date: ATCAHFP (ACLISS < ACFISS)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ATM_MT_ATCAHFP
 WHERE ACLISS IS NOT NULL AND ACFISS IS NOT NULL AND ACLISS < ACFISS
UNION ALL
-- ATM-DT-004 | Invalid Date Last Maintenance — Cardholder Master (ACDLMT)
SELECT 'ATM-DT-004', 'Invalid Date Last Maintenance: ATCAHFP (ACDLMT)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ATM_MT_ATCAHFP
 WHERE ACDLMT IS NOT NULL
   AND TO_NUMBER(TO_CHAR(ACDLMT,'YYYYMMDD')) NOT BETWEEN 20000101 AND TO_NUMBER(TO_CHAR(DATE '2026-06-15','YYYYMMDD'))
UNION ALL
-- ATM-DT-005 | Invalid Transaction Date — Transaction Log (EAXDAT)
SELECT 'ATM-DT-005', 'Invalid Transaction Date: ATTNFFP (EAXDAT)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ATM_MT_ATTNFFP
 WHERE EAXDAT IS NULL
    OR TO_NUMBER(TO_CHAR(EAXDAT,'YYYYMMDD')) NOT BETWEEN 20000101 AND TO_NUMBER(TO_CHAR(DATE '2026-06-15','YYYYMMDD'))
UNION ALL
-- ATM-DT-006 | Business Date Before Transaction Date — Transaction Log (EAXBDT < EAXDAT)
SELECT 'ATM-DT-006', 'Business Date Before Transaction Date: ATTNFFP (EAXBDT < EAXDAT)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ATM_MT_ATTNFFP
 WHERE EAXBDT IS NOT NULL AND EAXDAT IS NOT NULL AND EAXBDT < EAXDAT
UNION ALL
-- ATM-DT-007 | Invalid Transaction Date — Transaction Journal (EAXDAT)
SELECT 'ATM-DT-007', 'Invalid Transaction Date: ATTNFJP (EAXDAT)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ATM_MT_ATTNFJP
 WHERE EAXDAT IS NULL
    OR TO_NUMBER(TO_CHAR(EAXDAT,'YYYYMMDD')) NOT BETWEEN 20000101 AND TO_NUMBER(TO_CHAR(DATE '2026-06-15','YYYYMMDD'))
UNION ALL
-- ATM-DT-008 | Invalid Capture Date — Authorisation Log Journal (FACPDT)
SELECT 'ATM-DT-008', 'Invalid Capture Date: ATAULJP (FACPDT)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ATM_MT_ATAULJP
 WHERE FACPDT IS NOT NULL
   AND TO_NUMBER(TO_CHAR(FACPDT,'YYYYMMDD')) NOT BETWEEN 20000101 AND TO_NUMBER(TO_CHAR(DATE '2026-06-15','YYYYMMDD'))
UNION ALL
-- ATM-DT-009 | Invalid Transaction Date — Authorisation Log Journal (FAXDAT)
SELECT 'ATM-DT-009', 'Invalid Transaction Date: ATAULJP (FAXDAT)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ATM_MT_ATAULJP
 WHERE FAXDAT IS NOT NULL
   AND TO_NUMBER(TO_CHAR(FAXDAT,'YYYYMMDD')) NOT BETWEEN 20000101 AND TO_NUMBER(TO_CHAR(DATE '2026-06-15','YYYYMMDD'))
UNION ALL
-- ATM-DT-010 | Invalid Transaction Date — Daily OD Limit File (TQXDAT)
SELECT 'ATM-DT-010', 'Invalid Transaction Date: MVCLMPP (TQXDAT)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ATM_MT_MVCLMPP
 WHERE TQXDAT IS NULL
    OR TO_NUMBER(TO_CHAR(TQXDAT,'YYYYMMDD')) NOT BETWEEN 20000101 AND TO_NUMBER(TO_CHAR(DATE '2026-06-15','YYYYMMDD'))
UNION ALL
-- ATM-DT-011 | Card Expiry (YYMM, Integer) Implausible — Cardholder Master (ACCDEX)
-- TODO: field is Integer(4) storing YYMM, not Date/Time — plausibility range only
SELECT 'ATM-DT-011', 'Implausible Card Expiry YYMM: ATCAHFP (ACCDEX) [TODO-format]',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ATM_MT_ATCAHFP
 WHERE ACCDEX IS NOT NULL AND (MOD(ACCDEX,100) NOT BETWEEN 1 AND 12 OR ACCDEX < 2000)
UNION ALL
-- ATM-DT-012 | Card Expiry (YYMM, Integer) Implausible — Transaction Log (EACDEX)
-- TODO: field is Integer(4) storing YYMM, not Date/Time — plausibility range only
SELECT 'ATM-DT-012', 'Implausible Card Expiry YYMM: ATTNFFP (EACDEX) [TODO-format]',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ATM_MT_ATTNFFP
 WHERE EACDEX IS NOT NULL AND (MOD(EACDEX,100) NOT BETWEEN 1 AND 12 OR EACDEX < 2000)
      ) x
    UNION ALL
    SELECT 'CAT-ATM-04 NUMERIC INTEGRITY & DOMAIN DISTRIBUTIONS' AS dq_category, x.check_id, x.check_name, x.result_num, x.result_txt, x.expected
      FROM (
-- ATM-NI-001 | Missing/NULL Transaction LCY Amount — Transaction Log (EALCY)
SELECT 'ATM-NI-001' AS check_id, 'Missing/NULL Transaction LCY Amount: ATTNFFP (EALCY)' AS check_name,
       COUNT(*) AS RESULT_NUM, CAST(NULL AS VARCHAR2(200)) AS RESULT_TXT, CAST(NULL AS NUMBER) AS EXPECTED
  FROM DATACUT3.ATM_MT_ATTNFFP
 WHERE EALCY IS NULL
UNION ALL
-- ATM-NI-002 | Missing/NULL Transaction Amount — Authorisation Log Journal (FAXAMT)
SELECT 'ATM-NI-002', 'Missing/NULL Transaction Amount: ATAULJP (FAXAMT)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ATM_MT_ATAULJP
 WHERE FAXAMT IS NULL
UNION ALL
-- ATM-NI-003 | Negative Annual Card Fee (Normal) — Card Fee File (DPAFEN)
SELECT 'ATM-NI-003', 'Negative Annual Card Fee (Normal): ATCFEEP (DPAFEN)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ATM_MT_ATCFEEP
 WHERE DPAFEN < 0
UNION ALL
-- ATM-NI-004 | Negative Global Transaction Charge for CWD — Charge Control (AHCHG1)
SELECT 'ATM-NI-004', 'Negative Global Transaction Charge (CWD): ATCHRGP (AHCHG1)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ATM_MT_ATCHRGP
 WHERE AHCHG1 < 0
UNION ALL
-- ATM-NI-005 | Negative Cash Withdrawal Cycle Limit — Cycle Fund Control (BTLCWD)
SELECT 'ATM-NI-005', 'Negative Cash Withdrawal Cycle Limit: ATCYCLP (BTLCWD)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ATM_MT_ATCYCLP
 WHERE BTLCWD < 0
UNION ALL
-- ATM-NI-006 | Zero/Negative Daily OD Limit Amount — Daily OD Limit File (TQLMAM)
SELECT 'ATM-NI-006', 'Zero/Negative Daily OD Limit Amount: MVCLMPP (TQLMAM)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ATM_MT_MVCLMPP
 WHERE TQLMAM IS NULL OR TQLMAM <= 0
UNION ALL
-- ATM-NI-007 | Card Status Distribution — Cardholder Master (ACCDST) [INFO]
SELECT 'ATM-NI-007', 'Card Status Distribution: ATCAHFP (ACCDST)',
       COUNT(*), NVL(ACCDST,'[NULL]'), CAST(NULL AS NUMBER)
  FROM DATACUT3.ATM_MT_ATCAHFP GROUP BY ACCDST
UNION ALL
-- ATM-NI-008 | Chip Status Distribution — Cardholder Master (ACCHST) [INFO]
SELECT 'ATM-NI-008', 'Chip Status Distribution: ATCAHFP (ACCHST)',
       COUNT(*), NVL(ACCHST,'[NULL]'), CAST(NULL AS NUMBER)
  FROM DATACUT3.ATM_MT_ATCAHFP GROUP BY ACCHST
UNION ALL
-- ATM-NI-009 | Pin Status Distribution — Cardholder Extension (A@PHST) [INFO]
SELECT 'ATM-NI-009', 'Pin Status Distribution: AT@CAHEP (A@PHST)',
       COUNT(*), NVL("A@PHST",'[NULL]'), CAST(NULL AS NUMBER)
  FROM DATACUT3."ATM_MT_AT@CAHEP" GROUP BY "A@PHST"
UNION ALL
-- ATM-NI-010 | ATM Product Type Distribution — Cardholder Master (ACPDTY) [INFO]
SELECT 'ATM-NI-010', 'ATM Product Type Distribution: ATCAHFP (ACPDTY)',
       COUNT(*), NVL(ACPDTY,'[NULL]'), CAST(NULL AS NUMBER)
  FROM DATACUT3.ATM_MT_ATCAHFP GROUP BY ACPDTY
UNION ALL
-- ATM-NI-011 | Transaction Type Distribution — Transaction Log (EATTYP) [INFO]
SELECT 'ATM-NI-011', 'Transaction Type Distribution: ATTNFFP (EATTYP)',
       COUNT(*), NVL(EATTYP,'[NULL]'), CAST(NULL AS NUMBER)
  FROM DATACUT3.ATM_MT_ATTNFFP GROUP BY EATTYP
UNION ALL
-- ATM-NI-012 | Activation Status Distribution — Cardholder Master (ACPATV) [INFO]
SELECT 'ATM-NI-012', 'Activation Status Distribution: ATCAHFP (ACPATV)',
       COUNT(*), NVL(ACPATV,'[NULL]'), CAST(NULL AS NUMBER)
  FROM DATACUT3.ATM_MT_ATCAHFP GROUP BY ACPATV
      ) x
    UNION ALL
    SELECT 'CAT-ATM-05 DUPLICATE DETECTION' AS dq_category, x.check_id, x.check_name, x.result_num, x.result_txt, x.expected
      FROM (
-- ATM-DU-001 | Duplicate Cardholder Master Records (ACCTCD+ACGMAB+ACPAN+ACCINO)
SELECT 'ATM-DU-001' AS check_id, 'Duplicate Cardholder Master: ATCAHFP (ACCTCD+ACGMAB+ACPAN+ACCINO)' AS check_name,
       COUNT(*) AS RESULT_NUM, CAST(NULL AS VARCHAR2(200)) AS RESULT_TXT, CAST(NULL AS NUMBER) AS EXPECTED
  FROM (
    SELECT ACCTCD, ACGMAB, ACPAN, ACCINO, COUNT(*) AS cnt
      FROM DATACUT3.ATM_MT_ATCAHFP
     GROUP BY ACCTCD, ACGMAB, ACPAN, ACCINO HAVING COUNT(*) > 1
  )
UNION ALL
-- ATM-DU-002 | Duplicate Cardholder Extension Records (A@CTCD+A@GMAB+A@PAN+A@CINO)
SELECT 'ATM-DU-002', 'Duplicate Cardholder Extension: AT@CAHEP (A@CTCD+A@GMAB+A@PAN+A@CINO)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM (
    SELECT "A@CTCD", "A@GMAB", "A@PAN", "A@CINO", COUNT(*) AS cnt
      FROM DATACUT3."ATM_MT_AT@CAHEP"
     GROUP BY "A@CTCD", "A@GMAB", "A@PAN", "A@CINO" HAVING COUNT(*) > 1
  )
UNION ALL
-- ATM-DU-003 | Duplicate Product Type Control Records (BUCTCD+BUGMAB+BUAPTY)
SELECT 'ATM-DU-003', 'Duplicate Product Type Control: ATAPTYP (BUCTCD+BUGMAB+BUAPTY)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM (
    SELECT BUCTCD, BUGMAB, BUAPTY, COUNT(*) AS cnt
      FROM DATACUT3.ATM_MT_ATAPTYP
     GROUP BY BUCTCD, BUGMAB, BUAPTY HAVING COUNT(*) > 1
  )
UNION ALL
-- ATM-DU-004 | Duplicate ATM Product Type Records (DFCTCD+DFGMAB+DFPDTY)
SELECT 'ATM-DU-004', 'Duplicate ATM Product Type: ATPDCPP (DFCTCD+DFGMAB+DFPDTY)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM (
    SELECT DFCTCD, DFGMAB, DFPDTY, COUNT(*) AS cnt
      FROM DATACUT3.ATM_MT_ATPDCPP
     GROUP BY DFCTCD, DFGMAB, DFPDTY HAVING COUNT(*) > 1
  )
UNION ALL
-- ATM-DU-005 | Duplicate Account Suffix Records (ASCTCD+ASGMAB+ASSFXS+ASSFXE)
SELECT 'ATM-DU-005', 'Duplicate Account Suffix: ATSUFXP (ASCTCD+ASGMAB+ASSFXS+ASSFXE)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM (
    SELECT ASCTCD, ASGMAB, ASSFXS, ASSFXE, COUNT(*) AS cnt
      FROM DATACUT3.ATM_MT_ATSUFXP
     GROUP BY ASCTCD, ASGMAB, ASSFXS, ASSFXE HAVING COUNT(*) > 1
  )
UNION ALL
-- ATM-DU-006 | Duplicate Card Fee Records (DPCTCD+DPGMAB+DPPDTY+DPAPTY)
SELECT 'ATM-DU-006', 'Duplicate Card Fee: ATCFEEP (DPCTCD+DPGMAB+DPPDTY+DPAPTY)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM (
    SELECT DPCTCD, DPGMAB, DPPDTY, DPAPTY, COUNT(*) AS cnt
      FROM DATACUT3.ATM_MT_ATCFEEP
     GROUP BY DPCTCD, DPGMAB, DPPDTY, DPAPTY HAVING COUNT(*) > 1
  )
UNION ALL
-- ATM-DU-007 | Duplicate Transaction Charge Control Records (AHCTCD+AHGMAB+AHGTID+AHPDTY+AHAPTY)
SELECT 'ATM-DU-007', 'Duplicate Transaction Charge Control: ATCHRGP (AHCTCD+AHGMAB+AHGTID+AHPDTY+AHAPTY)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM (
    SELECT AHCTCD, AHGMAB, AHGTID, AHPDTY, AHAPTY, COUNT(*) AS cnt
      FROM DATACUT3.ATM_MT_ATCHRGP
     GROUP BY AHCTCD, AHGMAB, AHGTID, AHPDTY, AHAPTY HAVING COUNT(*) > 1
  )
UNION ALL
-- ATM-DU-008 | Duplicate Account Type Mapping Records (DGCTCD+DGGMAB+DGAPTY+DGACTY)
SELECT 'ATM-DU-008', 'Duplicate Account Type Mapping: ATAACTP (DGCTCD+DGGMAB+DGAPTY+DGACTY)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM (
    SELECT DGCTCD, DGGMAB, DGAPTY, DGACTY, COUNT(*) AS cnt
      FROM DATACUT3.ATM_MT_ATAACTP
     GROUP BY DGCTCD, DGGMAB, DGAPTY, DGACTY HAVING COUNT(*) > 1
  )
      ) x
    UNION ALL
    SELECT 'CAT-ATM-06 CROSS-TABLE CONSISTENCY WITHIN ME04_ATM' AS dq_category, x.check_id, x.check_name, x.result_num, x.result_txt, x.expected
      FROM (
-- ATM-CR-001 | Cardholder Master Without Matching Extension Record
SELECT 'ATM-CR-001' AS check_id, 'Cardholder Master Without Extension Record: ATCAHFP vs AT@CAHEP' AS check_name,
       COUNT(*) AS RESULT_NUM, CAST(NULL AS VARCHAR2(200)) AS RESULT_TXT, CAST(NULL AS NUMBER) AS EXPECTED
  FROM DATACUT3.ATM_MT_ATCAHFP m
 WHERE NOT EXISTS (
   SELECT 1 FROM DATACUT3."ATM_MT_AT@CAHEP" e
    WHERE e."A@CTCD" = m.ACCTCD AND e."A@GMAB" = m.ACGMAB
      AND e."A@PAN" = m.ACPAN AND e."A@CINO" = m.ACCINO
 )
UNION ALL
-- ATM-CR-002 | Cardholder Product Type Not in Product Control Table
SELECT 'ATM-CR-002', 'Cardholder Product Type Not in ATPDCPP: ATCAHFP (ACPDTY)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ATM_MT_ATCAHFP m
 WHERE ACPDTY IS NOT NULL
   AND NOT EXISTS (SELECT 1 FROM DATACUT3.ATM_MT_ATPDCPP p WHERE p.DFPDTY = m.ACPDTY)
UNION ALL
-- ATM-CR-003 | Card Fee Product Type Not in Product Control Table
SELECT 'ATM-CR-003', 'Card Fee Product Type Not in ATPDCPP: ATCFEEP (DPPDTY)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ATM_MT_ATCFEEP f
 WHERE DPPDTY IS NOT NULL
   AND NOT EXISTS (SELECT 1 FROM DATACUT3.ATM_MT_ATPDCPP p WHERE p.DFPDTY = f.DPPDTY)
UNION ALL
-- ATM-CR-004 | Transaction Log Product Type Not in Product Control Table
SELECT 'ATM-CR-004', 'Transaction Log Product Type Not in ATPDCPP: ATTNFFP (EAPDTY)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ATM_MT_ATTNFFP t
 WHERE EAPDTY IS NOT NULL
   AND NOT EXISTS (SELECT 1 FROM DATACUT3.ATM_MT_ATPDCPP p WHERE p.DFPDTY = t.EAPDTY)
UNION ALL
-- ATM-CR-005 | Supplementary Card Without Matching Cardholder Master Record
SELECT 'ATM-CR-005', 'Supplementary Card Without Cardholder Master: MVATSUP vs ATCAHFP',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ATM_MT_MVATSUP s
 WHERE NOT EXISTS (SELECT 1 FROM DATACUT3.ATM_MT_ATCAHFP m WHERE m.ACPAN = s.SPCRNO)
      ) x
    UNION ALL
    SELECT 'CAT-ATM-07 CROSS-MODULE REFERENTIAL INTEGRITY - ATM -> HUB' AS dq_category, x.check_id, x.check_name, x.result_num, x.result_txt, x.expected
      FROM (
-- ATM-RI-001 | Cardholder Domestic Customer Link — Row Count Only [TODO-verify HUB key]
SELECT 'ATM-RI-001' AS check_id,
       'Cardholder Domestic Customer Present (ACDCG/ACDCB/ACDCS): ATCAHFP [TODO-verify HUB SSCUSTP key]' AS check_name,
       COUNT(*) AS RESULT_NUM, CAST(NULL AS VARCHAR2(200)) AS RESULT_TXT, CAST(NULL AS NUMBER) AS EXPECTED
  FROM DATACUT3.ATM_MT_ATCAHFP
 WHERE ACDCG IS NOT NULL AND ACDCB IS NOT NULL AND ACDCS IS NOT NULL
UNION ALL
-- ATM-RI-002 | Cardholder Secondary Account 1 Link — Row Count Only [TODO-verify HUB key]
SELECT 'ATM-RI-002',
       'Cardholder Secondary Account 1 Present (ACSCC1/ACSGM1/ACSAN1): ATCAHFP [TODO-verify HUB DDACMSP key]',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ATM_MT_ATCAHFP
 WHERE ACSCC1 IS NOT NULL AND ACSGM1 IS NOT NULL AND ACSAN1 IS NOT NULL
UNION ALL
-- ATM-RI-003 | Transaction Log From-Account Link — Row Count Only [TODO-verify HUB key]
SELECT 'ATM-RI-003',
       'Transaction Log From-Account Present (EAFCD/EAFGP/EAFAC): ATTNFFP [TODO-verify HUB DDACMSP key]',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ATM_MT_ATTNFFP
 WHERE EAFCD IS NOT NULL AND EAFGP IS NOT NULL AND EAFAC IS NOT NULL
      ) x
) y
ORDER BY y.dq_category, y.check_id;