SELECT
    CAST('ME13_DECEASED' AS NVARCHAR2(50))     AS DQ_TYPE,
    CAST(y.dq_category AS NVARCHAR2(100))       AS DQ_CATEGORY,
    CAST(y.check_name  AS NVARCHAR2(500))      AS CHECK_NAME,
    CAST(NULL AS NVARCHAR2(100))               AS TABLE_NAME,
    CAST(NULL AS NUMBER)                       AS FAILED_RECORDS,
    CAST(y.result_num AS NUMBER)               AS TOTAL_RECORDS,
    CAST(NULL AS NUMBER)                       AS FAILURE_PCT,
    CAST(y.check_id AS NVARCHAR2(20))          AS CHECK_ID,
    CAST(y.result_num AS NUMBER(20,2))         AS RESULT_NUM,
    CAST(y.result_txt AS NVARCHAR2(2000))       AS RESULT_TXT,
    CAST(y.expected AS NUMBER(20,2))           AS EXPECTED,
    CAST(
        CASE
            WHEN y.expected IS NOT NULL
              THEN CASE WHEN ABS(y.result_num - y.expected) * 100.0 / NULLIF(y.expected, 0) <= 0.1
                        THEN 'PASS' ELSE 'REVIEW' END
            WHEN y.result_txt IS NULL
              THEN CASE WHEN y.result_num = 0 THEN 'PASS' ELSE 'FAIL' END
            ELSE 'INFO'
        END AS NVARCHAR2(20)
    ) AS DQ_STATUS
FROM (
    SELECT 'CAT-DC13-01 COMPLETENESS - DECEASED Main Document' AS dq_category, x.check_id, x.check_name, x.result_num, x.result_txt, x.expected
      FROM (
-- DC13-CM-001 | Blank SNo (file reference / PK) in DECEASED
SELECT 'DC13-CM-001', 'Blank SNo (File Ref Number): ME13_DECEASED',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ME13_DECEASED
 WHERE TRIM(SNo) IS NULL
UNION ALL
-- DC13-CM-002 | Blank Firstname in DECEASED
SELECT 'DC13-CM-002', 'Blank Firstname: ME13_DECEASED',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ME13_DECEASED
 WHERE TRIM(Firstname) IS NULL
UNION ALL
-- DC13-CM-003 | Blank Surname in DECEASED
SELECT 'DC13-CM-003', 'Blank Surname: ME13_DECEASED',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ME13_DECEASED
 WHERE TRIM(Surname) IS NULL
UNION ALL
-- DC13-CM-004 | Blank CustNo (HUB customer link) in DECEASED
SELECT 'DC13-CM-004', 'Blank CustNo (HUB Customer Link Missing): ME13_DECEASED',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ME13_DECEASED
 WHERE TRIM(CustNo) IS NULL
UNION ALL
-- DC13-CM-005 | Blank IdNo (ID Card/Passport) in DECEASED
SELECT 'DC13-CM-005', 'Blank IdNo (ID/Passport): ME13_DECEASED',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ME13_DECEASED
 WHERE TRIM(IdNo) IS NULL
UNION ALL
-- DC13-CM-006 | Blank STATUS in DECEASED
SELECT 'DC13-CM-006', 'Blank Document STATUS: ME13_DECEASED',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ME13_DECEASED
 WHERE TRIM(STATUS) IS NULL
UNION ALL
-- DC13-CM-007 | All three Date-of-Death components blank
SELECT 'DC13-CM-007', 'All DOD Components Blank (DODdd/DODmm/DODyy): ME13_DECEASED',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ME13_DECEASED
 WHERE TRIM(DODdd) IS NULL AND TRIM(DODmm) IS NULL AND TRIM(DODyy) IS NULL
UNION ALL
-- DC13-CM-008 | All three Date-of-Birth components blank
SELECT 'DC13-CM-008', 'All DOB Components Blank (Dobdd/dobmm/dobyy): ME13_DECEASED',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ME13_DECEASED
 WHERE TRIM(Dobdd) IS NULL AND TRIM(dobmm) IS NULL AND TRIM(dobyy) IS NULL
UNION ALL
-- DC13-CM-009 | Testate = Y (has a Will) but Legal Advisor name blank
SELECT 'DC13-CM-009', 'Testate=Y but Legal Advisor (LAdvisor) Blank: ME13_DECEASED',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ME13_DECEASED
 WHERE UPPER(TRIM(Testate)) = 'Y' AND TRIM(LAdvisor) IS NULL
UNION ALL
-- DC13-CM-010 | HasChaser = Y but ChaserDate blank
SELECT 'DC13-CM-010', 'HasChaser=Y but ChaserDate Blank: ME13_DECEASED',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ME13_DECEASED
 WHERE UPPER(TRIM(HasChaser)) = 'Y' AND ChaserDate IS NULL
      ) x
    UNION ALL
    SELECT 'CAT-DC13-02 VALIDITY - Date Components & Date Ordering' AS dq_category, x.check_id, x.check_name, x.result_num, x.result_txt, x.expected
      FROM (
-- DC13-DT-001 | DODdd not numeric or out of 01-31 range
SELECT 'DC13-DT-001', 'Invalid DODdd Component (not 01-31): ME13_DECEASED',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ME13_DECEASED
 WHERE TRIM(DODdd) IS NOT NULL
   AND (NOT REGEXP_LIKE(TRIM(DODdd), '^[0-9]+$') OR TO_NUMBER(DODdd) NOT BETWEEN 1 AND 31)
UNION ALL
-- DC13-DT-002 | DODmm not numeric or out of 01-12 range
SELECT 'DC13-DT-002', 'Invalid DODmm Component (not 01-12): ME13_DECEASED',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ME13_DECEASED
 WHERE TRIM(DODmm) IS NOT NULL
   AND (NOT REGEXP_LIKE(TRIM(DODmm), '^[0-9]+$') OR TO_NUMBER(DODmm) NOT BETWEEN 1 AND 12)
UNION ALL
-- DC13-DT-003 | DODyy not numeric or implausible (before 1990 or after current year)
SELECT 'DC13-DT-003', 'Invalid/Implausible DODyy Component: ME13_DECEASED',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ME13_DECEASED
 WHERE TRIM(DODyy) IS NOT NULL
   AND (NOT REGEXP_LIKE(TRIM(DODyy), '^[0-9]+$')
        OR TO_NUMBER(DODyy) NOT BETWEEN 1990 AND TO_NUMBER(TO_CHAR(DATE '2026-06-15','YYYY')))
UNION ALL
-- DC13-DT-004 | Dobdd not numeric or out of 01-31 range
SELECT 'DC13-DT-004', 'Invalid Dobdd Component (not 01-31): ME13_DECEASED',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ME13_DECEASED
 WHERE TRIM(Dobdd) IS NOT NULL
   AND (NOT REGEXP_LIKE(TRIM(Dobdd), '^[0-9]+$') OR TO_NUMBER(Dobdd) NOT BETWEEN 1 AND 31)
UNION ALL
-- DC13-DT-005 | dobmm not numeric or out of 01-12 range
SELECT 'DC13-DT-005', 'Invalid dobmm Component (not 01-12): ME13_DECEASED',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ME13_DECEASED
 WHERE TRIM(dobmm) IS NOT NULL
   AND (NOT REGEXP_LIKE(TRIM(dobmm), '^[0-9]+$') OR TO_NUMBER(dobmm) NOT BETWEEN 1 AND 12)
UNION ALL
-- DC13-DT-006 | dobyy not numeric or implausible (before 1900 or after current year)
SELECT 'DC13-DT-006', 'Invalid/Implausible dobyy Component: ME13_DECEASED',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ME13_DECEASED
 WHERE TRIM(dobyy) IS NOT NULL
   AND (NOT REGEXP_LIKE(TRIM(dobyy), '^[0-9]+$')
        OR TO_NUMBER(dobyy) NOT BETWEEN 1900 AND TO_NUMBER(TO_CHAR(DATE '2026-06-15','YYYY')))
UNION ALL
-- DC13-DT-007 | Date of Death year earlier than Date of Birth year (logical impossibility)
-- Only evaluated where all 4 components are numeric, to avoid false positives from DT-003/006
SELECT 'DC13-DT-007', 'DOD Year Before DOB Year: ME13_DECEASED',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ME13_DECEASED
 WHERE REGEXP_LIKE(TRIM(DODyy), '^[0-9]+$') AND REGEXP_LIKE(TRIM(dobyy), '^[0-9]+$')
   AND TO_NUMBER(DODyy) < TO_NUMBER(dobyy)
UNION ALL
-- DC13-DT-008 | File creation date (SDate) in the future
SELECT 'DC13-DT-008', 'SDate (File Created) in the Future: ME13_DECEASED',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ME13_DECEASED
 WHERE SDate IS NOT NULL AND TRUNC(SDate) > TRUNC(DATE '2026-06-15')
UNION ALL
-- DC13-DT-009 | Datesettled earlier than SDate (settled before the file was even opened)
SELECT 'DC13-DT-009', 'Datesettled Before SDate (Settlement Predates File): ME13_DECEASED',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ME13_DECEASED
 WHERE Datesettled IS NOT NULL AND SDate IS NOT NULL AND TRUNC(Datesettled) < TRUNC(SDate)
UNION ALL
-- DC13-DT-010 | ChaserReviewDate earlier than ChaserDate
SELECT 'DC13-DT-010', 'ChaserReviewDate Before ChaserDate: ME13_DECEASED',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ME13_DECEASED
 WHERE ChaserReviewDate IS NOT NULL AND ChaserDate IS NOT NULL
   AND TRUNC(ChaserReviewDate) < TRUNC(ChaserDate)
      ) x
    UNION ALL
    SELECT 'CAT-DC13-03 REFERENTIAL INTEGRITY - Child Sub-Forms vs DECEASED Main Doc' AS dq_category, x.check_id, x.check_name, x.result_num, x.result_txt, x.expected
      FROM (
-- DC13-RI-001 | CARDPRODS Record Without Matching DECEASED Main Document (orphan SNo)
SELECT 'DC13-RI-001', 'Orphan CARDPRODS Record (SNo not in DECEASED): ME13_CARDPRODS',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ME13_CARDPRODS C
 WHERE C.SNo IS NOT NULL
   AND NOT EXISTS (SELECT 1 FROM DATACUT3.ME13_DECEASED D WHERE D.SNo = C.SNo)
UNION ALL
-- DC13-RI-002 | COMPSEC Record Without Matching DECEASED Main Document (orphan SNo)
SELECT 'DC13-RI-002', 'Orphan COMPSEC Record (SNo not in DECEASED): ME13_COMPSEC',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ME13_COMPSEC C
 WHERE C.SNo IS NOT NULL
   AND NOT EXISTS (SELECT 1 FROM DATACUT3.ME13_DECEASED D WHERE D.SNo = C.SNo)
UNION ALL
-- DC13-RI-003 | CUSTODY Record Without Matching DECEASED Main Document (orphan SNo)
SELECT 'DC13-RI-003', 'Orphan CUSTODY Record (SNo not in DECEASED): ME13_CUSTODY',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ME13_CUSTODY C
 WHERE C.SNo IS NOT NULL
   AND NOT EXISTS (SELECT 1 FROM DATACUT3.ME13_DECEASED D WHERE D.SNo = C.SNo)
UNION ALL
-- DC13-RI-004 | CHASER Record Without Matching DECEASED Main Document (orphan SNo)
SELECT 'DC13-RI-004', 'Orphan CHASER Record (SNo not in DECEASED): ME13_CHASER',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ME13_CHASER C
 WHERE C.SNo IS NOT NULL
   AND NOT EXISTS (SELECT 1 FROM DATACUT3.ME13_DECEASED D WHERE D.SNo = C.SNo)
UNION ALL
-- DC13-RI-005 | FUNDMAN Record Without Matching DECEASED Main Document (orphan SNo)
SELECT 'DC13-RI-005', 'Orphan FUNDMAN Record (SNo not in DECEASED): ME13_FUNDMAN',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ME13_FUNDMAN C
 WHERE C.SNo IS NOT NULL
   AND NOT EXISTS (SELECT 1 FROM DATACUT3.ME13_DECEASED D WHERE D.SNo = C.SNo)
UNION ALL
-- DC13-RI-006 | HELDFUNDS Record Without Matching DECEASED Main Document (orphan SNo)
SELECT 'DC13-RI-006', 'Orphan HELDFUNDS Record (SNo not in DECEASED): ME13_HELDFUNDS',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ME13_HELDFUNDS C
 WHERE C.SNo IS NOT NULL
   AND NOT EXISTS (SELECT 1 FROM DATACUT3.ME13_DECEASED D WHERE D.SNo = C.SNo)
UNION ALL
-- DC13-RI-007 | LIFEASSURE Record Without Matching DECEASED Main Document (orphan SNo)
SELECT 'DC13-RI-007', 'Orphan LIFEASSURE Record (SNo not in DECEASED): ME13_LIFEASSURE',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ME13_LIFEASSURE C
 WHERE C.SNo IS NOT NULL
   AND NOT EXISTS (SELECT 1 FROM DATACUT3.ME13_DECEASED D WHERE D.SNo = C.SNo)
UNION ALL
-- DC13-RI-008 | PRIVBILL Record Without Matching DECEASED Main Document (orphan SNo)
SELECT 'DC13-RI-008', 'Orphan PRIVBILL Record (SNo not in DECEASED): ME13_PRIVBILL',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ME13_PRIVBILL C
 WHERE C.SNo IS NOT NULL
   AND NOT EXISTS (SELECT 1 FROM DATACUT3.ME13_DECEASED D WHERE D.SNo = C.SNo)
UNION ALL
-- DC13-RI-009 | G355SETT Record Without Matching DECEASED Main Document (orphan SNo)
SELECT 'DC13-RI-009', 'Orphan G355SETT Record (SNo not in DECEASED): ME13_G355SETT',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ME13_G355SETT C
 WHERE C.SNo IS NOT NULL
   AND NOT EXISTS (SELECT 1 FROM DATACUT3.ME13_DECEASED D WHERE D.SNo = C.SNo)
UNION ALL
-- DC13-RI-010 | SETHEIRLEG Record Without Matching DECEASED Main Document (orphan SNo)
SELECT 'DC13-RI-010', 'Orphan SETHEIRLEG Record (SNo not in DECEASED): ME13_SETHEIRLEG',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ME13_SETHEIRLEG C
 WHERE C.SNo IS NOT NULL
   AND NOT EXISTS (SELECT 1 FROM DATACUT3.ME13_DECEASED D WHERE D.SNo = C.SNo)
UNION ALL
-- DC13-RI-011 | SETCLSDACC Record Without Matching DECEASED Main Document (orphan SNo)
SELECT 'DC13-RI-011', 'Orphan SETCLSDACC Record (SNo not in DECEASED): ME13_SETCLSDACC',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ME13_SETCLSDACC C
 WHERE C.SNo IS NOT NULL
   AND NOT EXISTS (SELECT 1 FROM DATACUT3.ME13_DECEASED D WHERE D.SNo = C.SNo)
UNION ALL
-- DC13-RI-012 | SETWDRWACC Record Without Matching DECEASED Main Document (orphan SNo)
SELECT 'DC13-RI-012', 'Orphan SETWDRWACC Record (SNo not in DECEASED): ME13_SETWDRWACC',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ME13_SETWDRWACC C
 WHERE C.SNo IS NOT NULL
   AND NOT EXISTS (SELECT 1 FROM DATACUT3.ME13_DECEASED D WHERE D.SNo = C.SNo)
UNION ALL
-- DC13-RI-013 | SETDEDRETB Record Without Matching DECEASED Main Document (orphan SNo)
SELECT 'DC13-RI-013', 'Orphan SETDEDRETB Record (SNo not in DECEASED): ME13_SETDEDRETB',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ME13_SETDEDRETB C
 WHERE C.SNo IS NOT NULL
   AND NOT EXISTS (SELECT 1 FROM DATACUT3.ME13_DECEASED D WHERE D.SNo = C.SNo)
UNION ALL
-- DC13-RI-014 | SETNOTFEED Record Without Matching DECEASED Main Document (orphan SNo)
SELECT 'DC13-RI-014', 'Orphan SETNOTFEED Record (SNo not in DECEASED): ME13_SETNOTFEED',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ME13_SETNOTFEED C
 WHERE C.SNo IS NOT NULL
   AND NOT EXISTS (SELECT 1 FROM DATACUT3.ME13_DECEASED D WHERE D.SNo = C.SNo)
UNION ALL
-- DC13-RI-015 | SETDEDLEG Record Without Matching DECEASED Main Document (orphan SNo)
SELECT 'DC13-RI-015', 'Orphan SETDEDLEG Record (SNo not in DECEASED): ME13_SETDEDLEG',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ME13_SETDEDLEG C
 WHERE C.SNo IS NOT NULL
   AND NOT EXISTS (SELECT 1 FROM DATACUT3.ME13_DECEASED D WHERE D.SNo = C.SNo)
UNION ALL
-- DC13-RI-016 | SETFURDED Record Without Matching DECEASED Main Document (orphan SNo)
SELECT 'DC13-RI-016', 'Orphan SETFURDED Record (SNo not in DECEASED): ME13_SETFURDED',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ME13_SETFURDED C
 WHERE C.SNo IS NOT NULL
   AND NOT EXISTS (SELECT 1 FROM DATACUT3.ME13_DECEASED D WHERE D.SNo = C.SNo)
UNION ALL
-- DC13-RI-017 | SETPARTITD Record Without Matching DECEASED Main Document (orphan SNo)
SELECT 'DC13-RI-017', 'Orphan SETPARTITD Record (SNo not in DECEASED): ME13_SETPARTITD',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ME13_SETPARTITD C
 WHERE C.SNo IS NOT NULL
   AND NOT EXISTS (SELECT 1 FROM DATACUT3.ME13_DECEASED D WHERE D.SNo = C.SNo)
UNION ALL
-- DC13-RI-018 | SETARTHEIR Record Without Matching DECEASED Main Document (orphan SNo)
SELECT 'DC13-RI-018', 'Orphan SETARTHEIR Record (SNo not in DECEASED): ME13_SETARTHEIR',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ME13_SETARTHEIR C
 WHERE C.SNo IS NOT NULL
   AND NOT EXISTS (SELECT 1 FROM DATACUT3.ME13_DECEASED D WHERE D.SNo = C.SNo)
UNION ALL
-- DC13-RI-019 | SETTRFSHBN Record Without Matching DECEASED Main Document (orphan SNo)
SELECT 'DC13-RI-019', 'Orphan SETTRFSHBN Record (SNo not in DECEASED): ME13_SETTRFSHBN',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ME13_SETTRFSHBN C
 WHERE C.SNo IS NOT NULL
   AND NOT EXISTS (SELECT 1 FROM DATACUT3.ME13_DECEASED D WHERE D.SNo = C.SNo)
UNION ALL
-- DC13-RI-020 | SETFUNDTRF Record Without Matching DECEASED Main Document (orphan SNo)
SELECT 'DC13-RI-020', 'Orphan SETFUNDTRF Record (SNo not in DECEASED): ME13_SETFUNDTRF',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ME13_SETFUNDTRF C
 WHERE C.SNo IS NOT NULL
   AND NOT EXISTS (SELECT 1 FROM DATACUT3.ME13_DECEASED D WHERE D.SNo = C.SNo)
UNION ALL
-- DC13-RI-021 | SETINSCLM Record Without Matching DECEASED Main Document (orphan SNo)
SELECT 'DC13-RI-021', 'Orphan SETINSCLM Record (SNo not in DECEASED): ME13_SETINSCLM',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ME13_SETINSCLM C
 WHERE C.SNo IS NOT NULL
   AND NOT EXISTS (SELECT 1 FROM DATACUT3.ME13_DECEASED D WHERE D.SNo = C.SNo)
UNION ALL
-- DC13-RI-022 | SETSECTRF Record Without Matching DECEASED Main Document (orphan SNo)
SELECT 'DC13-RI-022', 'Orphan SETSECTRF Record (SNo not in DECEASED): ME13_SETSECTRF',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ME13_SETSECTRF C
 WHERE C.SNo IS NOT NULL
   AND NOT EXISTS (SELECT 1 FROM DATACUT3.ME13_DECEASED D WHERE D.SNo = C.SNo)
UNION ALL
-- DC13-RI-023 | SETPARSAFE Record Without Matching DECEASED Main Document (orphan SNo)
SELECT 'DC13-RI-023', 'Orphan SETPARSAFE Record (SNo not in DECEASED): ME13_SETPARSAFE',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ME13_SETPARSAFE C
 WHERE C.SNo IS NOT NULL
   AND NOT EXISTS (SELECT 1 FROM DATACUT3.ME13_DECEASED D WHERE D.SNo = C.SNo)
      ) x
    UNION ALL
    SELECT 'CAT-DC13-04 DUPLICATE CHECKS - DECEASED Main Document' AS dq_category, x.check_id, x.check_name, x.result_num, x.result_txt, x.expected
      FROM (
-- DC13-DP-001 | Duplicate SNo (file ref number should be unique) in DECEASED
SELECT 'DC13-DP-001', 'Duplicate SNo (File Ref Number): ME13_DECEASED',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM (SELECT SNo FROM DATACUT3.ME13_DECEASED
        WHERE TRIM(SNo) IS NOT NULL GROUP BY SNo HAVING COUNT(*) > 1)
UNION ALL
-- DC13-DP-002 | Duplicate CustNo (same HUB customer deceased-flagged more than once)
SELECT 'DC13-DP-002', 'Duplicate CustNo Across Deceased Files: ME13_DECEASED',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM (SELECT CustNo FROM DATACUT3.ME13_DECEASED
        WHERE TRIM(CustNo) IS NOT NULL GROUP BY CustNo HAVING COUNT(*) > 1)
UNION ALL
-- DC13-DP-003 | Duplicate IdNo (same ID Card/Passport across deceased files)
SELECT 'DC13-DP-003', 'Duplicate IdNo Across Deceased Files: ME13_DECEASED',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM (SELECT IdNo FROM DATACUT3.ME13_DECEASED
        WHERE TRIM(IdNo) IS NOT NULL GROUP BY IdNo HAVING COUNT(*) > 1)
UNION ALL
-- DC13-DP-004 | Possible duplicate person entry: same Firstname+Surname+DOB year, different SNo (INFO)
SELECT 'DC13-DP-004', 'Possible Duplicate Person (Firstname+Surname+DODyy, different SNo): ME13_DECEASED',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM (SELECT Firstname, Surname, DODyy FROM DATACUT3.ME13_DECEASED
        WHERE TRIM(Firstname) IS NOT NULL AND TRIM(Surname) IS NOT NULL
        GROUP BY Firstname, Surname, DODyy HAVING COUNT(*) > 1)
      ) x
    UNION ALL
    SELECT 'CAT-DC13-05 STATUS / WORKFLOW DISTRIBUTION' AS dq_category, x.check_id, x.check_name, x.result_num, x.result_txt, x.expected
      FROM (
-- DC13-DM-001 | Document STATUS Distribution: DECEASED
SELECT 'DC13-DM-001', 'Document STATUS Distribution: ME13_DECEASED',
       COUNT(*), NVL(STATUS,'[NULL]'), CAST(NULL AS NUMBER)
  FROM DATACUT3.ME13_DECEASED GROUP BY STATUS
UNION ALL
-- DC13-DM-002 | Purge Status Distribution: DECEASED
SELECT 'DC13-DM-002', 'PURGE_STATUS Distribution: ME13_DECEASED',
       COUNT(*), NVL(PURGE_STATUS,'[NULL]'), CAST(NULL AS NUMBER)
  FROM DATACUT3.ME13_DECEASED GROUP BY PURGE_STATUS
UNION ALL
-- DC13-DM-003 | Civil Status (State) Distribution: DECEASED
SELECT 'DC13-DM-003', 'Civil Status (State) Distribution: ME13_DECEASED',
       COUNT(*), NVL(State,'[NULL]'), CAST(NULL AS NUMBER)
  FROM DATACUT3.ME13_DECEASED GROUP BY State
UNION ALL
-- DC13-DM-004 | Testate (Has a Will) Distribution: DECEASED
SELECT 'DC13-DM-004', 'Testate Distribution: ME13_DECEASED',
       COUNT(*), NVL(Testate,'[NULL]'), CAST(NULL AS NUMBER)
  FROM DATACUT3.ME13_DECEASED GROUP BY Testate
UNION ALL
-- DC13-DM-005 | Death Certificate Availability Distribution: DECEASED
SELECT 'DC13-DM-005', 'Death Certificate Availability Distribution (deathcert): ME13_DECEASED',
       COUNT(*), NVL(deathcert,'[NULL]'), CAST(NULL AS NUMBER)
  FROM DATACUT3.ME13_DECEASED GROUP BY deathcert
UNION ALL
-- DC13-DM-006 | HasChaser Distribution: DECEASED
SELECT 'DC13-DM-006', 'HasChaser Distribution: ME13_DECEASED',
       COUNT(*), NVL(HasChaser,'[NULL]'), CAST(NULL AS NUMBER)
  FROM DATACUT3.ME13_DECEASED GROUP BY HasChaser
UNION ALL
-- DC13-DM-007 | Settlement Type Distribution: G355SETT
SELECT 'DC13-DM-007', 'Settlement Type Distribution (TYPEOFSETTLEMENT): ME13_G355SETT',
       COUNT(*), NVL(TYPEOFSETTLEMENT,'[NULL]'), CAST(NULL AS NUMBER)
  FROM DATACUT3.ME13_G355SETT GROUP BY TYPEOFSETTLEMENT
UNION ALL
-- DC13-DM-008 | Document STATUS Distribution: G355SETT
SELECT 'DC13-DM-008', 'Document STATUS Distribution: ME13_G355SETT',
       COUNT(*), NVL(STATUS,'[NULL]'), CAST(NULL AS NUMBER)
  FROM DATACUT3.ME13_G355SETT GROUP BY STATUS
UNION ALL
-- DC13-DM-009 | Settlement Type Distribution: SETCLSDACC (Closed Accounts)
SELECT 'DC13-DM-009', 'SettlementType Distribution: ME13_SETCLSDACC',
       COUNT(*), NVL(SettlementType,'[NULL]'), CAST(NULL AS NUMBER)
  FROM DATACUT3.ME13_SETCLSDACC GROUP BY SettlementType
UNION ALL
-- DC13-DM-010 | Card Products "Choice" (Selection of Information in Hand) Distribution
SELECT 'DC13-DM-010', 'Choice Distribution: ME13_CARDPRODS',
       COUNT(*), NVL(Choice,'[NULL]'), CAST(NULL AS NUMBER)
  FROM DATACUT3.ME13_CARDPRODS GROUP BY Choice
      ) x
    UNION ALL
    SELECT 'CAT-DC13-06 SETTLEMENT WORKFLOW CONSISTENCY' AS dq_category, x.check_id, x.check_name, x.result_num, x.result_txt, x.expected
      FROM (
-- DC13-WF-001 | STATUS text suggests closed/settled but Datesettled is NULL
-- TODO: confirm exact closed/settled STATUS code values with NC/HSBC (assumed contains
-- 'CLOS' or 'SETT' — this pattern-match is a placeholder until the code list is confirmed)
SELECT 'DC13-WF-001', 'STATUS Suggests Closed/Settled but Datesettled NULL: ME13_DECEASED',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ME13_DECEASED
 WHERE (UPPER(STATUS) LIKE '%CLOS%' OR UPPER(STATUS) LIKE '%SETT%')
   AND Datesettled IS NULL
UNION ALL
-- DC13-WF-002 | Datesettled populated but STATUS does not indicate closed/settled (inconsistent)
SELECT 'DC13-WF-002', 'Datesettled Populated but STATUS Not Closed/Settled: ME13_DECEASED',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ME13_DECEASED
 WHERE Datesettled IS NOT NULL
   AND NOT (UPPER(STATUS) LIKE '%CLOS%' OR UPPER(STATUS) LIKE '%SETT%')
UNION ALL
-- DC13-WF-003 | G355SETT settlement record exists but parent DECEASED.Datesettled is NULL
SELECT 'DC13-WF-003', 'G355SETT Exists but Parent Datesettled NULL: ME13_G355SETT vs ME13_DECEASED',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ME13_G355SETT G
  JOIN DATACUT3.ME13_DECEASED D ON D.SNo = G.SNo
 WHERE D.Datesettled IS NULL
UNION ALL
-- DC13-WF-004 | Closed-account settlement record (SETCLSDACC) with no matching G355SETT
SELECT 'DC13-WF-004', 'SETCLSDACC Without Matching G355SETT: ME13_SETCLSDACC vs ME13_G355SETT',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ME13_SETCLSDACC S
 WHERE S.SNo IS NOT NULL
   AND NOT EXISTS (SELECT 1 FROM DATACUT3.ME13_G355SETT G WHERE G.SNo = S.SNo)
UNION ALL
-- DC13-WF-005 | Withdrawal-from-account record (SETWDRWACC) with no matching G355SETT
SELECT 'DC13-WF-005', 'SETWDRWACC Without Matching G355SETT: ME13_SETWDRWACC vs ME13_G355SETT',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ME13_SETWDRWACC S
 WHERE S.SNo IS NOT NULL
   AND NOT EXISTS (SELECT 1 FROM DATACUT3.ME13_G355SETT G WHERE G.SNo = S.SNo)
UNION ALL
-- DC13-WF-006 | HasChaser = Y on DECEASED but no CHASER record exists for that file
SELECT 'DC13-WF-006', 'HasChaser=Y but No CHASER Record: ME13_DECEASED vs ME13_CHASER',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ME13_DECEASED D
 WHERE UPPER(TRIM(D.HasChaser)) = 'Y'
   AND NOT EXISTS (SELECT 1 FROM DATACUT3.ME13_CHASER C WHERE C.SNo = D.SNo)
UNION ALL
-- DC13-WF-007 | CHASER record exists but parent DECEASED.HasChaser is not Y (inconsistent flag)
SELECT 'DC13-WF-007', 'CHASER Record Exists but HasChaser<>Y on Parent: ME13_CHASER vs ME13_DECEASED',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ME13_CHASER C
  JOIN DATACUT3.ME13_DECEASED D ON D.SNo = C.SNo
 WHERE NVL(UPPER(TRIM(D.HasChaser)),'N') <> 'Y'
UNION ALL
-- DC13-WF-008 | Purged file (PURGE_STATUS) still carrying child sub-form records (INFO)
-- TODO: confirm exact purge status code / expected post-purge child-record behaviour with NC
SELECT 'DC13-WF-008', 'Purged DECEASED File Still Has Child Records (scope TBC): ME13_DECEASED',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ME13_DECEASED D
 WHERE UPPER(NVL(D.PURGE_STATUS,'')) LIKE '%PURG%'
   AND EXISTS (SELECT 1 FROM DATACUT3.ME13_HELDFUNDS H WHERE H.SNo = D.SNo)
      ) x
    UNION ALL
    SELECT 'CAT-DC13-07 CURRENCY / AMOUNT SANITY' AS dq_category, x.check_id, x.check_name, x.result_num, x.result_txt, x.expected
      FROM (
-- DC13-FN-001 | Negative card outstanding balance (Bal1-4): CARDPRODS
SELECT 'DC13-FN-001', 'Negative Card Outstanding Balance (Bal1-4): ME13_CARDPRODS',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ME13_CARDPRODS
 WHERE NVL(Bal1,0) < 0 OR NVL(Bal2,0) < 0 OR NVL(Bal3,0) < 0 OR NVL(Bal4,0) < 0
UNION ALL
-- DC13-FN-002 | Negative security amount (CCAmnt1): COMPSEC (representative field of 10)
-- TODO: extend to CCAmnt2..10 once column list is scripted/generated for production run
SELECT 'DC13-FN-002', 'Negative Security Amount (CCAmnt1): ME13_COMPSEC',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ME13_COMPSEC
 WHERE NVL(CCAmnt1,0) < 0
UNION ALL
-- DC13-FN-003 | Negative custody amount (Amnt1): CUSTODY (representative field of 10)
-- TODO: extend to Amnt2..10 once column list is scripted/generated for production run
SELECT 'DC13-FN-003', 'Negative Custody Amount (Amnt1): ME13_CUSTODY',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ME13_CUSTODY
 WHERE NVL(Amnt1,0) < 0
UNION ALL
-- DC13-FN-004 | Negative fund management amount (Amnt1): FUNDMAN
SELECT 'DC13-FN-004', 'Negative Fund Management Amount (Amnt1): ME13_FUNDMAN',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ME13_FUNDMAN
 WHERE NVL(Amnt1,0) < 0
UNION ALL
-- DC13-FN-005 | Negative life assurance amount (Amnt1): LIFEASSURE
SELECT 'DC13-FN-005', 'Negative Life Assurance Amount (Amnt1): ME13_LIFEASSURE',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ME13_LIFEASSURE
 WHERE NVL(Amnt1,0) < 0
UNION ALL
-- DC13-FN-006 | Negative privilege bill amount: PRIVBILL
SELECT 'DC13-FN-006', 'Negative Amount: ME13_PRIVBILL',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ME13_PRIVBILL
 WHERE NVL(Amount,0) < 0
UNION ALL
-- DC13-FN-007 | Negative withdrawal balance: SETWDRWACC
SELECT 'DC13-FN-007', 'Negative Balance: ME13_SETWDRWACC',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ME13_SETWDRWACC
 WHERE NVL(Balance,0) < 0
UNION ALL
-- DC13-FN-008 | Negative notary/lawyer fee balance: SETNOTFEED
SELECT 'DC13-FN-008', 'Negative Balance: ME13_SETNOTFEED',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ME13_SETNOTFEED
 WHERE NVL(Balance,0) < 0
UNION ALL
-- DC13-FN-009 | Negative deducted legacy balance: SETDEDLEG
SELECT 'DC13-FN-009', 'Negative Balance: ME13_SETDEDLEG',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ME13_SETDEDLEG
 WHERE NVL(Balance,0) < 0
UNION ALL
-- DC13-FN-010 | Invalid ISO currency code length (<>3 chars, value not displayed - masked field)
SELECT 'DC13-FN-010', 'Invalid ISO Currency Code Length (across settlement tables)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM (
    SELECT Currency AS CCY FROM DATACUT3.ME13_SETCLSDACC WHERE Currency IS NOT NULL
    UNION ALL
    SELECT Currency FROM DATACUT3.ME13_SETWDRWACC WHERE Currency IS NOT NULL
    UNION ALL
    SELECT Currency FROM DATACUT3.ME13_SETDEDRETB WHERE Currency IS NOT NULL
    UNION ALL
    SELECT Currency FROM DATACUT3.ME13_SETNOTFEED WHERE Currency IS NOT NULL
    UNION ALL
    SELECT Currency FROM DATACUT3.ME13_SETDEDLEG WHERE Currency IS NOT NULL
    UNION ALL
    SELECT CCY FROM DATACUT3.ME13_PRIVBILL WHERE CCY IS NOT NULL
  ) X
 WHERE LENGTH(TRIM(CCY)) <> 3
      ) x
    UNION ALL
    SELECT 'CAT-DC13-08 VOLUME / ROW COUNTS' AS dq_category, x.check_id, x.check_name, x.result_num, x.result_txt, x.expected
      FROM (
-- DC13-RC-001 | Row Count: ME13_DECEASED (EXPECTED pending NC/HSBC DC3 benchmark)
SELECT 'DC13-RC-001', 'Row Count: ME13_DECEASED',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ME13_DECEASED
UNION ALL
-- DC13-RC-002 | Row Count: ME13_CARDPRODS (EXPECTED pending NC/HSBC DC3 benchmark)
SELECT 'DC13-RC-002', 'Row Count: ME13_CARDPRODS',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ME13_CARDPRODS
UNION ALL
-- DC13-RC-003 | Row Count: ME13_COMPSEC (EXPECTED pending NC/HSBC DC3 benchmark)
SELECT 'DC13-RC-003', 'Row Count: ME13_COMPSEC',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ME13_COMPSEC
UNION ALL
-- DC13-RC-004 | Row Count: ME13_CUSTODY (EXPECTED pending NC/HSBC DC3 benchmark)
SELECT 'DC13-RC-004', 'Row Count: ME13_CUSTODY',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ME13_CUSTODY
UNION ALL
-- DC13-RC-005 | Row Count: ME13_CHASER (EXPECTED pending NC/HSBC DC3 benchmark)
SELECT 'DC13-RC-005', 'Row Count: ME13_CHASER',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ME13_CHASER
UNION ALL
-- DC13-RC-006 | Row Count: ME13_FUNDMAN (EXPECTED pending NC/HSBC DC3 benchmark)
SELECT 'DC13-RC-006', 'Row Count: ME13_FUNDMAN',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ME13_FUNDMAN
UNION ALL
-- DC13-RC-007 | Row Count: ME13_HELDFUNDS (EXPECTED pending NC/HSBC DC3 benchmark)
SELECT 'DC13-RC-007', 'Row Count: ME13_HELDFUNDS',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ME13_HELDFUNDS
UNION ALL
-- DC13-RC-008 | Row Count: ME13_LIFEASSURE (EXPECTED pending NC/HSBC DC3 benchmark)
SELECT 'DC13-RC-008', 'Row Count: ME13_LIFEASSURE',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ME13_LIFEASSURE
UNION ALL
-- DC13-RC-009 | Row Count: ME13_PRIVBILL (EXPECTED pending NC/HSBC DC3 benchmark)
SELECT 'DC13-RC-009', 'Row Count: ME13_PRIVBILL',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ME13_PRIVBILL
UNION ALL
-- DC13-RC-010 | Row Count: ME13_G355SETT (EXPECTED pending NC/HSBC DC3 benchmark)
SELECT 'DC13-RC-010', 'Row Count: ME13_G355SETT',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ME13_G355SETT
UNION ALL
-- DC13-RC-011 | Row Count: ME13_SETHEIRLEG (EXPECTED pending NC/HSBC DC3 benchmark)
SELECT 'DC13-RC-011', 'Row Count: ME13_SETHEIRLEG',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ME13_SETHEIRLEG
UNION ALL
-- DC13-RC-012 | Row Count: ME13_SETCLSDACC (EXPECTED pending NC/HSBC DC3 benchmark)
SELECT 'DC13-RC-012', 'Row Count: ME13_SETCLSDACC',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ME13_SETCLSDACC
UNION ALL
-- DC13-RC-013 | Row Count: ME13_SETWDRWACC (EXPECTED pending NC/HSBC DC3 benchmark)
SELECT 'DC13-RC-013', 'Row Count: ME13_SETWDRWACC',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ME13_SETWDRWACC
UNION ALL
-- DC13-RC-014 | Row Count: ME13_SETDEDRETB (EXPECTED pending NC/HSBC DC3 benchmark)
SELECT 'DC13-RC-014', 'Row Count: ME13_SETDEDRETB',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ME13_SETDEDRETB
UNION ALL
-- DC13-RC-015 | Row Count: ME13_SETNOTFEED (EXPECTED pending NC/HSBC DC3 benchmark)
SELECT 'DC13-RC-015', 'Row Count: ME13_SETNOTFEED',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ME13_SETNOTFEED
UNION ALL
-- DC13-RC-016 | Row Count: ME13_SETDEDLEG (EXPECTED pending NC/HSBC DC3 benchmark)
SELECT 'DC13-RC-016', 'Row Count: ME13_SETDEDLEG',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ME13_SETDEDLEG
UNION ALL
-- DC13-RC-017 | Row Count: ME13_SETFURDED (EXPECTED pending NC/HSBC DC3 benchmark)
SELECT 'DC13-RC-017', 'Row Count: ME13_SETFURDED',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ME13_SETFURDED
UNION ALL
-- DC13-RC-018 | Row Count: ME13_SETPARTITD (EXPECTED pending NC/HSBC DC3 benchmark)
SELECT 'DC13-RC-018', 'Row Count: ME13_SETPARTITD',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ME13_SETPARTITD
UNION ALL
-- DC13-RC-019 | Row Count: ME13_SETARTHEIR (EXPECTED pending NC/HSBC DC3 benchmark)
SELECT 'DC13-RC-019', 'Row Count: ME13_SETARTHEIR',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ME13_SETARTHEIR
UNION ALL
-- DC13-RC-020 | Row Count: ME13_SETTRFSHBN (EXPECTED pending NC/HSBC DC3 benchmark)
SELECT 'DC13-RC-020', 'Row Count: ME13_SETTRFSHBN',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ME13_SETTRFSHBN
UNION ALL
-- DC13-RC-021 | Row Count: ME13_SETFUNDTRF (EXPECTED pending NC/HSBC DC3 benchmark)
SELECT 'DC13-RC-021', 'Row Count: ME13_SETFUNDTRF',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ME13_SETFUNDTRF
UNION ALL
-- DC13-RC-022 | Row Count: ME13_SETINSCLM (EXPECTED pending NC/HSBC DC3 benchmark)
SELECT 'DC13-RC-022', 'Row Count: ME13_SETINSCLM',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ME13_SETINSCLM
UNION ALL
-- DC13-RC-023 | Row Count: ME13_SETSECTRF (EXPECTED pending NC/HSBC DC3 benchmark)
SELECT 'DC13-RC-023', 'Row Count: ME13_SETSECTRF',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ME13_SETSECTRF
UNION ALL
-- DC13-RC-024 | Row Count: ME13_SETPARSAFE (EXPECTED pending NC/HSBC DC3 benchmark)
SELECT 'DC13-RC-024', 'Row Count: ME13_SETPARSAFE',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ME13_SETPARSAFE
UNION ALL
-- DC13-RC-025 | Row Count: ME13_SETUPDOC (EXPECTED pending NC/HSBC DC3 benchmark)
SELECT 'DC13-RC-025', 'Row Count: ME13_SETUPDOC',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ME13_SETUPDOC
UNION ALL
-- DC13-RC-026 | Row Count: ME13_NOTARDETS (EXPECTED pending NC/HSBC DC3 benchmark)
SELECT 'DC13-RC-026', 'Row Count: ME13_NOTARDETS',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ME13_NOTARDETS
UNION ALL
-- DC13-RC-027 | Row Count: ME13_KEYWORD (EXPECTED pending NC/HSBC DC3 benchmark)
SELECT 'DC13-RC-027', 'Row Count: ME13_KEYWORD',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ME13_KEYWORD
UNION ALL
-- DC13-RC-028 | Row Count: ME13_TOWNLIST (EXPECTED pending NC/HSBC DC3 benchmark)
SELECT 'DC13-RC-028', 'Row Count: ME13_TOWNLIST',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.ME13_TOWNLIST
      ) x
) y
ORDER BY y.dq_category, y.check_id;
