SELECT
    CAST('ME20_HIE' AS NVARCHAR2(50))          AS DQ_TYPE,
    CAST(y.dq_category AS NVARCHAR2(100))       AS DQ_CATEGORY,
    CAST(y.check_name  AS NVARCHAR2(500))      AS CHECK_NAME,
    CAST(NULL AS NVARCHAR2(100))               AS TABLE_NAME,
    CAST(NULL AS NUMBER)                       AS FAILED_RECORDS,
    CAST(y.result_num AS NUMBER)               AS TOTAL_RECORDS,
    CAST(NULL AS NUMBER)                       AS FAILURE_PCT,
    CAST(y.check_id AS NVARCHAR2(20))          AS CHECK_ID,
    CAST(y.result_num AS NUMBER(20,2))         AS RESULT_NUM,
    CAST(y.result_txt AS NVARCHAR2(2000))       AS RESULT_TXT,
    CAST(y.expected AS NUMBER(20,2))           AS EXPECTED,
    CAST(
        CASE
            WHEN y.expected IS NOT NULL
              THEN CASE WHEN ABS(y.result_num - y.expected) * 100.0 / NULLIF(y.expected, 0) <= 0.1
                        THEN 'PASS' ELSE 'REVIEW' END
            WHEN y.result_txt IS NULL
              THEN CASE WHEN y.result_num = 0 THEN 'PASS' ELSE 'FAIL' END
            ELSE 'INFO'
        END AS NVARCHAR2(20)
    ) AS DQ_STATUS
FROM (
    SELECT 'CAT-HIE-01 VOLUME RECONCILIATION' AS dq_category, x.check_id, x.check_name, x.result_num, x.result_txt, x.expected
      FROM (
-- HIE-RC-001 | Row Count: IMP DC Master (HIE_IPDCMSP)
-- ANALYSIS: Primary Imports DC master. EXPECTED TBD — OI-011.
SELECT 'HIE-RC-001' AS check_id, 'Row Count: IMP DC Master (IPDCMSP)' AS check_name,
       COUNT(*) AS RESULT_NUM, CAST(NULL AS VARCHAR2(200)) AS RESULT_TXT,
       CAST(NULL AS NUMBER) AS EXPECTED
  FROM DATACUT3.HIE_IPDCMSP
UNION ALL
-- HIE-RC-002 | Row Count: EXP Collection File Master (HIE_EPCFMSP)
SELECT 'HIE-RC-002', 'Row Count: EXP Collection File Master (EPCFMSP)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.HIE_EPCFMSP
UNION ALL
-- HIE-RC-003 | Row Count: IMP DC Clause Record (HIE_IPMSCLP)
SELECT 'HIE-RC-003', 'Row Count: IMP DC Clause Record (IPMSCLP)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.HIE_IPMSCLP
UNION ALL
-- HIE-RC-004 | Row Count: IMP DC History (HIE_IPDCHSP)
SELECT 'HIE-RC-004', 'Row Count: IMP DC History (IPDCHSP)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.HIE_IPDCHSP
UNION ALL
-- HIE-RC-005 | Row Count: IMP A/C Master (HIE_IPACMSP)
SELECT 'HIE-RC-005', 'Row Count: IMP A/C Master (IPACMSP)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.HIE_IPACMSP
UNION ALL
-- HIE-RC-006 | Row Count: IMP Loan Master (HIE_IPLNMSP)
SELECT 'HIE-RC-006', 'Row Count: IMP Loan Master (IPLNMSP)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.HIE_IPLNMSP
UNION ALL
-- HIE-RC-007 | Row Count: IMP Loan Interest History (HIE_IPLNIHP)
SELECT 'HIE-RC-007', 'Row Count: IMP Loan Interest History (IPLNIHP)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.HIE_IPLNIHP
UNION ALL
-- HIE-RC-008 | Row Count: IMP Bill Master (HIE_IPBLMSP)
SELECT 'HIE-RC-008', 'Row Count: IMP Bill Master (IPBLMSP)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.HIE_IPBLMSP
UNION ALL
-- HIE-RC-009 | Row Count: IMP Bill Interest History (HIE_IPBLIHP)
SELECT 'HIE-RC-009', 'Row Count: IMP Bill Interest History (IPBLIHP)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.HIE_IPBLIHP
UNION ALL
-- HIE-RC-010 | Row Count: EXP A/C Master (HIE_EPACMSP)
SELECT 'HIE-RC-010', 'Row Count: EXP A/C Master (EPACMSP)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.HIE_EPACMSP
UNION ALL
-- HIE-RC-011 | Row Count: EXP DC Master (HIE_EPDCMSP)
SELECT 'HIE-RC-011', 'Row Count: EXP DC Master (EPDCMSP)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.HIE_EPDCMSP
UNION ALL
-- HIE-RC-012 | Row Count: EXP Product DC Control (HIE_EPPDCPP)
SELECT 'HIE-RC-012', 'Row Count: EXP Product DC Control (EPPDCPP)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.HIE_EPPDCPP
UNION ALL
-- HIE-RC-013 | Row Count: IMP Product DC Control (HIE_IPPDCPP)
SELECT 'HIE-RC-013', 'Row Count: IMP Product DC Control (IPPDCPP)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.HIE_IPPDCPP
UNION ALL
-- HIE-RC-014 | Row Count: EXP Bill Master (HIE_EPBLMSP)
SELECT 'HIE-RC-014', 'Row Count: EXP Bill Master (EPBLMSP)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.HIE_EPBLMSP
UNION ALL
-- HIE-RC-015 | Row Count: EXP Bill Interest History (HIE_EPBLIHP)
SELECT 'HIE-RC-015', 'Row Count: EXP Bill Interest History (EPBLIHP)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.HIE_EPBLIHP
UNION ALL
-- HIE-RC-016 | Row Count: BA OMNI Gateway Message History (HIE_BAOMGHP)
SELECT 'HIE-RC-016', 'Row Count: BA OMNI Gateway Message History (BAOMGHP)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.HIE_BAOMGHP
UNION ALL
-- HIE-RC-017 | Row Count: BA OMNI Gateway Message Current (HIE_BAOMGCP)
SELECT 'HIE-RC-017', 'Row Count: BA OMNI Gateway Message Current (BAOMGCP)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.HIE_BAOMGCP
      ) x
    UNION ALL
    SELECT 'CAT-HIE-02 MODE FLAG & SHADOW RECORD VALIDATION' AS dq_category, x.check_id, x.check_name, x.result_num, x.result_txt, x.expected
      FROM (
-- HIE-MF-001 | Mode Flag Distribution — IPDCMSP (IHMDFL)
SELECT 'HIE-MF-001' AS check_id, 'Mode Flag Distribution: IPDCMSP (IHMDFL)' AS check_name,
       COUNT(*) AS RESULT_NUM, NVL(IHMDFL,'[BLANK]') AS RESULT_TXT, CAST(NULL AS NUMBER) AS EXPECTED
  FROM DATACUT3.HIE_IPDCMSP GROUP BY IHMDFL
UNION ALL
-- HIE-MF-002 | Invalid Mode Flag — IPDCMSP
SELECT 'HIE-MF-002', 'Invalid Mode Flag: IPDCMSP',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.HIE_IPDCMSP
 WHERE IHMDFL NOT IN ('P','S') AND IHMDFL IS NOT NULL
UNION ALL
-- HIE-MF-003 | Shadow Record Ratio % — IPDCMSP (INFO)
SELECT 'HIE-MF-003', 'Shadow Record Ratio %: IPDCMSP',
       ROUND(SUM(CASE WHEN IHMDFL='S' THEN 1 ELSE 0 END)*100.0/NULLIF(COUNT(*),0),2),
       CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.HIE_IPDCMSP
UNION ALL
-- HIE-MF-004 | Mode Flag Distribution — IPACMSP (IGMDFL)
SELECT 'HIE-MF-004', 'Mode Flag Distribution: IPACMSP (IGMDFL)',
       COUNT(*), NVL(IGMDFL,'[BLANK]'), CAST(NULL AS NUMBER)
  FROM DATACUT3.HIE_IPACMSP GROUP BY IGMDFL
UNION ALL
-- HIE-MF-005 | Invalid Mode Flag — IPACMSP
SELECT 'HIE-MF-005', 'Invalid Mode Flag: IPACMSP',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.HIE_IPACMSP
 WHERE IGMDFL NOT IN ('P','S') AND IGMDFL IS NOT NULL
UNION ALL
-- HIE-MF-006 | Mode Flag Distribution — IPLNMSP (ILMDFL)
SELECT 'HIE-MF-006', 'Mode Flag Distribution: IPLNMSP (ILMDFL)',
       COUNT(*), NVL(ILMDFL,'[BLANK]'), CAST(NULL AS NUMBER)
  FROM DATACUT3.HIE_IPLNMSP GROUP BY ILMDFL
UNION ALL
-- HIE-MF-007 | Invalid Mode Flag — IPLNMSP
SELECT 'HIE-MF-007', 'Invalid Mode Flag: IPLNMSP',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.HIE_IPLNMSP
 WHERE ILMDFL NOT IN ('P','S') AND ILMDFL IS NOT NULL
UNION ALL
-- HIE-MF-008 | Mode Flag Distribution — IPBLMSP (IIMDFL)
SELECT 'HIE-MF-008', 'Mode Flag Distribution: IPBLMSP (IIMDFL)',
       COUNT(*), NVL(IIMDFL,'[BLANK]'), CAST(NULL AS NUMBER)
  FROM DATACUT3.HIE_IPBLMSP GROUP BY IIMDFL
UNION ALL
-- HIE-MF-009 | Invalid Mode Flag — IPBLMSP
SELECT 'HIE-MF-009', 'Invalid Mode Flag: IPBLMSP',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.HIE_IPBLMSP
 WHERE IIMDFL NOT IN ('P','S') AND IIMDFL IS NOT NULL
UNION ALL
-- HIE-MF-010 | Mode Flag Distribution — EPACMSP (BAMDFL)
SELECT 'HIE-MF-010', 'Mode Flag Distribution: EPACMSP (BAMDFL)',
       COUNT(*), NVL(BAMDFL,'[BLANK]'), CAST(NULL AS NUMBER)
  FROM DATACUT3.HIE_EPACMSP GROUP BY BAMDFL
UNION ALL
-- HIE-MF-011 | Invalid Mode Flag — EPACMSP
SELECT 'HIE-MF-011', 'Invalid Mode Flag: EPACMSP',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.HIE_EPACMSP
 WHERE BAMDFL NOT IN ('P','S') AND BAMDFL IS NOT NULL
UNION ALL
-- HIE-MF-012 | Mode Flag Distribution — EPDCMSP (BCMDFL)
SELECT 'HIE-MF-012', 'Mode Flag Distribution: EPDCMSP (BCMDFL)',
       COUNT(*), NVL(BCMDFL,'[BLANK]'), CAST(NULL AS NUMBER)
  FROM DATACUT3.HIE_EPDCMSP GROUP BY BCMDFL
UNION ALL
-- HIE-MF-013 | Invalid Mode Flag — EPDCMSP
SELECT 'HIE-MF-013', 'Invalid Mode Flag: EPDCMSP',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.HIE_EPDCMSP
 WHERE BCMDFL NOT IN ('P','S') AND BCMDFL IS NOT NULL
UNION ALL
-- HIE-MF-014 | Mode Flag Distribution — EPBLMSP (BBMDFL)
SELECT 'HIE-MF-014', 'Mode Flag Distribution: EPBLMSP (BBMDFL)',
       COUNT(*), NVL(BBMDFL,'[BLANK]'), CAST(NULL AS NUMBER)
  FROM DATACUT3.HIE_EPBLMSP GROUP BY BBMDFL
UNION ALL
-- HIE-MF-015 | Invalid Mode Flag — EPBLMSP
SELECT 'HIE-MF-015', 'Invalid Mode Flag: EPBLMSP',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.HIE_EPBLMSP
 WHERE BBMDFL NOT IN ('P','S') AND BBMDFL IS NOT NULL
UNION ALL
-- HIE-MF-016 | Mode Flag Distribution — BAOMGHP (BMMDFL)
SELECT 'HIE-MF-016', 'Mode Flag Distribution: BAOMGHP (BMMDFL)',
       COUNT(*), NVL(BMMDFL,'[BLANK]'), CAST(NULL AS NUMBER)
  FROM DATACUT3.HIE_BAOMGHP GROUP BY BMMDFL
UNION ALL
-- HIE-MF-017 | Invalid Mode Flag — BAOMGHP
SELECT 'HIE-MF-017', 'Invalid Mode Flag: BAOMGHP',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.HIE_BAOMGHP
 WHERE BMMDFL NOT IN ('P','S') AND BMMDFL IS NOT NULL
UNION ALL
-- HIE-MF-018 | Mode Flag Distribution — EPPDCPP (ABMDFL)
SELECT 'HIE-MF-018', 'Mode Flag Distribution: EPPDCPP (ABMDFL)',
       COUNT(*), NVL(ABMDFL,'[BLANK]'), CAST(NULL AS NUMBER)
  FROM DATACUT3.HIE_EPPDCPP GROUP BY ABMDFL
UNION ALL
-- HIE-MF-019 | Mode Flag Distribution — IPPDCPP (IBMDFL)
SELECT 'HIE-MF-019', 'Mode Flag Distribution: IPPDCPP (IBMDFL)',
       COUNT(*), NVL(IBMDFL,'[BLANK]'), CAST(NULL AS NUMBER)
  FROM DATACUT3.HIE_IPPDCPP GROUP BY IBMDFL
UNION ALL
-- HIE-MF-020 | Mode Flag Distribution — EPCFMSP (GMMDFL)
SELECT 'HIE-MF-020', 'Mode Flag Distribution: EPCFMSP (GMMDFL)',
       COUNT(*), NVL(GMMDFL,'[BLANK]'), CAST(NULL AS NUMBER)
  FROM DATACUT3.HIE_EPCFMSP GROUP BY GMMDFL
UNION ALL
-- HIE-MF-021 | Shadow Record Ratio % — EPDCMSP (INFO)
SELECT 'HIE-MF-021', 'Shadow Record Ratio %: EPDCMSP',
       ROUND(SUM(CASE WHEN BCMDFL='S' THEN 1 ELSE 0 END)*100.0/NULLIF(COUNT(*),0),2),
       CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.HIE_EPDCMSP
UNION ALL
-- HIE-MF-022 | Shadow Record Ratio % — EPBLMSP (INFO)
SELECT 'HIE-MF-022', 'Shadow Record Ratio %: EPBLMSP',
       ROUND(SUM(CASE WHEN BBMDFL='S' THEN 1 ELSE 0 END)*100.0/NULLIF(COUNT(*),0),2),
       CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.HIE_EPBLMSP
      ) x
    UNION ALL
    SELECT 'CAT-HIE-03 MANDATORY FIELDS - NULL/BLANK' AS dq_category, x.check_id, x.check_name, x.result_num, x.result_txt, x.expected
      FROM (
-- HIE-NL-001 | Missing DC Product Type in IMP DC Master (IHDCPT)
SELECT 'HIE-NL-001' AS check_id, 'Missing DC Product Type: IPDCMSP (IHDCPT)' AS check_name,
       COUNT(*) AS RESULT_NUM, CAST(NULL AS VARCHAR2(200)) AS RESULT_TXT, CAST(NULL AS NUMBER) AS EXPECTED
  FROM DATACUT3.HIE_IPDCMSP
 WHERE IHMDFL <> 'S' AND (IHDCPT IS NULL OR TRIM(IHDCPT) = '')
UNION ALL
-- HIE-NL-002 | Missing Expiry Date in IMP DC Master (IHEXDE)
SELECT 'HIE-NL-002', 'Missing Expiry Date: IPDCMSP (IHEXDE)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.HIE_IPDCMSP
 WHERE IHMDFL <> 'S' AND IHEXDE IS NULL
UNION ALL
-- HIE-NL-003 | Missing Product Currency in IMP DC Master (IHPRCY)
SELECT 'HIE-NL-003', 'Missing Product Currency: IPDCMSP (IHPRCY)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.HIE_IPDCMSP
 WHERE IHMDFL <> 'S' AND (IHPRCY IS NULL OR TRIM(IHPRCY) = '')
UNION ALL
-- HIE-NL-004 | Missing A/C Short Name in IMP A/C Master (IGACSN)
SELECT 'HIE-NL-004', 'Missing A/C Short Name: IPACMSP (IGACSN)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.HIE_IPACMSP
 WHERE IGMDFL <> 'S' AND (IGACSN IS NULL OR TRIM(IGACSN) = '')
UNION ALL
-- HIE-NL-005 | Missing Status in IMP A/C Master (IGSTUS)
SELECT 'HIE-NL-005', 'Missing A/C Status: IPACMSP (IGSTUS)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.HIE_IPACMSP
 WHERE IGMDFL <> 'S' AND (IGSTUS IS NULL OR TRIM(IGSTUS) = '')
UNION ALL
-- HIE-NL-006 | Missing Product Currency in IMP Loan (ILPRCY)
SELECT 'HIE-NL-006', 'Missing Product Currency: IPLNMSP (ILPRCY)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.HIE_IPLNMSP
 WHERE ILMDFL <> 'S' AND (ILPRCY IS NULL OR TRIM(ILPRCY) = '')
UNION ALL
-- HIE-NL-007 | Missing Loan Amount in IMP Loan (ILLNAA = 0 or NULL)
SELECT 'HIE-NL-007', 'Missing/Zero Loan Amount: IPLNMSP (ILLNAA)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.HIE_IPLNMSP
 WHERE ILMDFL <> 'S' AND (ILLNAA IS NULL OR ILLNAA = 0)
UNION ALL
-- HIE-NL-008 | Missing Bill Number in IMP Bill Master (IIBLNO)
SELECT 'HIE-NL-008', 'Missing Bill Number: IPBLMSP (IIBLNO)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.HIE_IPBLMSP
 WHERE IIMDFL <> 'S' AND (IIBLNO IS NULL OR TRIM(IIBLNO) = '')
UNION ALL
-- HIE-NL-009 | Missing Product Currency in IMP Bill (IIPRCY)
SELECT 'HIE-NL-009', 'Missing Product Currency: IPBLMSP (IIPRCY)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.HIE_IPBLMSP
 WHERE IIMDFL <> 'S' AND (IIPRCY IS NULL OR TRIM(IIPRCY) = '')
UNION ALL
-- HIE-NL-010 | Missing Exports DC Number in EXP DC Master (BCDCNR)
SELECT 'HIE-NL-010', 'Missing Exports DC Number: EPDCMSP (BCDCNR)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.HIE_EPDCMSP
 WHERE BCMDFL <> 'S' AND (BCDCNR IS NULL OR TRIM(BCDCNR) = '')
UNION ALL
-- HIE-NL-011 | Missing Product Currency in EXP DC Master (BCPRCY)
SELECT 'HIE-NL-011', 'Missing Product Currency: EPDCMSP (BCPRCY)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.HIE_EPDCMSP
 WHERE BCMDFL <> 'S' AND (BCPRCY IS NULL OR TRIM(BCPRCY) = '')
UNION ALL
-- HIE-NL-012 | Missing A/C Short Name in EXP A/C Master (BAACSN)
SELECT 'HIE-NL-012', 'Missing A/C Short Name: EPACMSP (BAACSN)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.HIE_EPACMSP
 WHERE BAMDFL <> 'S' AND (BAACSN IS NULL OR TRIM(BAACSN) = '')
UNION ALL
-- HIE-NL-013 | Missing Bill Number in EXP Bill Master (BBBLNO)
SELECT 'HIE-NL-013', 'Missing Bill Number: EPBLMSP (BBBLNO)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.HIE_EPBLMSP
 WHERE BBMDFL <> 'S' AND (BBBLNO IS NULL OR TRIM(BBBLNO) = '')
UNION ALL
-- HIE-NL-014 | Missing Remittance Amount in OMNI Gateway (BMRAMT = 0 or NULL)
SELECT 'HIE-NL-014', 'Missing/Zero Remittance Amount: BAOMGHP (BMRAMT)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.HIE_BAOMGHP
 WHERE BMMDFL <> 'S' AND (BMRAMT IS NULL OR BMRAMT = 0)
UNION ALL
-- HIE-NL-015 | Missing Remittance Currency in OMNI Gateway (BMRCCY)
SELECT 'HIE-NL-015', 'Missing Remittance Currency: BAOMGHP (BMRCCY)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.HIE_BAOMGHP
 WHERE BMMDFL <> 'S' AND (BMRCCY IS NULL OR TRIM(BMRCCY) = '')
      ) x
    UNION ALL
    SELECT 'CAT-HIE-04 DATE FIELD VALIDITY' AS dq_category, x.check_id, x.check_name, x.result_num, x.result_txt, x.expected
      FROM (
-- HIE-DT-001 | Invalid/Zero DC Expiry Date — IPDCMSP (IHEXDE)
SELECT 'HIE-DT-001' AS check_id, 'Invalid/Zero DC Expiry Date: IPDCMSP (IHEXDE)' AS check_name,
       CAST(COUNT(*) AS NUMBER) AS RESULT_NUM, CAST(NULL AS VARCHAR2(200)) AS RESULT_TXT, CAST(NULL AS NUMBER) AS EXPECTED
  FROM DATACUT3.HIE_IPDCMSP
 WHERE IHMDFL <> 'S'
   AND (IHEXDE IS NULL
        OR TO_CHAR(IHEXDE,'YYYYMMDD') NOT BETWEEN '19000101' AND '20991231')
UNION ALL
-- HIE-DT-002 | IMP DC Expiry Date Before Issue Date (IHEXDE < IHDISS)
SELECT 'HIE-DT-002', 'IMP DC Expiry Date Before Issue Date: IPDCMSP',
       CAST(COUNT(*) AS NUMBER), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.HIE_IPDCMSP
 WHERE IHMDFL <> 'S' AND IHEXDE IS NOT NULL AND IHDISS IS NOT NULL 
   AND TO_CHAR(IHEXDE, 'YYYYMMDD') < TO_CHAR(IHDISS, 'YYYYMMDD')
UNION ALL
-- HIE-DT-003 | Invalid/Zero Loan Due Date — IPLNMSP (ILDUDT)
SELECT 'HIE-DT-003', 'Invalid/Zero Loan Due Date: IPLNMSP (ILDUDT)',
       CAST(COUNT(*) AS NUMBER), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.HIE_IPLNMSP
 WHERE ILMDFL <> 'S' AND (ILDUDT IS NULL OR TO_CHAR(ILDUDT) = '0')
UNION ALL
-- HIE-DT-004 | Past Due Active Loans — IPLNMSP (ILDUDT < DATE '2026-06-15', non-closed)
SELECT 'HIE-DT-004', 'Past Due Active Loan (ILDUDT in Past): IPLNMSP',
       CAST(COUNT(*) AS NUMBER), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.HIE_IPLNMSP
 WHERE ILMDFL <> 'S'
   AND NVL(ILSTAT,'X') NOT IN ('D','F')
   AND ILDUDT IS NOT NULL
   AND TO_CHAR(ILDUDT,'YYYYMMDD') < TO_CHAR(DATE '2026-06-15','YYYYMMDD')
UNION ALL
-- HIE-DT-005 | Invalid/Zero Bill Due Date — IPBLMSP (IIDUDT)
SELECT 'HIE-DT-005', 'Invalid/Zero Bill Due Date: IPBLMSP (IIDUDT)',
       CAST(COUNT(*) AS NUMBER), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.HIE_IPBLMSP
 WHERE IIMDFL <> 'S' AND (IIDUDT IS NULL OR TO_CHAR(IIDUDT) = '0')
UNION ALL
-- HIE-DT-006 | IMP A/C Date Opened Invalid — IPACMSP (IGDTAO)
SELECT 'HIE-DT-006', 'Invalid IMP A/C Date Opened: IPACMSP (IGDTAO)',
       CAST(COUNT(*) AS NUMBER), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.HIE_IPACMSP
 WHERE IGMDFL <> 'S'
   AND (IGDTAO IS NULL
        OR TO_CHAR(IGDTAO,'YYYYMMDD') NOT BETWEEN '19000101' AND '20991231')
UNION ALL
-- HIE-DT-007 | EXP DC — Expiry Date field TBD (EPDCMSP)
SELECT 'HIE-DT-007', 'EXP DC Expiry Date Field Pending Confirmation (EPDCMSP) [TODO]',
       CAST(COUNT(*) AS NUMBER), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.HIE_EPDCMSP
 WHERE BCMDFL <> 'S'
UNION ALL
-- HIE-DT-008 | EXP Bill Due Date Invalid — EPBLMSP (BBDUDT)
SELECT 'HIE-DT-008', 'Invalid/Zero EXP Bill Due Date: EPBLMSP (BBDUDT)',
       CAST(COUNT(*) AS NUMBER), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.HIE_EPBLMSP
 WHERE BBMDFL <> 'S' AND (BBDUDT IS NULL OR TO_CHAR(BBDUDT) = '0')
UNION ALL
-- HIE-DT-009 | OMNI Gateway Message Without Transmission Date (BMXMDT)
SELECT 'HIE-DT-009', 'Missing Transmission Date: BAOMGHP (BMXMDT)',
       CAST(COUNT(*) AS NUMBER), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.HIE_BAOMGHP
 WHERE BMMDFL <> 'S' AND BMXMDT IS NULL
UNION ALL
-- HIE-DT-010 | OMNI Gateway Message Without Value Date (BMVLDT)
SELECT 'HIE-DT-010', 'Missing Value Date: BAOMGHP (BMVLDT)',
       CAST(COUNT(*) AS NUMBER), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.HIE_BAOMGHP
 WHERE BMMDFL <> 'S' AND BMVLDT IS NULL
UNION ALL
-- HIE-DT-011 | IMP Loan Next Instalment Date in Past (ILNISD < DATE '2026-06-15')
SELECT 'HIE-DT-011', 'Next Instalment Date in Past: IPLNMSP (ILNISD)',
       CAST(COUNT(*) AS NUMBER), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.HIE_IPLNMSP
 WHERE ILMDFL <> 'S'
   AND ILNISD IS NOT NULL
   AND TO_CHAR(ILNISD,'YYYYMMDD') < TO_CHAR(DATE '2026-06-15','YYYYMMDD')
UNION ALL
-- HIE-DT-012 | EXP A/C Date Opened Invalid — EPACMSP (BADTAO)
SELECT 'HIE-DT-012', 'Invalid EXP A/C Date Opened: EPACMSP (BADTAO)',
       CAST(COUNT(*) AS NUMBER), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.HIE_EPACMSP
 WHERE BAMDFL <> 'S'
   AND BADTAO IS NULL
      ) x
    UNION ALL
    SELECT 'CAT-HIE-05 NUMERIC INTEGRITY' AS dq_category, x.check_id, x.check_name, x.result_num, x.result_txt, x.expected
      FROM (
-- HIE-NI-001 | Negative DC Amount Outstanding — IPDCMSP (IHDCAO < 0)
SELECT 'HIE-NI-001' AS check_id, 'Negative DC Amount Outstanding: IPDCMSP (IHDCAO)' AS check_name,
       COUNT(*) AS RESULT_NUM, CAST(NULL AS VARCHAR2(200)) AS RESULT_TXT, CAST(NULL AS NUMBER) AS EXPECTED
  FROM DATACUT3.HIE_IPDCMSP
 WHERE IHMDFL <> 'S' AND IHDCAO < 0
UNION ALL
-- HIE-NI-002 | Negative LCY Ledger Balance — IPDCMSP (IHLLBL < 0)
SELECT 'HIE-NI-002', 'Negative LCY Ledger Balance: IPDCMSP (IHLLBL)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.HIE_IPDCMSP
 WHERE IHMDFL <> 'S' AND IHLLBL < 0
UNION ALL
-- HIE-NI-003 | DC Amount Utilised > DC Amount Applied — IPDCMSP
SELECT 'HIE-NI-003', 'DC Amount Utilised Exceeds DC Amount Applied: IPDCMSP',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.HIE_IPDCMSP
 WHERE IHMDFL <> 'S' AND IHDCAU > IHDCAA AND IHDCAA > 0
UNION ALL
-- HIE-NI-004 | Negative Bill Amount Outstanding — IPBLMSP (IIBLAO < 0)
SELECT 'HIE-NI-004', 'Negative Bill Amount Outstanding: IPBLMSP (IIBLAO)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.HIE_IPBLMSP
 WHERE IIMDFL <> 'S' AND IIBLAO < 0
UNION ALL
-- HIE-NI-005 | IMP Bill Amount Outstanding > Bill Amount Applied
SELECT 'HIE-NI-005', 'IMP Bill O/S Exceeds Bill Amount Applied: IPBLMSP',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.HIE_IPBLMSP
 WHERE IIMDFL <> 'S' AND IIBLAO > IIBLAA AND IIBLAA > 0
UNION ALL
-- HIE-NI-006 | Negative Loan Amount Outstanding — IPLNMSP (ILLNAO < 0)
-- ANALYSIS: HIE equivalent of OI-001. Flag as potential STOPPER if >50%.
SELECT 'HIE-NI-006', 'Negative Loan Amount Outstanding: IPLNMSP (ILLNAO)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.HIE_IPLNMSP
 WHERE ILMDFL <> 'S' AND ILLNAO < 0
UNION ALL
-- HIE-NI-007 | Negative EXP DC Amount Outstanding — EPDCMSP (BCDCAO < 0)
SELECT 'HIE-NI-007', 'Negative EXP DC Amount Outstanding: EPDCMSP (BCDCAO)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.HIE_EPDCMSP
 WHERE BCMDFL <> 'S' AND BCDCAO < 0
UNION ALL
-- HIE-NI-008 | Negative EXP Bill Amount Outstanding — EPBLMSP (BBBLAO < 0)
SELECT 'HIE-NI-008', 'Negative EXP Bill Amount Outstanding: EPBLMSP (BBBLAO)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.HIE_EPBLMSP
 WHERE BBMDFL <> 'S' AND BBBLAO < 0
UNION ALL
-- HIE-NI-009 | IMP DC with Zero Outstanding but Not Closed (INFO — distribution)
SELECT 'HIE-NI-009', 'IMP DC Zero Outstanding Not-Closed Status Distribution: IPDCMSP',
       COUNT(*), NVL(IHSTAT,'NULL'), CAST(NULL AS NUMBER)
  FROM DATACUT3.HIE_IPDCMSP
 WHERE IHMDFL <> 'S' AND IHDCAO = 0 AND NVL(IHSTAT,'X') NOT IN ('D','F','C')
 GROUP BY IHSTAT
UNION ALL
-- HIE-NI-010 | OMNI Gateway Remittance Amount Zero or Negative (BMRAMT <= 0)
SELECT 'HIE-NI-010', 'OMNI Gateway Remittance Amount Zero or Negative: BAOMGHP',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.HIE_BAOMGHP
 WHERE BMMDFL <> 'S' AND (BMRAMT IS NULL OR BMRAMT <= 0)
      ) x
    UNION ALL
    SELECT 'CAT-HIE-06 DC / LOAN / BILL DOMAIN CHECKS' AS dq_category, x.check_id, x.check_name, x.result_num, x.result_txt, x.expected
      FROM (
-- HIE-DM-001 | IMP DC Item Status Distribution (INFO)
SELECT 'HIE-DM-001' AS check_id, 'IMP DC Item Status Distribution: IPDCMSP' AS check_name,
       COUNT(*) AS RESULT_NUM, NVL(IHSTAT,'[NULL]') AS RESULT_TXT, CAST(NULL AS NUMBER) AS EXPECTED
  FROM DATACUT3.HIE_IPDCMSP WHERE IHMDFL <> 'S' GROUP BY IHSTAT
UNION ALL
-- HIE-DM-002 | EXP DC Item Status Distribution (INFO)
SELECT 'HIE-DM-002', 'EXP DC Item Status Distribution: EPDCMSP',
       COUNT(*), NVL(BCSTAT,'[NULL]'), CAST(NULL AS NUMBER)
  FROM DATACUT3.HIE_EPDCMSP WHERE BCMDFL <> 'S' GROUP BY BCSTAT
UNION ALL
-- HIE-DM-003 | IMP DC Product Type Distribution (INFO)
SELECT 'HIE-DM-003', 'IMP DC Product Type Distribution: IPDCMSP',
       COUNT(*), NVL(IHDCPT,'[NULL]'), CAST(NULL AS NUMBER)
  FROM DATACUT3.HIE_IPDCMSP WHERE IHMDFL <> 'S' GROUP BY IHDCPT
UNION ALL
-- HIE-DM-004 | IMP DC Currency Distribution with Total Outstanding (INFO)
SELECT 'HIE-DM-004', 'IMP DC Currency Distribution + Total O/S: IPDCMSP',
       COUNT(*), IHPRCY || ' [O/S=' || TO_CHAR(SUM(IHDCAO)/100,'FM999,999,999') || ']',
       CAST(NULL AS NUMBER)
  FROM DATACUT3.HIE_IPDCMSP
 WHERE IHMDFL <> 'S' AND IHDCAO > 0 GROUP BY IHPRCY
UNION ALL
-- HIE-DM-005 | IMP A/C Status Distribution (INFO)
SELECT 'HIE-DM-005', 'IMP A/C Status Distribution: IPACMSP',
       COUNT(*), NVL(IGSTUS,'[NULL]'), CAST(NULL AS NUMBER)
  FROM DATACUT3.HIE_IPACMSP WHERE IGMDFL <> 'S' GROUP BY IGSTUS
UNION ALL
-- HIE-DM-006 | IMP Loan Maturity Code Distribution (INFO)
SELECT 'HIE-DM-006', 'IMP Loan Maturity Code Distribution: IPLNMSP',
       COUNT(*), NVL(ILMTCD,'[NULL]'), CAST(NULL AS NUMBER)
  FROM DATACUT3.HIE_IPLNMSP WHERE ILMDFL <> 'S' GROUP BY ILMTCD
UNION ALL
-- HIE-DM-007 | IMP Loan Currency Distribution + Total Outstanding (INFO)
SELECT 'HIE-DM-007', 'IMP Loan Currency Distribution + Total O/S: IPLNMSP',
       COUNT(*), ILPRCY || ' [O/S=' || TO_CHAR(SUM(ILLNAO)/100,'FM999,999,999') || ']',
       CAST(NULL AS NUMBER)
  FROM DATACUT3.HIE_IPLNMSP WHERE ILMDFL <> 'S' GROUP BY ILPRCY
UNION ALL
-- HIE-DM-008 | IMP Bill Item Status Distribution (INFO)
SELECT 'HIE-DM-008', 'IMP Bill Item Status Distribution: IPBLMSP',
       COUNT(*), NVL(IISTAT,'[NULL]'), CAST(NULL AS NUMBER)
  FROM DATACUT3.HIE_IPBLMSP WHERE IIMDFL <> 'S' GROUP BY IISTAT
UNION ALL
-- HIE-DM-009 | EXP Bill Item Status Distribution (INFO)
SELECT 'HIE-DM-009', 'EXP Bill Item Status Distribution: EPBLMSP',
       COUNT(*), NVL(BBSTAT,'[NULL]'), CAST(NULL AS NUMBER)
  FROM DATACUT3.HIE_EPBLMSP WHERE BBMDFL <> 'S' GROUP BY BBSTAT
UNION ALL
-- HIE-DM-010 | EXP Bill Trade Term Distribution (INFO)
SELECT 'HIE-DM-010', 'EXP Bill Trade Term Distribution: EPBLMSP',
       COUNT(*), NVL(BBTDTM,'[NULL]'), CAST(NULL AS NUMBER)
  FROM DATACUT3.HIE_EPBLMSP WHERE BBMDFL <> 'S' GROUP BY BBTDTM
UNION ALL
-- HIE-DM-011 | IMP DC Zero Outstanding but Active — count (FAIL if > 0)
SELECT 'HIE-DM-011', 'IMP DC Zero Outstanding but Active Status: IPDCMSP',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.HIE_IPDCMSP
 WHERE IHMDFL <> 'S' AND IHDCAO = 0 AND NVL(IHSTAT,'X') NOT IN ('D','F','C')
UNION ALL
-- HIE-DM-012 | EXP DC Zero Outstanding but Active — count (FAIL if > 0)
SELECT 'HIE-DM-012', 'EXP DC Zero Outstanding but Active Status: EPDCMSP',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.HIE_EPDCMSP
 WHERE BCMDFL <> 'S' AND BCDCAO = 0 AND NVL(BCSTAT,'X') NOT IN ('D','F','C')
UNION ALL
-- HIE-DM-013 | IMP Loan Zero Outstanding but Active — count (FAIL if > 0)
SELECT 'HIE-DM-013', 'IMP Loan Zero Outstanding but Active: IPLNMSP',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.HIE_IPLNMSP
 WHERE ILMDFL <> 'S' AND ILLNAO = 0 AND NVL(ILSTAT,'X') NOT IN ('D','F')
UNION ALL
-- HIE-DM-014 | OMNI Gateway Message Status Distribution (INFO)
SELECT 'HIE-DM-014', 'OMNI Gateway Message Status Distribution: BAOMGHP',
       COUNT(*), NVL(BMMSTS,'[NULL]'), CAST(NULL AS NUMBER)
  FROM DATACUT3.HIE_BAOMGHP WHERE BMMDFL <> 'S' GROUP BY BMMSTS
UNION ALL
-- HIE-DM-015 | EXP Product Control — Product Types (INFO)
SELECT 'HIE-DM-015', 'EXP Product Control Types: EPPDCPP',
       COUNT(*), NVL(ABAPTY,'[NULL]') || ' - ' || NVL(ABDS20,''), CAST(NULL AS NUMBER)
  FROM DATACUT3.HIE_EPPDCPP WHERE ABMDFL <> 'S' GROUP BY ABAPTY, ABDS20
UNION ALL
-- HIE-DM-016 | EXP A/C Status Distribution — EPACMSP (BASTUS) — INFO
-- NOTE: BASTUS confirmed from ALL_TAB_COLUMNS (VARCHAR2 4); field name differs from IPACMSP (IGSTUS)
SELECT 'HIE-DM-016' AS check_id, 'EXP A/C Status Distribution: EPACMSP (BASTUS)' AS check_name,
       COUNT(*) AS RESULT_NUM, NVL(BASTUS,'[NULL]') AS RESULT_TXT, CAST(NULL AS NUMBER) AS EXPECTED
  FROM DATACUT3.HIE_EPACMSP WHERE BAMDFL <> 'S' GROUP BY BASTUS
      ) x
    UNION ALL
    SELECT 'CAT-HIE-07 REFERENTIAL INTEGRITY - HIE -> HUB' AS dq_category, x.check_id, x.check_name, x.result_num, x.result_txt, x.expected
      FROM (
-- HIE-RI-001 | IMP DC Account Not in HUB DD Account Master
-- ANALYSIS: IMP DC IHACB/IHACS/IHACX must link to HUB_MT_DDACMSP DFACB/DFACS/DFACX.
SELECT 'HIE-RI-001' AS check_id, 'IMP DC Account Not in HUB DD Account Master' AS check_name,
       COUNT(*) AS RESULT_NUM, CAST(NULL AS VARCHAR2(200)) AS RESULT_TXT, CAST(NULL AS NUMBER) AS EXPECTED
  FROM DATACUT3.HIE_IPDCMSP H
 WHERE H.IHMDFL <> 'S' AND H.IHACB IS NOT NULL
   AND NOT EXISTS (SELECT 1 FROM DATACUT3.HUB_MT_DDACMSP D
                   WHERE D.DFACB = H.IHACB AND D.DFACS = H.IHACS AND D.DFACX = H.IHACX)
UNION ALL
-- HIE-RI-002 | IMP Loan Account Not in HUB DD Account Master
SELECT 'HIE-RI-002', 'IMP Loan Account Not in HUB DD Account Master',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.HIE_IPLNMSP L
 WHERE L.ILMDFL <> 'S' AND L.ILACB IS NOT NULL
   AND NOT EXISTS (SELECT 1 FROM DATACUT3.HUB_MT_DDACMSP D
                   WHERE D.DFACB = L.ILACB AND D.DFACS = L.ILACS AND D.DFACX = L.ILACX)
UNION ALL
-- HIE-RI-003 | IMP Bill Account Not in HUB DD Account Master
SELECT 'HIE-RI-003', 'IMP Bill Account Not in HUB DD Account Master',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.HIE_IPBLMSP B
 WHERE B.IIMDFL <> 'S' AND B.IIACB IS NOT NULL
   AND NOT EXISTS (SELECT 1 FROM DATACUT3.HUB_MT_DDACMSP D
                   WHERE D.DFACB = B.IIACB AND D.DFACS = B.IIACS AND D.DFACX = B.IIACX)
UNION ALL
-- HIE-RI-004 | EXP DC Account Not in HUB DD Account Master
SELECT 'HIE-RI-004', 'EXP DC Account Not in HUB DD Account Master',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.HIE_EPDCMSP E
 WHERE E.BCMDFL <> 'S' AND E.BCACB IS NOT NULL
   AND NOT EXISTS (SELECT 1 FROM DATACUT3.HUB_MT_DDACMSP D
                   WHERE D.DFACB = E.BCACB AND D.DFACS = E.BCACS AND D.DFACX = E.BCACX)
UNION ALL
-- HIE-RI-005 | EXP Bill Account Not in HUB DD Account Master
SELECT 'HIE-RI-005', 'EXP Bill Account Not in HUB DD Account Master',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.HIE_EPBLMSP B
 WHERE B.BBMDFL <> 'S' AND B.BBACB IS NOT NULL
   AND NOT EXISTS (SELECT 1 FROM DATACUT3.HUB_MT_DDACMSP D
                   WHERE D.DFACB = B.BBACB AND D.DFACS = B.BBACS AND D.DFACX = B.BBACX)
UNION ALL
-- HIE-RI-006 | IMP A/C Customer Not in HUB Customer Master
SELECT 'HIE-RI-006', 'IMP A/C Customer Not in HUB Customer Master',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.HIE_IPACMSP A
 WHERE A.IGMDFL <> 'S' AND A.IGDCB IS NOT NULL
   AND NOT EXISTS (SELECT 1 FROM DATACUT3.HUB_MT_SSCUSTP C
                   WHERE C.ZGDCB = A.IGDCB AND C.ZGDCS = A.IGDCS)
UNION ALL
-- HIE-RI-007 | EXP A/C Customer Not in HUB Customer Master
SELECT 'HIE-RI-007', 'EXP A/C Customer Not in HUB Customer Master',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.HIE_EPACMSP A
 WHERE A.BAMDFL <> 'S' AND A.BADCB IS NOT NULL
   AND NOT EXISTS (SELECT 1 FROM DATACUT3.HUB_MT_SSCUSTP C
                   WHERE C.ZGDCB = A.BADCB AND C.ZGDCS = A.BADCS)
UNION ALL
-- HIE-RI-008 | IMP DC vs EXP DC Count Symmetry (INFO)
SELECT 'HIE-RI-008', 'IMP/EXP DC Count Symmetry Check',
       COUNT(*), 'IMP_DC', CAST(NULL AS NUMBER)
  FROM DATACUT3.HIE_IPDCMSP WHERE IHMDFL <> 'S'
UNION ALL
SELECT 'HIE-RI-008', 'IMP/EXP DC Count Symmetry Check',
       COUNT(*), 'EXP_DC', CAST(NULL AS NUMBER)
  FROM DATACUT3.HIE_EPDCMSP WHERE BCMDFL <> 'S'
      ) x
    UNION ALL
    SELECT 'CAT-HIE-08 DUPLICATE DETECTION' AS dq_category, x.check_id, x.check_name, x.result_num, x.result_txt, x.expected
      FROM (
-- HIE-DU-001 | Duplicate IMP DC Records (IHDCPT + IHBRAB + IHDCNO)
SELECT 'HIE-DU-001' AS check_id, 'Duplicate IMP DC Records: IPDCMSP (IHDCPT+IHBRAB+IHDCNO)' AS check_name,
       COUNT(*) AS RESULT_NUM, CAST(NULL AS VARCHAR2(200)) AS RESULT_TXT, CAST(NULL AS NUMBER) AS EXPECTED
  FROM (SELECT IHDCPT, IHBRAB, IHDCNO, COUNT(*) AS cnt
          FROM DATACUT3.HIE_IPDCMSP WHERE IHMDFL <> 'S'
         GROUP BY IHDCPT, IHBRAB, IHDCNO HAVING COUNT(*) > 1)
UNION ALL
-- HIE-DU-002 | Duplicate IMP A/C Records (IGACB + IGACS + IGACX)
SELECT 'HIE-DU-002', 'Duplicate IMP A/C Records: IPACMSP (IGACB+IGACS+IGACX)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM (SELECT IGACB, IGACS, IGACX, COUNT(*) AS cnt
          FROM DATACUT3.HIE_IPACMSP WHERE IGMDFL <> 'S'
         GROUP BY IGACB, IGACS, IGACX HAVING COUNT(*) > 1)
UNION ALL
-- HIE-DU-003 | Duplicate IMP Loan Records (ILACB + ILACS + ILACX + ILAPTY)
SELECT 'HIE-DU-003', 'Duplicate IMP Loan Records: IPLNMSP (ILACB+ILACS+ILACX+ILAPTY)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM (SELECT ILACB, ILACS, ILACX, ILAPTY, COUNT(*) AS cnt
          FROM DATACUT3.HIE_IPLNMSP WHERE ILMDFL <> 'S'
         GROUP BY ILACB, ILACS, ILACX, ILAPTY HAVING COUNT(*) > 1)
UNION ALL
-- HIE-DU-004 | Duplicate IMP Bill Records (IIACB + IIACS + IIACX + IIBLNO)
SELECT 'HIE-DU-004', 'Duplicate IMP Bill Records: IPBLMSP (IIACB+IIACS+IIACX+IIBLNO)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM (SELECT IIACB, IIACS, IIACX, IIBLNO, COUNT(*) AS cnt
          FROM DATACUT3.HIE_IPBLMSP WHERE IIMDFL <> 'S'
         GROUP BY IIACB, IIACS, IIACX, IIBLNO HAVING COUNT(*) > 1)
UNION ALL
-- HIE-DU-005 | Duplicate EXP DC Records (BCDCNR + BCDCSR)
SELECT 'HIE-DU-005', 'Duplicate EXP DC Records: EPDCMSP (BCDCNR+BCDCSR)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM (SELECT BCDCNR, BCDCSR, COUNT(*) AS cnt
          FROM DATACUT3.HIE_EPDCMSP WHERE BCMDFL <> 'S'
         GROUP BY BCDCNR, BCDCSR HAVING COUNT(*) > 1)
UNION ALL
-- HIE-DU-006 | Duplicate EXP A/C Records (BAACB + BAACS + BAACX)
SELECT 'HIE-DU-006', 'Duplicate EXP A/C Records: EPACMSP (BAACB+BAACS+BAACX)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM (SELECT BAACB, BAACS, BAACX, COUNT(*) AS cnt
          FROM DATACUT3.HIE_EPACMSP WHERE BAMDFL <> 'S'
         GROUP BY BAACB, BAACS, BAACX HAVING COUNT(*) > 1)
      ) x
) y
ORDER BY y.dq_category, y.check_id;