SELECT
    CAST('ME36_TREATS' AS NVARCHAR2(50))       AS DQ_TYPE,
    CAST(y.dq_category AS NVARCHAR2(100))       AS DQ_CATEGORY,
    CAST(y.check_name  AS NVARCHAR2(200))      AS CHECK_NAME,
    CAST(NULL AS NVARCHAR2(100))               AS TABLE_NAME,
    CAST(NULL AS NUMBER)                       AS FAILED_RECORDS,
    CAST(y.result_num AS NUMBER)               AS TOTAL_RECORDS,
    CAST(NULL AS NUMBER)                       AS FAILURE_PCT,
    CAST(y.check_id AS NVARCHAR2(20))          AS CHECK_ID,
    CAST(y.result_num AS NUMBER(20,2))         AS RESULT_NUM,
    CAST(y.result_txt AS NVARCHAR2(1000))       AS RESULT_TXT,
    CAST(y.expected AS NUMBER(20,2))           AS EXPECTED,
    CAST(
        CASE
            WHEN y.expected IS NOT NULL
              THEN CASE WHEN ABS(y.result_num - y.expected) * 100.0 / NULLIF(y.expected, 0) <= 0.1
                        THEN 'PASS' ELSE 'REVIEW' END
            WHEN y.result_txt IS NULL
              THEN CASE WHEN y.result_num = 0 THEN 'PASS' ELSE 'FAIL' END
            ELSE 'INFO'
        END AS NVARCHAR2(20)
    ) AS DQ_STATUS
FROM (
    SELECT 'CAT-TR-01 VOLUME RECONCILIATION' AS dq_category, x.check_id, x.check_name, x.result_num, x.result_txt, x.expected
      FROM (
-- TR-RC-001 | Row Count: FX Spot Deals (TREATS_MPESPTP)
SELECT 'TR-RC-001' AS check_id, 'Row Count: FX Spot Deals (MPESPTP)' AS check_name,
       COUNT(*) AS RESULT_NUM, CAST(NULL AS VARCHAR2(200)) AS RESULT_TXT, 21 AS EXPECTED
  FROM DATACUT3.TREATS_MPESPTP
UNION ALL
-- TR-RC-002 | Row Count: FX Forward Deals (TREATS_MPEFWDP)
SELECT 'TR-RC-002', 'Row Count: FX Forward Deals (MPEFWDP)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), 217
  FROM DATACUT3.TREATS_MPEFWDP
UNION ALL
-- TR-RC-003 | Row Count: MM/Cash Deposit Deals (TREATS_MPMZCPP)
SELECT 'TR-RC-003', 'Row Count: MM/Cash Deposit Deals (MPMZCPP)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), 7197
  FROM DATACUT3.TREATS_MPMZCPP
UNION ALL
-- TR-RC-004 | Row Count: Product Control Table (TREATS_TTPDCTP)
SELECT 'TR-RC-004', 'Row Count: Product Control Table (TTPDCTP)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), 438
  FROM DATACUT3.TREATS_TTPDCTP
UNION ALL
-- TR-RC-005 | Row Count: MM Deposit Additional (TREATS_MPMMCPP)
SELECT 'TR-RC-005', 'Row Count: MM Deposit Additional (MPMMCPP)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), 36
  FROM DATACUT3.TREATS_MPMMCPP
UNION ALL
-- TR-RC-006 | Row Count: Swap Schedule Cashflow (TREATS_MPSWSCP)
SELECT 'TR-RC-006', 'Row Count: Swap Schedule Cashflow (MPSWSCP)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), 3133
  FROM DATACUT3.TREATS_MPSWSCP
UNION ALL
-- TR-RC-007 | Row Count: Settlement Deal SI (TREATS_SEDLSIP)
SELECT 'TR-RC-007', 'Row Count: Settlement Deal SI (SEDLSIP)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), 265
  FROM DATACUT3.TREATS_SEDLSIP
UNION ALL
-- TR-RC-008 | Row Count: Settlement Counterparty SI (TREATS_SECPSIP)
SELECT 'TR-RC-008', 'Row Count: Settlement Counterparty SI (SECPSIP)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), 315
  FROM DATACUT3.TREATS_SECPSIP
UNION ALL
-- TR-RC-009 | Row Count: Interest Rate Swap Master (TREATS_MPMSWPP)
SELECT 'TR-RC-009', 'Row Count: Interest Rate Swap Master (MPMSWPP)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), 23
  FROM DATACUT3.TREATS_MPMSWPP
UNION ALL
-- TR-RC-010 | Row Count: Counterparty ERDS Profile (TREATS_TTCPEPP)
SELECT 'TR-RC-010', 'Row Count: Counterparty ERDS Profile (TTCPEPP)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), 130
  FROM DATACUT3.TREATS_TTCPEPP
UNION ALL
-- TR-RC-011 | Row Count: Counterparty Address Details (TREATS_TTCPADP)
SELECT 'TR-RC-011', 'Row Count: Counterparty Address Details (TTCPADP)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), 135
  FROM DATACUT3.TREATS_TTCPADP
UNION ALL
-- TR-RC-012 | Row Count: NI/Bond/Repo/Securities Deals (TREATS_MPMNMCP)
SELECT 'TR-RC-012', 'Row Count: NI/Bond/Repo/Securities Deals (MPMNMCP)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), 244
  FROM DATACUT3.TREATS_MPMNMCP
UNION ALL
-- TR-RC-013 | Row Count: Security Master (TREATS_ISNMMSP)
SELECT 'TR-RC-013', 'Row Count: Security Master (ISNMMSP)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), 111
  FROM DATACUT3.TREATS_ISNMMSP
UNION ALL
-- TR-RC-014 | Row Count: Security NML Line Position (TREATS_MMNMLNP)
SELECT 'TR-RC-014', 'Row Count: Security NML Line Position (MMNMLNP)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), 121
  FROM DATACUT3.TREATS_MMNMLNP
UNION ALL
-- TR-RC-015 | Row Count: Security Coupon Schedule (TREATS_ISCPSCP)
SELECT 'TR-RC-015', 'Row Count: Security Coupon Schedule (ISCPSCP)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), 689
  FROM DATACUT3.TREATS_ISCPSCP
UNION ALL
-- TR-RC-016 | Row Count: Security Master Position Cross-Ref (TREATS_ISNMPCP)
SELECT 'TR-RC-016', 'Row Count: Security Master Position Cross-Ref (ISNMPCP)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), 111
  FROM DATACUT3.TREATS_ISNMPCP
UNION ALL
-- TR-RC-017 | Row Count: Security ID Master (TREATS_ISNMSDP)
SELECT 'TR-RC-017', 'Row Count: Security ID Master (ISNMSDP)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), 308
  FROM DATACUT3.TREATS_ISNMSDP
UNION ALL
-- TR-RC-018 | Row Count: Deal Delivery Instructions (TREATS_DEDLDIP)
SELECT 'TR-RC-018', 'Row Count: Deal Delivery Instructions (DEDLDIP)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), 235
  FROM DATACUT3.TREATS_DEDLDIP
UNION ALL
-- TR-RC-019 | Row Count: Counterparty Profile (TREATS_TTCPIPP)
SELECT 'TR-RC-019', 'Row Count: Counterparty Profile (TTCPIPP)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), 130
  FROM DATACUT3.TREATS_TTCPIPP
UNION ALL
-- TR-RC-020 | Row Count: Security ESG Profile (TREATS_ISNMESP)
SELECT 'TR-RC-020', 'Row Count: Security ESG Profile (ISNMESP)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), 111
  FROM DATACUT3.TREATS_ISNMESP
UNION ALL
-- TR-RC-021 | Row Count: Credit Limit Overlay Master (TREATS_CKOVLMP)
SELECT 'TR-RC-021', 'Row Count: Credit Limit Overlay Master (CKOVLMP)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), 108
  FROM DATACUT3.TREATS_CKOVLMP
UNION ALL
-- TR-RC-022 | Row Count: Credit Sub-Limit Master (TREATS_CKSBLMP)
SELECT 'TR-RC-022', 'Row Count: Credit Sub-Limit Master (CKSBLMP)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), 143
  FROM DATACUT3.TREATS_CKSBLMP
UNION ALL
-- TR-RC-023 | Row Count: Regulatory Reporting Key (TREATS_MPRKSFP)
SELECT 'TR-RC-023', 'Row Count: Regulatory Reporting Key (MPRKSFP)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), 3247
  FROM DATACUT3.TREATS_MPRKSFP
      ) x
    UNION ALL
    SELECT 'CAT-TR-02 DEAL STATUS DISTRIBUTION' AS dq_category, x.check_id, x.check_name, x.result_num, x.result_txt, x.expected
      FROM (
-- TR-DS-001 | FX Spot Deal Status Distribution (TADLST) — INFO
SELECT 'TR-DS-001' AS check_id, 'FX Spot Deal Status Distribution: MPESPTP' AS check_name,
       COUNT(*) AS RESULT_NUM, NVL(TADLST,'[NULL]') AS RESULT_TXT, CAST(NULL AS NUMBER) AS EXPECTED
  FROM DATACUT3.TREATS_MPESPTP GROUP BY TADLST
UNION ALL
-- TR-DS-002 | FX Forward Deal Status Distribution (TCDLST) — INFO
SELECT 'TR-DS-002', 'FX Forward Deal Status Distribution: MPEFWDP',
       COUNT(*), NVL(TCDLST,'[NULL]'), CAST(NULL AS NUMBER)
  FROM DATACUT3.TREATS_MPEFWDP GROUP BY TCDLST
UNION ALL
-- TR-DS-003 | MM/Cash Deposit Deal Status Distribution (TGDLST) — INFO
SELECT 'TR-DS-003', 'MM/Cash Deposit Deal Status Distribution: MPMZCPP',
       COUNT(*), NVL(TGDLST,'[NULL]'), CAST(NULL AS NUMBER)
  FROM DATACUT3.TREATS_MPMZCPP GROUP BY TGDLST
UNION ALL
-- TR-DS-004 | MM Deposit Additional Deal Status Distribution (T9DLST) — INFO
SELECT 'TR-DS-004', 'MM Deposit Additional Status Distribution: MPMMCPP',
       COUNT(*), NVL(T9DLST,'[NULL]'), CAST(NULL AS NUMBER)
  FROM DATACUT3.TREATS_MPMMCPP GROUP BY T9DLST
UNION ALL
-- TR-DS-005 | IRS Deal Status Distribution (T7DLST) — INFO
SELECT 'TR-DS-005', 'IRS Deal Status Distribution: MPMSWPP',
       COUNT(*), NVL(T7DLST,'[NULL]'), CAST(NULL AS NUMBER)
  FROM DATACUT3.TREATS_MPMSWPP GROUP BY T7DLST
UNION ALL
-- TR-DS-006 | NI/Bond/Repo Deal Status Distribution (TYDLST) — INFO
SELECT 'TR-DS-006', 'NI/Bond/Repo Deal Status Distribution: MPMNMCP',
       COUNT(*), NVL(TYDLST,'[NULL]'), CAST(NULL AS NUMBER)
  FROM DATACUT3.TREATS_MPMNMCP GROUP BY TYDLST
UNION ALL
-- TR-DS-007 | Active vs Closed FX Spot Deals (INFO)
SELECT 'TR-DS-007', 'FX Spot Active/Closed Deal Ratio: MPESPTP',
       COUNT(CASE WHEN TADLST NOT IN ('C','D','X') THEN 1 END),
       'ACTIVE_CNT | TOTAL=' || TO_CHAR(COUNT(*)), CAST(NULL AS NUMBER)
  FROM DATACUT3.TREATS_MPESPTP
UNION ALL
-- TR-DS-008 | Product Type Distribution — All Deal Tables (INFO)
SELECT 'TR-DS-008', 'Product Type Distribution: MPESPTP',
       COUNT(*), 'FX_SPOT|' || NVL(TAAPTY,'[NULL]'), CAST(NULL AS NUMBER)
  FROM DATACUT3.TREATS_MPESPTP GROUP BY TAAPTY
UNION ALL
SELECT 'TR-DS-008', 'Product Type Distribution: MPEFWDP',
       COUNT(*), 'FX_FWD|' || NVL(TCAPTY,'[NULL]'), CAST(NULL AS NUMBER)
  FROM DATACUT3.TREATS_MPEFWDP GROUP BY TCAPTY
UNION ALL
SELECT 'TR-DS-008', 'Product Type Distribution: MPMZCPP',
       COUNT(*), 'MM_DEP|' || NVL(TGAPTY,'[NULL]'), CAST(NULL AS NUMBER)
  FROM DATACUT3.TREATS_MPMZCPP GROUP BY TGAPTY
UNION ALL
SELECT 'TR-DS-008', 'Product Type Distribution: MPMSWPP',
       COUNT(*), 'IRS|' || NVL(T7APTY,'[NULL]'), CAST(NULL AS NUMBER)
  FROM DATACUT3.TREATS_MPMSWPP GROUP BY T7APTY
UNION ALL
SELECT 'TR-DS-008', 'Product Type Distribution: MPMNMCP',
       COUNT(*), 'NI_BOND|' || NVL(TYAPTY,'[NULL]'), CAST(NULL AS NUMBER)
  FROM DATACUT3.TREATS_MPMNMCP GROUP BY TYAPTY
      ) x
    UNION ALL
    SELECT 'CAT-TR-03 MANDATORY FIELDS - NULL/BLANK' AS dq_category, x.check_id, x.check_name, x.result_num, x.result_txt, x.expected
      FROM (
-- TR-NL-001 | Missing Deal Number — FX Spot (TADLNO)
SELECT 'TR-NL-001' AS check_id, 'Missing Deal Number: MPESPTP (TADLNO)' AS check_name,
       COUNT(*) AS RESULT_NUM, CAST(NULL AS VARCHAR2(200)) AS RESULT_TXT, CAST(NULL AS NUMBER) AS EXPECTED
  FROM DATACUT3.TREATS_MPESPTP
 WHERE TADLNO IS NULL OR TRIM(TADLNO) = ''
UNION ALL
-- TR-NL-002 | Missing Primary CCY — FX Spot (TACYPC)
SELECT 'TR-NL-002', 'Missing Primary CCY: MPESPTP (TACYPC)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.TREATS_MPESPTP
 WHERE TACYPC IS NULL OR TRIM(TACYPC) = ''
UNION ALL
-- TR-NL-003 | Missing Counter CCY — FX Spot (TACYCC)
SELECT 'TR-NL-003', 'Missing Counter CCY: MPESPTP (TACYCC)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.TREATS_MPESPTP
 WHERE TACYCC IS NULL OR TRIM(TACYCC) = ''
UNION ALL
-- TR-NL-004 | Missing Deal Number — FX Forward (TCDLNO)
SELECT 'TR-NL-004', 'Missing Deal Number: MPEFWDP (TCDLNO)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.TREATS_MPEFWDP
 WHERE TCDLNO IS NULL OR TRIM(TCDLNO) = ''
UNION ALL
-- TR-NL-005 | Missing Product Currency — MM Deposit (TGCCYC)
SELECT 'TR-NL-005', 'Missing Product Currency: MPMZCPP (TGCCYC)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.TREATS_MPMZCPP
 WHERE TGCCYC IS NULL OR TRIM(TGCCYC) = ''
UNION ALL
-- TR-NL-006 | Missing/Zero Principal — MM Deposit (TGPRCP)
SELECT 'TR-NL-006', 'Missing/Zero Principal: MPMZCPP (TGPRCP)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.TREATS_MPMZCPP
 WHERE TGPRCP IS NULL OR TGPRCP = 0
UNION ALL
-- TR-NL-007 | Missing Security Master Number — Security Master (RDSMNO)
SELECT 'TR-NL-007', 'Missing Security Master Number: ISNMMSP (RDSMNO)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.TREATS_ISNMMSP
 WHERE RDSMNO IS NULL OR TRIM(RDSMNO) = ''
UNION ALL
-- TR-NL-008 | Missing Product Currency — Security Master (RDPDCY)
SELECT 'TR-NL-008', 'Missing Product Currency: ISNMMSP (RDPDCY)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.TREATS_ISNMMSP
 WHERE RDPDCY IS NULL OR TRIM(RDPDCY) = ''
UNION ALL
-- TR-NL-009 | Missing Counterparty Acronym — Counterparty Profile (XJCPAC)
SELECT 'TR-NL-009', 'Missing Counterparty Acronym: TTCPIPP (XJCPAC)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.TREATS_TTCPIPP
 WHERE XJCPAC IS NULL OR TRIM(XJCPAC) = ''
UNION ALL
-- TR-NL-010 | Missing Security Number — NI/Bond Deals (TYSMNO)
SELECT 'TR-NL-010', 'Missing Security Number: MPMNMCP (TYSMNO)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.TREATS_MPMNMCP
 WHERE TYSMNO IS NULL OR TRIM(TYSMNO) = ''
UNION ALL
-- TR-NL-011 | Missing/Zero IRS Principal — Pay Leg (T7PRCP)
SELECT 'TR-NL-011', 'Missing/Zero IRS Principal: MPMSWPP (T7PRCP)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.TREATS_MPMSWPP
 WHERE T7PRCP IS NULL OR T7PRCP = 0
UNION ALL
-- TR-NL-012 | Missing Deal Number — Settlement Deal SI (GGDLNO)
SELECT 'TR-NL-012', 'Missing Deal Number: SEDLSIP (GGDLNO)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.TREATS_SEDLSIP
 WHERE GGDLNO IS NULL OR TRIM(GGDLNO) = ''
UNION ALL
-- TR-NL-013 | Missing Coupon Rate — Fixed Security Master (RDCPRT when RDFXFG='Y')
SELECT 'TR-NL-013', 'Missing Coupon Rate for Fixed Security: ISNMMSP (RDCPRT)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.TREATS_ISNMMSP
 WHERE RDFXFG = 'Y' AND (RDCPRT IS NULL OR RDCPRT = 0)
UNION ALL
-- TR-NL-014 | Missing Maturity Date — Security Master (RDMDAT)
SELECT 'TR-NL-014', 'Missing Maturity Date: ISNMMSP (RDMDAT)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.TREATS_ISNMMSP
 WHERE RDMDAT IS NULL
UNION ALL
-- TR-NL-015 | Missing Regulatory Key Value — Reg Reporting (RMVALU)
SELECT 'TR-NL-015', 'Missing Regulatory Key Value: MPRKSFP (RMVALU)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.TREATS_MPRKSFP
 WHERE RMVALU IS NULL OR TRIM(RMVALU) = ''
      ) x
    UNION ALL
    SELECT 'CAT-TR-04 DATE FIELD VALIDITY' AS dq_category, x.check_id, x.check_name, x.result_num, x.result_txt, x.expected
      FROM (
-- TR-DT-001 | FX Spot Deal Date Invalid or Missing (TADDAT)
SELECT 'TR-DT-001' AS check_id, 'FX Spot Deal Date Invalid or Missing: MPESPTP (TADDAT)' AS check_name,
       COUNT(*) AS RESULT_NUM, CAST(NULL AS VARCHAR2(200)) AS RESULT_TXT, CAST(NULL AS NUMBER) AS EXPECTED
  FROM DATACUT3.TREATS_MPESPTP
 WHERE TADDAT IS NULL
    OR TO_NUMBER(TO_CHAR(TADDAT,'YYYYMMDD')) NOT BETWEEN 19900101 AND 20991231
UNION ALL
-- TR-DT-002 | FX Spot Primary CCY Value Date Before Deal Date
SELECT 'TR-DT-002', 'FX Spot Value Date Before Deal Date: MPESPTP',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.TREATS_MPESPTP
 WHERE TAVDPC IS NOT NULL AND TADDAT IS NOT NULL AND TAVDPC < TADDAT
UNION ALL
-- TR-DT-003 | FX Forward Value Date Before Deal Date
SELECT 'TR-DT-003', 'FX Forward Value Date Before Deal Date: MPEFWDP',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.TREATS_MPEFWDP
 WHERE TCVDPC IS NOT NULL AND TCDDAT IS NOT NULL AND TCVDPC < TCDDAT
UNION ALL
-- TR-DT-004 | MM Deposit Maturity Date Before Value Date
SELECT 'TR-DT-004', 'MM Deposit Maturity Date Before Value Date: MPMZCPP',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.TREATS_MPMZCPP
 WHERE TGMDAT IS NOT NULL AND TGVDAT IS NOT NULL AND TGMDAT < TGVDAT
UNION ALL
-- TR-DT-005 | Active MM Deposit with Missing Maturity Date
SELECT 'TR-DT-005', 'Active MM Deposit Missing Maturity Date: MPMZCPP',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.TREATS_MPMZCPP
 WHERE TGDLST NOT IN ('C','D','X') AND TGMDAT IS NULL
UNION ALL
-- TR-DT-006 | IRS Maturity Date Before Value Date
SELECT 'TR-DT-006', 'IRS Maturity Date Before Value Date: MPMSWPP',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.TREATS_MPMSWPP
 WHERE T7MDAT IS NOT NULL AND T7VDAT IS NOT NULL AND T7MDAT < T7VDAT
UNION ALL
-- TR-DT-007 | NI/Bond Deal Maturity Before Issue Date
SELECT 'TR-DT-007', 'NI/Bond Maturity Before Issue Date: MPMNMCP',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.TREATS_MPMNMCP
 WHERE TYMDAT IS NOT NULL AND TYIDAT IS NOT NULL AND TYMDAT < TYIDAT
UNION ALL
-- TR-DT-008 | Security Master Maturity Before Issue Date
SELECT 'TR-DT-008', 'Security Master Maturity Before Issue Date: ISNMMSP',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.TREATS_ISNMMSP
 WHERE RDMDAT IS NOT NULL AND RDIDAT IS NOT NULL AND RDMDAT < RDIDAT
UNION ALL
-- TR-DT-009 | Regulatory Reporting Send Date Invalid (RMSDDT)
SELECT 'TR-DT-009', 'Regulatory Reporting Send Date Invalid: MPRKSFP (RMSDDT)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.TREATS_MPRKSFP
 WHERE RMSDDT IS NULL
    OR TO_NUMBER(TO_CHAR(RMSDDT,'YYYYMMDD')) NOT BETWEEN 20200101 AND 20991231
UNION ALL
-- TR-DT-010 | FX Forward Counter CCY Value Date Before Primary CCY Value Date
SELECT 'TR-DT-010', 'FX Forward Counter CCY VD Before Primary CCY VD: MPEFWDP',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.TREATS_MPEFWDP
 WHERE TCVDCC IS NOT NULL AND TCVDPC IS NOT NULL AND TCVDCC < TCVDPC
UNION ALL
-- TR-DT-011 | NI/Bond Value Date Before Deal Date
SELECT 'TR-DT-011', 'NI/Bond Value Date Before Deal Date: MPMNMCP',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.TREATS_MPMNMCP
 WHERE TYVDAT IS NOT NULL AND TYDDAT IS NOT NULL AND TYVDAT < TYDDAT
UNION ALL
-- TR-DT-012 | Active MM Deposit Past Maturity Date
SELECT 'TR-DT-012', 'Active MM Deposit Past Maturity Date (Overdue): MPMZCPP',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.TREATS_MPMZCPP
 WHERE TGDLST NOT IN ('C','D','X')
   AND TGMDAT IS NOT NULL
   AND TO_NUMBER(TO_CHAR(TGMDAT,'YYYYMMDD')) < TO_NUMBER(TO_CHAR(DATE '2026-06-15','YYYYMMDD'))
      ) x
    UNION ALL
    SELECT 'CAT-TR-05 NUMERIC INTEGRITY' AS dq_category, x.check_id, x.check_name, x.result_num, x.result_txt, x.expected
      FROM (
-- TR-NI-001 | Negative Principal — MM/Cash Deposit (TGPRCP < 0)
SELECT 'TR-NI-001' AS check_id, 'Negative Principal: MPMZCPP (TGPRCP)' AS check_name,
       COUNT(*) AS RESULT_NUM, CAST(NULL AS VARCHAR2(200)) AS RESULT_TXT, CAST(NULL AS NUMBER) AS EXPECTED
  FROM DATACUT3.TREATS_MPMZCPP WHERE TGPRCP < 0
UNION ALL
-- TR-NI-002 | Zero Principal on Active MM Deposits
SELECT 'TR-NI-002', 'Zero/NULL Principal on Active MM Deposit: MPMZCPP',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.TREATS_MPMZCPP
 WHERE TGDLST NOT IN ('C','D','X') AND (TGPRCP IS NULL OR TGPRCP = 0)
UNION ALL
-- TR-NI-003 | FX Spot Primary CCY Amount Zero or Negative (TAPCYA)
SELECT 'TR-NI-003', 'FX Spot Primary CCY Amount Zero or Negative: MPESPTP (TAPCYA)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.TREATS_MPESPTP WHERE TAPCYA IS NULL OR TAPCYA <= 0
UNION ALL
-- TR-NI-004 | FX Spot Counter CCY Amount Zero or Negative (TACCYA)
SELECT 'TR-NI-004', 'FX Spot Counter CCY Amount Zero or Negative: MPESPTP (TACCYA)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.TREATS_MPESPTP WHERE TACCYA IS NULL OR TACCYA <= 0
UNION ALL
-- TR-NI-005 | FX Forward Primary CCY Amount Zero or Negative (TCPCYA)
SELECT 'TR-NI-005', 'FX Forward Primary CCY Amount Zero or Negative: MPEFWDP (TCPCYA)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.TREATS_MPEFWDP WHERE TCPCYA IS NULL OR TCPCYA <= 0
UNION ALL
-- TR-NI-006 | IRS Principal Zero or Negative — Pay Leg (T7PRCP)
SELECT 'TR-NI-006', 'IRS Principal Zero or Negative — Pay Leg: MPMSWPP (T7PRCP)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.TREATS_MPMSWPP WHERE T7PRCP IS NULL OR T7PRCP <= 0
UNION ALL
-- TR-NI-007 | NI/Bond Nominal Value Zero or Negative (TYNMIN)
SELECT 'TR-NI-007', 'NI/Bond Nominal Value Zero or Negative: MPMNMCP (TYNMIN)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.TREATS_MPMNMCP WHERE TYNMIN IS NULL OR TYNMIN <= 0
UNION ALL
-- TR-NI-008 | Security Master Total Nominal Value Zero or Null (RDTLNV)
SELECT 'TR-NI-008', 'Security Master Total Nominal Value Zero/NULL: ISNMMSP (RDTLNV)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.TREATS_ISNMMSP WHERE RDTLNV = 0 OR RDTLNV IS NULL
UNION ALL
-- TR-NI-009 | FX Spot Primary CCY Amount Distribution (INFO)
SELECT 'TR-NI-009', 'FX Spot Primary CCY Distribution + Total: MPESPTP',
       COUNT(*),
       TACYPC || ' [Tot=' || TO_CHAR(SUM(TAPCYA)/100,'FM999,999,999,999') || ']',
       CAST(NULL AS NUMBER)
  FROM DATACUT3.TREATS_MPESPTP
 GROUP BY TACYPC
UNION ALL
-- TR-NI-010 | MM Deposit Principal Distribution by Currency (INFO)
SELECT 'TR-NI-010', 'MM Deposit Principal Distribution by CCY (Active): MPMZCPP',
       COUNT(*),
       TGCCYC || ' [Tot=' || TO_CHAR(SUM(TGPRCP)/100,'FM999,999,999,999') || ']',
       CAST(NULL AS NUMBER)
  FROM DATACUT3.TREATS_MPMZCPP
 WHERE TGDLST NOT IN ('C','D','X')
 GROUP BY TGCCYC
      ) x
    UNION ALL
    SELECT 'CAT-TR-06 FX DEAL DOMAIN CHECKS' AS dq_category, x.check_id, x.check_name, x.result_num, x.result_txt, x.expected
      FROM (
-- TR-FX-001 | FX Spot Deals Without Spot Rate (TASTOR = 0 or NULL)
SELECT 'TR-FX-001' AS check_id, 'FX Spot Deals Without Spot Rate: MPESPTP (TASTOR)' AS check_name,
       COUNT(*) AS RESULT_NUM, CAST(NULL AS VARCHAR2(200)) AS RESULT_TXT, CAST(NULL AS NUMBER) AS EXPECTED
  FROM DATACUT3.TREATS_MPESPTP
 WHERE TASTOR IS NULL OR TASTOR = 0
UNION ALL
-- TR-FX-002 | FX Spot Same Primary and Counter Currency (TACYPC = TACYCC)
SELECT 'TR-FX-002', 'FX Spot Same Primary and Counter Currency: MPESPTP',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.TREATS_MPESPTP WHERE TACYPC = TACYCC
UNION ALL
-- TR-FX-003 | FX Forward Without Forward Rate (TCFTOR = 0 or NULL)
SELECT 'TR-FX-003', 'FX Forward Without Forward Rate: MPEFWDP (TCFTOR)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.TREATS_MPEFWDP WHERE TCFTOR IS NULL OR TCFTOR = 0
UNION ALL
-- TR-FX-004 | FX Forward Same Primary and Counter Currency
SELECT 'TR-FX-004', 'FX Forward Same Primary and Counter Currency: MPEFWDP',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.TREATS_MPEFWDP WHERE TCCYPC = TCCYCC
UNION ALL
-- TR-FX-005 | FX Spot Primary CCY Distribution (INFO)
SELECT 'TR-FX-005', 'FX Spot Primary CCY Distribution: MPESPTP',
       COUNT(*), NVL(TACYPC,'[NULL]'), CAST(NULL AS NUMBER)
  FROM DATACUT3.TREATS_MPESPTP GROUP BY TACYPC
UNION ALL
-- TR-FX-006 | FX Forward Primary CCY Distribution (INFO)
SELECT 'TR-FX-006', 'FX Forward Primary CCY Distribution: MPEFWDP',
       COUNT(*), NVL(TCCYPC,'[NULL]'), CAST(NULL AS NUMBER)
  FROM DATACUT3.TREATS_MPEFWDP GROUP BY TCCYPC
UNION ALL
-- TR-FX-007 | FX Spot Deals Without Exchange ID (TAEXID)
SELECT 'TR-FX-007', 'FX Spot Deals Without Exchange ID: MPESPTP (TAEXID)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.TREATS_MPESPTP WHERE TAEXID IS NULL OR TRIM(TAEXID) = ''
UNION ALL
-- TR-FX-008 | FX Forward Without Maturity Code (TCMATC)
SELECT 'TR-FX-008', 'FX Forward Without Maturity Code: MPEFWDP (TCMATC)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.TREATS_MPEFWDP WHERE TCMATC IS NULL OR TRIM(TCMATC) = ''
UNION ALL
-- TR-FX-009 | FX Spot Deal Date Distribution by Month (Last 12 months — INFO)
SELECT 'TR-FX-009', 'FX Spot Deal Date Monthly Distribution: MPESPTP',
       COUNT(*), TO_CHAR(TADDAT,'YYYY-MM'), CAST(NULL AS NUMBER)
  FROM DATACUT3.TREATS_MPESPTP
 WHERE TADDAT IS NOT NULL
   AND TADDAT >= ADD_MONTHS(DATE '2026-06-15',-12)
 GROUP BY TO_CHAR(TADDAT,'YYYY-MM')
UNION ALL
-- TR-FX-010 | FX Spot Ext/Int/Retail/Arb Indicator Distribution (INFO)
SELECT 'TR-FX-010', 'FX Spot EXT/INT/RET/ARB Indicator Distribution: MPESPTP',
       COUNT(*), NVL(TAEIRI,'[NULL]'), CAST(NULL AS NUMBER)
  FROM DATACUT3.TREATS_MPESPTP GROUP BY TAEIRI
      ) x
    UNION ALL
    SELECT 'CAT-TR-07 MM / SECURITIES / IRS DOMAIN CHECKS' AS dq_category, x.check_id, x.check_name, x.result_num, x.result_txt, x.expected
      FROM (
-- TR-MM-001 | MM Deposit Interest Rate = 0 for Active Deals (TGDLIR)
SELECT 'TR-MM-001' AS check_id, 'MM Deposit Interest Rate Zero (Active): MPMZCPP (TGDLIR)' AS check_name,
       COUNT(*) AS RESULT_NUM, CAST(NULL AS VARCHAR2(200)) AS RESULT_TXT, CAST(NULL AS NUMBER) AS EXPECTED
  FROM DATACUT3.TREATS_MPMZCPP
 WHERE TGDLST NOT IN ('C','D','X') AND (TGDLIR IS NULL OR TGDLIR = 0)
UNION ALL
-- TR-MM-002 | MM Deposit Interest Rate > 50% (Anomaly) (TGDLIR > 50)
SELECT 'TR-MM-002', 'MM Deposit Interest Rate Anomaly (>50%): MPMZCPP (TGDLIR)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.TREATS_MPMZCPP WHERE TGDLIR > 50
UNION ALL
-- TR-MM-003 | IRS Fixed Rate Zero on Both Legs (Active Deals)
SELECT 'TR-MM-003', 'IRS Fixed Rate Zero Both Legs (Active): MPMSWPP',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.TREATS_MPMSWPP
 WHERE T7DLST NOT IN ('C','D','X')
   AND (T7XRAP IS NULL OR T7XRAP = 0) AND (T7XRAR IS NULL OR T7XRAR = 0)
UNION ALL
-- TR-MM-004 | IRS Currency Distribution + Total Principal (INFO)
SELECT 'TR-MM-004', 'IRS Currency Distribution + Total Principal: MPMSWPP',
       COUNT(*),
       NVL(T7CCYP,'[NULL]') || ' [Tot=' || TO_CHAR(SUM(T7PRCP)/100,'FM999,999,999,999') || ']',
       CAST(NULL AS NUMBER)
  FROM DATACUT3.TREATS_MPMSWPP GROUP BY T7CCYP
UNION ALL
-- TR-MM-005 | NI/Bond/Repo Deal Product Type Distribution (INFO)
SELECT 'TR-MM-005', 'NI/Bond/Repo Product Type Distribution: MPMNMCP',
       COUNT(*), NVL(TYAPTY,'[NULL]'), CAST(NULL AS NUMBER)
  FROM DATACUT3.TREATS_MPMNMCP GROUP BY TYAPTY
UNION ALL
-- TR-MM-006 | Security Master Missing Coupon Rate for Fixed Securities
SELECT 'TR-MM-006', 'Missing Coupon Rate for Fixed Security: ISNMMSP (RDCPRT)',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.TREATS_ISNMMSP
 WHERE RDFXFG = 'Y' AND (RDCPRT IS NULL OR RDCPRT = 0)
UNION ALL
-- TR-MM-007 | Security Master Currency Distribution (INFO)
SELECT 'TR-MM-007', 'Security Master Currency Distribution: ISNMMSP',
       COUNT(*), NVL(RDPDCY,'[NULL]'), CAST(NULL AS NUMBER)
  FROM DATACUT3.TREATS_ISNMMSP GROUP BY RDPDCY
UNION ALL
-- TR-MM-008 | MM Deposit Rollover Method Distribution (INFO)
SELECT 'TR-MM-008', 'MM Deposit Rollover Method Distribution: MPMZCPP (TGROMD)',
       COUNT(*), NVL(TGROMD,'[NULL]'), CAST(NULL AS NUMBER)
  FROM DATACUT3.TREATS_MPMZCPP GROUP BY TGROMD
UNION ALL
-- TR-MM-009 | Swap Schedule Cashflows Without Deal Number (T6DLNO)
-- TODO: Confirm deal number field name for MPSWSCP (T6DLNO assumed from DD naming pattern)
SELECT 'TR-MM-009', 'Swap Schedule Cashflow Without Deal Number: MPSWSCP (T6DLNO) [TODO-verify field]',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.TREATS_MPSWSCP
 WHERE T6DLNO IS NULL OR TRIM(T6DLNO) = ''
UNION ALL
-- TR-MM-010 | Regulatory Reporting Jurisdiction Distribution (INFO)
SELECT 'TR-MM-010', 'Regulatory Reporting Jurisdiction Distribution: MPRKSFP',
       COUNT(*), NVL(RMJURI,'[NULL]'), CAST(NULL AS NUMBER)
  FROM DATACUT3.TREATS_MPRKSFP GROUP BY RMJURI
      ) x
    UNION ALL
    SELECT 'CAT-TR-08 CROSS-MODULE REFERENTIAL INTEGRITY - TREATS -> HUB' AS dq_category, x.check_id, x.check_name, x.result_num, x.result_txt, x.expected
      FROM (
-- TR-RI-001 | TREATS Local Branch Reference Without HUB GL Account (placeholder)
-- TODO: TALCBK/TALCBN linkage to HUB GLACMSP branch not confirmed — COUNT(*) only
SELECT 'TR-RI-001' AS check_id,
       'TREATS FX Spot Without Local Branch (COUNT placeholder) [TODO-confirm linkage]' AS check_name,
       COUNT(*) AS RESULT_NUM, CAST(NULL AS VARCHAR2(200)) AS RESULT_TXT, CAST(NULL AS NUMBER) AS EXPECTED
  FROM DATACUT3.TREATS_MPESPTP WHERE TALCBN IS NULL
UNION ALL

-- TR-RI-002 | TREATS Counterparty Profile Volume (placeholder for → HUB cross-check)
-- TODO: XJCPAC → HUB SSCUSTP linkage key not confirmed — COUNT(*) only
SELECT 'TR-RI-002',
       'TREATS Counterparty Profile Count (placeholder) [TODO-confirm HUB linkage]',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.TREATS_TTCPIPP
UNION ALL

-- TR-RI-003 | TREATS Settlement Deal SI Without Matching Deal (GGDLNO orphan)
-- ANALYSIS: Every settlement SI must reference a valid deal across all deal tables.
SELECT 'TR-RI-003',
       'Settlement Deal SI Without Matching Deal in Any TREATS Deal Table: SEDLSIP',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.TREATS_SEDLSIP S
 WHERE S.GGDLNO IS NOT NULL
   AND NOT EXISTS (SELECT 1 FROM DATACUT3.TREATS_MPESPTP T WHERE T.TADLNO = S.GGDLNO)
   AND NOT EXISTS (SELECT 1 FROM DATACUT3.TREATS_MPEFWDP T WHERE T.TCDLNO = S.GGDLNO)
   AND NOT EXISTS (SELECT 1 FROM DATACUT3.TREATS_MPMSWPP T WHERE T.T7DLNO = S.GGDLNO)
   AND NOT EXISTS (SELECT 1 FROM DATACUT3.TREATS_MPMNMCP T WHERE T.TYDLNO = S.GGDLNO)
   AND NOT EXISTS (SELECT 1 FROM DATACUT3.TREATS_MPMZCPP T WHERE T.TGDLNO = S.GGDLNO)
UNION ALL

-- TR-RI-004 | Delivery Instructions Without Matching NI/Bond Deal (APDLNO → TYDLNO)
SELECT 'TR-RI-004',
       'Deal Delivery Instructions Without Matching NI/Bond Deal: DEDLDIP',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.TREATS_DEDLDIP D
 WHERE D.APDLNO IS NOT NULL
   AND NOT EXISTS (SELECT 1 FROM DATACUT3.TREATS_MPMNMCP T WHERE T.TYDLNO = D.APDLNO)
UNION ALL

-- TR-RI-005 | Security Position Cross-Ref Without Security Master (RHSMNO → RDSMNO)
SELECT 'TR-RI-005',
       'Security Position Cross-Ref Without Security Master: ISNMPCP',
       COUNT(*), CAST(NULL AS VARCHAR2(200)), CAST(NULL AS NUMBER)
  FROM DATACUT3.TREATS_ISNMPCP P
 WHERE P.RHSMNO IS NOT NULL
   AND NOT EXISTS (SELECT 1 FROM DATACUT3.TREATS_ISNMMSP M WHERE M.RDSMNO = P.RHSMNO)
      ) x
) y
ORDER BY y.dq_category, y.check_id;